# English (United States) translations for trove.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the trove project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version:  trove\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-05-23 06:05+0000\n"
"PO-Revision-Date: 2014-03-19 18:14+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: English (United States) "
"(http://www.transifex.com/projects/p/openstack/language/en_US/)\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: trove/backup/models.py:280
#, python-format
msgid "Checking if backup exist in '%s'"
msgstr ""

#: trove/backup/models.py:283
msgid "Checking if backup checksum matches swift."
msgstr ""

#: trove/backup/service.py:49
#, python-format
msgid "Showing a backup for tenant '%s'"
msgstr ""

#: trove/backup/service.py:50 trove/extensions/mgmt/host/service.py:45
#: trove/extensions/mgmt/instances/service.py:73
#: trove/extensions/mgmt/instances/service.py:151
#: trove/extensions/mgmt/instances/service.py:182 trove/instance/service.py:158
#: trove/instance/service.py:170
#, python-format
msgid ""
"id : '%s'\n"
"\n"
msgstr ""

#: trove/cmd/manage.py:130
#, python-format
msgid "Possible wrong number of arguments supplied %s"
msgstr ""

#: trove/cmd/manage.py:133
msgid "Command failed, please check log for more info."
msgstr ""

#: trove/common/auth.py:63
#, python-format
msgid "Authorized tenant '%(tenant_id)s' request: %(request)s"
msgstr ""

#: trove/common/auth.py:67
#, python-format
msgid "User with tenant id %s cannot access this resource"
msgstr ""

#: trove/common/exception.py:55
#, python-format
msgid "Failed to save %(model_name)s because: %(error)s"
msgstr ""

#: trove/common/exception.py:60
msgid "Invalid RPC Connection Reuse"
msgstr ""

#: trove/common/exception.py:65 trove/common/exception.py:70
#, python-format
msgid "Resource %(uuid)s cannot be found"
msgstr ""

#: trove/common/exception.py:75
#, python-format
msgid "User %(uuid)s cannot be found on the instance."
msgstr ""

#: trove/common/exception.py:80
#, python-format
msgid "Database %(uuid)s cannot be found on the instance."
msgstr ""

#: trove/common/exception.py:85
#, python-format
msgid "Cannot find compute instance %(server_id)s for instance %(instance_id)s."
msgstr ""

#: trove/common/exception.py:88
#, python-format
msgid "Resource %(instance_id)s can not be retrieved."
msgstr ""

#: trove/common/exception.py:93
#, python-format
msgid "DnsRecord with name= %(name)s not found."
msgstr ""

#: trove/common/exception.py:98
#, python-format
msgid "Datastore '%(datastore)s' cannot be found."
msgstr ""

#: trove/common/exception.py:103
#, python-format
msgid "Datastore version '%(version)s' cannot be found."
msgstr ""

#: trove/common/exception.py:108
msgid "Datastores cannot be found."
msgstr ""

#: trove/common/exception.py:113
#, python-format
msgid "Datastore '%(datastore)s' has no version '%(version)s'."
msgstr ""

#: trove/common/exception.py:118
#, python-format
msgid "Datastore version '%(version)s' is not active."
msgstr ""

#: trove/common/exception.py:123
msgid "Please specify datastore."
msgstr ""

#: trove/common/exception.py:128
#, python-format
msgid "Default version for datastore '%(datastore)s' not found."
msgstr ""

#: trove/common/exception.py:133
#, python-format
msgid ""
"The '%(operation)s' operation is not supported for the '%(datastore)s' "
"datastore."
msgstr ""

#: trove/common/exception.py:139
#, python-format
msgid "Multiple matches found for '%(name)s', iuse an UUID to be more specific."
msgstr ""

#: trove/common/exception.py:145
msgid "The server rejected the request due to its size or rate."
msgstr ""

#: trove/common/exception.py:151
#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr ""

#: trove/common/exception.py:156
msgid "Instance volume quota exceeded."
msgstr ""

#: trove/common/exception.py:161
#, python-format
msgid "An error occurred communicating with the guest: %(original_message)s."
msgstr ""

#: trove/common/exception.py:167
msgid "Timeout trying to connect to the Guest Agent."
msgstr ""

#: trove/common/exception.py:172
msgid ""
"The server could not comply with the request since it is either malformed"
" or otherwise incorrect."
msgstr ""

#: trove/common/exception.py:178
#, python-format
msgid "Required element/key - %(key)s was not specified"
msgstr ""

#: trove/common/exception.py:183
#, python-format
msgid "A database with the name \"%(name)s\" already exists."
msgstr ""

#: trove/common/exception.py:188
#, python-format
msgid "A user with the name \"%(name)s\" already exists."
msgstr ""

#: trove/common/exception.py:193
msgid ""
"A configuration group cannot be deleted if it is associated with one or "
"more non-terminated instances. Detach the configuration group from all "
"non-terminated instances and please try again."
msgstr ""

#: trove/common/exception.py:201
msgid "Unable to process the contained request"
msgstr ""

#: trove/common/exception.py:206
msgid "When resizing, instances must change size!"
msgstr ""

#: trove/common/exception.py:211
msgid "Cannot find the volumes attached to compute instance %(server_id)"
msgstr ""

#: trove/common/exception.py:217
msgid "Failed to create a volume in Nova."
msgstr ""

#: trove/common/exception.py:222
msgid "Volume size was not specified."
msgstr ""

#: trove/common/exception.py:227
#, python-format
msgid "Local storage not specified in flavor ID: %(flavor)s."
msgstr ""

#: trove/common/exception.py:232
msgid "Local storage support is not enabled."
msgstr ""

#: trove/common/exception.py:237
msgid "Volume support is not enabled."
msgstr ""

#: trove/common/exception.py:242
#, python-format
msgid ""
"An error occurred communicating with the task manager: "
"%(original_message)s."
msgstr ""

#: trove/common/exception.py:248
#, python-format
msgid "Value could not be converted: %(msg)s"
msgstr ""

#: trove/common/exception.py:253
msgid "Polling request timed out."
msgstr ""

#: trove/common/exception.py:258
msgid "User does not have admin privileges."
msgstr ""

#: trove/common/exception.py:263
#, python-format
msgid "The following values are invalid: %(errors)s"
msgstr ""

#: trove/common/exception.py:268
msgid "Not Found"
msgstr ""

#: trove/common/exception.py:273
msgid "Failed to update instances"
msgstr ""

#: trove/common/exception.py:278
msgid "Config file not found"
msgstr ""

#: trove/common/exception.py:283
msgid "Paste app not found."
msgstr ""

#: trove/common/exception.py:287
msgid "Quota could not be found"
msgstr ""

#: trove/common/exception.py:291
#, python-format
msgid "Quota for tenant %(tenant_id)s could not be found."
msgstr ""

#: trove/common/exception.py:295
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: trove/common/exception.py:299
msgid "Unable to upload Backup onto swift"
msgstr ""

#: trove/common/exception.py:303
msgid "Unable to download Backup from swift"
msgstr ""

#: trove/common/exception.py:307
msgid "Unable to create Backup"
msgstr ""

#: trove/common/exception.py:311
msgid "Unable to update Backup table in db"
msgstr ""

#: trove/common/exception.py:316
msgid "Failed to create Security Group."
msgstr ""

#: trove/common/exception.py:321
msgid "Failed to delete Security Group."
msgstr ""

#: trove/common/exception.py:326
msgid "Failed to create Security Group Rule."
msgstr ""

#: trove/common/exception.py:331
msgid "Failed to delete Security Group Rule."
msgstr ""

#: trove/common/exception.py:336
#, python-format
msgid ""
"Error creating security group rules. Malformed port(s). Port(s) is not "
"integer. FromPort = %(from)s greater than ToPort = %(to)s"
msgstr ""

#: trove/common/exception.py:343
#, python-format
msgid "Unable to create instance because backup %(backup_id)s is not completed"
msgstr ""

#: trove/common/exception.py:348
#, python-format
msgid "Backup file in %(location)s was not found in the object storage."
msgstr ""

#: trove/common/exception.py:353
#, python-format
msgid ""
"The datastore-version from which the backup was taken, %(version1)s, does"
" not match the destination datastore-version of %(version2)s"
msgstr ""

#: trove/common/exception.py:359
#, python-format
msgid "Swift account not accessible for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:363
#, python-format
msgid ""
"The request indicates that user %(user)s should have access to database "
"%(database)s, but database %(database)s is not included in the initial "
"databases list."
msgstr ""

#: trove/common/exception.py:369
msgid ""
"Two or more databases share the same name in the initial databases list. "
"Please correct the names or remove the duplicate entries."
msgstr ""

#: trove/common/exception.py:375
msgid ""
"Two or more users share the same name and host in the initial users list."
" Please correct the names or remove the duplicate entries."
msgstr ""

#: trove/common/exception.py:381
#, python-format
msgid ""
"Current Swift object checksum does not match original checksum for backup"
" %(backup_id)s."
msgstr ""

#: trove/common/exception.py:386
#, python-format
msgid "%(key)s is not a supported configuration parameter"
msgstr ""

#: trove/common/exception.py:390
#, python-format
msgid "No configuration parser found for datastore %(datastore_manager)s"
msgstr ""

#: trove/common/exception.py:395
#, python-format
msgid ""
"Datastore Version on Configuration %(config_datastore_version)s does not "
"match the Datastore Version on the instance "
"%(instance_datastore_version)s."
msgstr ""

#: trove/common/exception.py:402
#, python-format
msgid ""
"%(parameter_name)s parameter can no longer be  set as of "
"%(parameter_deleted_at)s"
msgstr ""

#: trove/common/exception.py:407
#, python-format
msgid ""
"Instance %(instance_id)s already has a Configuration Group attached: "
"%(configuration_id)s."
msgstr ""

#: trove/common/exception.py:412
#, python-format
msgid ""
"The operation you have requested cannot be executed because the instance "
"status is currently: %(status)s"
msgstr ""

#: trove/common/exception.py:418
#, python-format
msgid ""
"Multiple matches for service_type=%(service_type)s and "
"endpoint_region=%(endpoint_region)s. This generally means that a region "
"is required and you have not supplied one."
msgstr ""

#: trove/common/limits.py:87
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: trove/common/limits.py:211
msgid "This request was rate-limited."
msgstr ""

#: trove/common/utils.py:221
msgid "in looping call"
msgstr ""

#: trove/common/utils.py:277 trove/common/utils.py:292
#, python-format
msgid ""
"Time out after waiting %(time)s seconds when running proc: %(args)s "
"%(kwargs)s"
msgstr ""

#: trove/common/wsgi.py:145
msgid "version not supported"
msgstr ""

#: trove/common/wsgi.py:519
msgid "Invalid service catalog json."
msgstr ""

#: trove/common/wsgi.py:564
#, python-format
msgid "Caught error: %s"
msgstr ""

#: trove/conductor/manager.py:45
#, python-format
msgid "[Instance %s] sent field not present. Cannot compare."
msgstr ""

#: trove/conductor/manager.py:75
#, python-format
msgid "[Instance %s] Rec'd message is older than last seen. Discarding."
msgstr ""

#: trove/conductor/manager.py:108
#, python-format
msgid ""
"[Instance: %(instance)s] Backup IDs mismatch! Expected %(expected)s, "
"found %(found)s"
msgstr ""

#: trove/conductor/manager.py:117
#, python-format
msgid ""
"[Instance: %(instance)s] Backup instance IDs mismatch! Expected "
"%(expected)s, found %(found)s"
msgstr ""

#: trove/configuration/models.py:138
#, python-format
msgid "Configuration group with ID %s could not be found."
msgstr ""

#: trove/configuration/service.py:122
#, python-format
msgid "Updating configuration for tenant id %s"
msgstr ""

#: trove/configuration/service.py:141 trove/configuration/service.py:152
#, python-format
msgid "loaded configuration instances: %s"
msgstr ""

#: trove/configuration/service.py:160
#, python-format
msgid "loaded configuration group: %s"
msgstr ""

#: trove/configuration/service.py:177
msgid "Validating configuration values"
msgstr ""

#: trove/configuration/service.py:196
#, python-format
msgid ""
"The value provided for the configuration parameter %(key)s is not of type"
" %(type)s."
msgstr ""

#: trove/configuration/service.py:205
msgid ""
"Invalid or unsupported min value defined in the configuration-parameters "
"configuration file. Expected integer."
msgstr ""

#: trove/configuration/service.py:211
#, python-format
msgid ""
"The value for the configuration parameter %(key)s is less than the "
"minimum allowed: %(min)s"
msgstr ""

#: trove/configuration/service.py:219
msgid ""
"Invalid or unsupported max value defined in the configuration-parameters "
"configuration file. Expected integer."
msgstr ""

#: trove/configuration/service.py:225
#, python-format
msgid ""
"The value for the configuration parameter %(key)s is greater than the "
"maximum allowed: %(max)s"
msgstr ""

#: trove/configuration/service.py:239
msgid ""
"Invalid or unsupported type defined in the configuration-parameters "
"configuration file."
msgstr ""

#: trove/configuration/service.py:249
#, python-format
msgid "%s is not a supported configuration parameter."
msgstr ""

#: trove/db/models.py:98 trove/db/models.py:105 trove/dns/models.py:68
#, python-format
msgid "%s Not Found"
msgstr ""

#: trove/db/sqlalchemy/session.py:77
#, python-format
msgid "Creating SQLAlchemy engine with args: %s"
msgstr ""

#: trove/extensions/account/service.py:35
#: trove/extensions/account/service.py:46
#: trove/extensions/mgmt/host/service.py:34
#: trove/extensions/mgmt/host/service.py:43
#: trove/extensions/mgmt/instances/service.py:50
#: trove/extensions/mgmt/instances/service.py:71
#: trove/extensions/mgmt/instances/service.py:149
#: trove/extensions/mgmt/instances/service.py:168
#: trove/extensions/mgmt/instances/service.py:180
#: trove/extensions/mgmt/quota/service.py:33
#: trove/extensions/mgmt/volume/service.py:33
#: trove/extensions/mysql/service.py:44 trove/extensions/mysql/service.py:52
#: trove/extensions/mysql/service.py:74 trove/extensions/mysql/service.py:85
#: trove/extensions/mysql/service.py:98 trove/extensions/mysql/service.py:121
#: trove/extensions/mysql/service.py:138 trove/extensions/mysql/service.py:160
#: trove/extensions/mysql/service.py:208 trove/extensions/mysql/service.py:224
#: trove/extensions/mysql/service.py:239 trove/extensions/mysql/service.py:262
#: trove/extensions/mysql/service.py:273 trove/extensions/mysql/service.py:283
#: trove/instance/service.py:133 trove/instance/service.py:144
#: trove/instance/service.py:156 trove/instance/service.py:168
#: trove/instance/service.py:181
#, python-format
msgid ""
"req : '%s'\n"
"\n"
msgstr ""

#: trove/extensions/account/service.py:36
#, python-format
msgid "Showing account information for '%(account)s' to '%(tenant)s'"
msgstr ""

#: trove/extensions/account/service.py:47
#, python-format
msgid "Showing all accounts with instances for '%s'"
msgstr ""

#: trove/extensions/mgmt/host/service.py:35
#, python-format
msgid "Indexing a host for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/host/service.py:44
#, python-format
msgid "Showing a host for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/host/instance/service.py:34
#: trove/extensions/mgmt/host/instance/service.py:52
#: trove/extensions/mgmt/instances/service.py:92
#: trove/extensions/mgmt/instances/service.py:115
#: trove/extensions/mgmt/quota/service.py:43 trove/instance/service.py:78
msgid "Invalid request body."
msgstr ""

#: trove/extensions/mgmt/host/instance/service.py:42
#: trove/extensions/mgmt/instances/service.py:105
msgid "Only one action can be specified per request."
msgstr ""

#: trove/extensions/mgmt/host/instance/service.py:46
#, python-format
msgid "Invalid host action: %s"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:51 trove/instance/service.py:134
#, python-format
msgid "Indexing a database instance for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:72 trove/instance/service.py:157
#, python-format
msgid "Showing a database instance for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:109
#, python-format
msgid "Invalid instance action: %s"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:150
#, python-format
msgid "Showing root history for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:169
#, python-format
msgid "Showing hardware info for instance '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:181
#, python-format
msgid "Showing a instance diagnostics for instance '%s'"
msgstr ""

#: trove/extensions/mgmt/quota/service.py:34
#, python-format
msgid "Indexing quota info for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/volume/service.py:34
#, python-format
msgid "Indexing storage info for tenant '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:43
#, python-format
msgid "Getting root enabled for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:51
#, python-format
msgid "Enabling root for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:73
#, python-format
msgid "Listing users for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:84
#, python-format
msgid "Creating users for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:86 trove/extensions/mysql/service.py:274
#: trove/instance/service.py:182
#, python-format
msgid ""
"body : '%s'\n"
"\n"
msgstr ""

#: trove/extensions/mysql/service.py:97
#, python-format
msgid "Deleting user for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:120
#, python-format
msgid "Showing a user for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:137
#, python-format
msgid "Updating user attributes for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:159
#, python-format
msgid "Updating user passwords for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:207
#, python-format
msgid "Showing user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:214 trove/extensions/mysql/service.py:229
#: trove/extensions/mysql/service.py:244
#, python-format
msgid "No such user: %(user)s "
msgstr ""

#: trove/extensions/mysql/service.py:223
#, python-format
msgid "Granting user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:238
#, python-format
msgid "Revoking user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:261
#, python-format
msgid "Listing schemas for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:272
#, python-format
msgid "Creating schema for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:282
#, python-format
msgid "Deleting schema for instance '%s'"
msgstr ""

#: trove/extensions/security_group/models.py:78
#, python-format
msgid "Security Group for %s"
msgstr ""

#: trove/extensions/security_group/models.py:132
#, python-format
msgid "Security Group with id: %(id)s already had been deleted"
msgstr ""

#: trove/extensions/security_group/service.py:127
#, python-format
msgid "Create Security Group Rules Required field(s) - %s"
msgstr ""

#: trove/guestagent/pkg.py:111
#, python-format
msgid "Error removing conflict %s"
msgstr ""

#: trove/guestagent/pkg.py:207
msgid "version() saw unexpected output from rpm!"
msgstr ""

#: trove/guestagent/pkg.py:230
msgid "Error fixing dpkg"
msgstr ""

#: trove/guestagent/pkg.py:336
msgid "Error updating the apt sources"
msgstr ""

#: trove/guestagent/volume.py:60
#, python-format
msgid "InvalidDevicePath(path=%s)"
msgstr ""

#: trove/guestagent/volume.py:72
msgid "Device path at {0} did not seem to be {1}."
msgstr ""

#: trove/guestagent/volume.py:76
msgid "Volume was not formatted."
msgstr ""

#: trove/guestagent/volume.py:116
#, python-format
msgid "Error resizing the filesystem: %s"
msgstr ""

#: trove/guestagent/volume.py:129
#, python-format
msgid "Device %(device)s is already mounted in %(mount_point)s"
msgstr ""

#: trove/guestagent/volume.py:132
#, python-format
msgid "Unmounting %s"
msgstr ""

#: trove/guestagent/volume.py:144
#, python-format
msgid "Could not obtain a list of mount points for device: %s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:68
#, python-format
msgid "Running backup %(id)s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:77
#, python-format
msgid "Using incremental runner: %s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:105
#, python-format
msgid "Starting Backup %s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:118
#, python-format
msgid "Backup %(backup_id)s completed status: %(success)s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:120
#, python-format
msgid "Backup %(backup_id)s file swift checksum: %(checksum)s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:122
#, python-format
msgid "Backup %(backup_id)s location: %(location)s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:131
#, python-format
msgid "Error saving %(backup_id)s Backup"
msgstr ""

#: trove/guestagent/backup/backupagent.py:140
#, python-format
msgid "Error running backup: %(backup_id)s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:147
#, python-format
msgid "Saving %(backup_id)s Backup Info to model"
msgstr ""

#: trove/guestagent/backup/backupagent.py:171
#, python-format
msgid "Restore from backup %(id)s completed successfully to %(restore_location)s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:173
#, python-format
msgid "Restore size: %s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:177
#, python-format
msgid "Error restoring backup %(id)s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:181
#, python-format
msgid "Restored Backup %(id)s"
msgstr ""

#: trove/guestagent/datastore/cassandra/manager.py:64
msgid "Setting status BUILDING"
msgstr ""

#: trove/guestagent/datastore/cassandra/manager.py:70
msgid "Config processing"
msgstr ""

#: trove/guestagent/datastore/cassandra/manager.py:87
#: trove/guestagent/datastore/mongodb/manager.py:77
msgid "\"prepare\" call has finished."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:45
msgid "Preparing Guest as Cassandra Server"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:48
#: trove/guestagent/datastore/mysql/service.py:597
#: trove/guestagent/datastore/redis/service.py:149
msgid "Dbaas install_if_needed complete"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:66
msgid "Error while initiating storage structure."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:86
msgid "Error killing stalled Cassandra start command."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:89
msgid "Could not start Cassandra"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:100
#: trove/guestagent/datastore/cassandra/service.py:102
msgid "Could not stop Cassandra"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:107
msgid "Restarting DB"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:120
#, python-format
msgid "Defining temp config holder at %s"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:124
msgid "Writing new config"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:128
msgid "Overriding old config"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:133
msgid "Opening cassandra.yaml"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:135
msgid "Preparing YAML object from cassandra.yaml"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:144
#: trove/guestagent/datastore/cassandra/service.py:161
#, python-format
msgid "Updating cassandra.yaml with %(key)s: %(value)s"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:147
#: trove/guestagent/datastore/cassandra/service.py:164
msgid "Dumping YAML to stream"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:176
msgid "Starting cassandra with conf changes..."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:177
#, python-format
msgid "inside the guest - cassandra is running %s..."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:180
#, python-format
msgid "Cannot execute start_db_with_conf_changes because cassandra state == %s!"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:183
#: trove/guestagent/datastore/mysql/service.py:864
#: trove/guestagent/datastore/redis/service.py:246
msgid "Initiating config."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:189
#: trove/guestagent/datastore/couchbase/service.py:214
#: trove/guestagent/datastore/mongodb/service.py:143
#: trove/guestagent/datastore/mysql/service.py:870
#: trove/guestagent/datastore/redis/service.py:252
msgid "Resetting configuration"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:206
#: trove/guestagent/datastore/mongodb/service.py:211
#: trove/guestagent/datastore/mongodb/service.py:225
#, python-format
msgid "Process execution %s"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:209
#: trove/guestagent/datastore/mongodb/service.py:228
#, python-format
msgid "OS Error %s"
msgstr ""

#: trove/guestagent/datastore/couchbase/manager.py:77
msgid "Securing couchbase now."
msgstr ""

#: trove/guestagent/datastore/couchbase/manager.py:79
msgid "\"prepare\" couchbase call has finished."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:57
msgid "Preparing Guest as Couchbase Server"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:59
msgid "Installing Couchbase"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:67
msgid "Couchbase Server change data dir path"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:77
msgid "Couchbase Server initialize cluster"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:85
msgid "Couchbase Server initial setup finished"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:87
#, python-format
msgid "Process execution error %s"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:117
msgid "Enabling Couchbase Server on boot."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:124
msgid "Command to enable Couchbase Server on boot not found."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:128
msgid "Disabling Couchbase Server on boot"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:142
msgid "Stopping Couchbase Server..."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:157
msgid "Could not stop Couchbase Server!"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:159
msgid "Could not stop Couchbase Server"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:162
msgid "Restarting Couchbase Server"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:174
msgid "Starting Couchbase Server..."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:190
msgid "Start up of Couchbase Server failed!"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:203
msgid "Starting Couchbase with configuration changes"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:204
#: trove/guestagent/datastore/mongodb/service.py:133
#, python-format
msgid ""
"Configuration contents:\n"
" %s"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:206
#, python-format
msgid "Cannot start Couchbase with configuration changes. Couchbase state == %s!"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:221
msgid "Doing nothing."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:242
#, python-format
msgid "Process execution %s "
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:42
msgid "Preparing Guest as MongoDB"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:46
msgid "Finished installing MongoDB server"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:49
msgid "Enabling MongoDB on boot"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:56
#: trove/guestagent/datastore/mongodb/service.py:79
msgid "MongoDB service is not discovered."
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:59
msgid "Disabling MongoDB on boot"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:69
msgid "Stopping MongoDB"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:84
#: trove/guestagent/datastore/mongodb/service.py:86
msgid "Could not stop MongoDB"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:89
msgid "Restarting MongoDB"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:98
msgid "Starting MongoDB"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:115
msgid "Start up of MongoDB failed"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:132
msgid "Starting MongoDB with configuration changes"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:135
#, python-format
msgid "Cannot start MongoDB with configuration changes. MongoDB state == %s!"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:163
msgid "Updating MongoDB config"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:165
#, python-format
msgid "Writing %s"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:169
#, python-format
msgid "Moving %(a)s to %(b)s"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:174
msgid "Empty config_contents. Do nothing"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:181
#, python-format
msgid "Config file %s not found"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:198
#, python-format
msgid "Set owner to 'mongodb' for %s "
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:201
#, python-format
msgid "Set group to 'mongodb' for %s "
msgstr ""

#: trove/guestagent/datastore/mysql/manager.py:96
#, python-format
msgid "Restoring database from backup %s"
msgstr ""

#: trove/guestagent/datastore/mysql/manager.py:105
msgid "Restored database successfully"
msgstr ""

#: trove/guestagent/datastore/mysql/manager.py:132
msgid "Securing mysql now."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:355
#, python-format
msgid "Username %(user)s is not valid: %(reason)s"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:387
#, python-format
msgid "Grant access to %s is not allowed"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:586
msgid "Preparing Guest as MySQL Server"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:603
msgid "Generating admin password..."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:616
msgid "Dbaas secure complete."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:620
msgid "Preserving root access from restore"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:664
msgid "Stopping mysql..."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:676
msgid "Could not stop MySQL!"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:724
#, python-format
msgid "Unable to set %(key)s with value %(value)s"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:760
msgid "Wiping ib_logfiles..."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:781
msgid "Writing my.cnf templates."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:803
msgid "Writing new temp overrides.cnf file."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:807
msgid "Moving overrides.cnf into correct location."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:811
msgid "Setting permissions on overrides.cnf"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:816
msgid "Removing overrides configuration file"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:821
msgid "Starting mysql..."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:844
msgid "Start up of MySQL failed!"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:857
msgid "Starting mysql with conf changes..."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:858
#, python-format
msgid "inside the guest - self.status.is_mysql_running(%s)..."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:861
#, python-format
msgid "Cannot execute start_db_with_conf_changes because MySQL state == %s!"
msgstr ""

#: trove/guestagent/datastore/redis/manager.py:92
msgid "Securing redis now."
msgstr ""

#: trove/guestagent/datastore/redis/manager.py:95
msgid "\"prepare\" redis call has finished."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:86
msgid "Password is set running ping with password"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:95
msgid "Password not set running ping without password"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:101
msgid "Redis is RUNNING."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:104
msgid "Process execution error on redis-cli"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:110
#, python-format
msgid "Redis pid: %s"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:112
msgid "Service Status is BLOCKED."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:118
msgid "Service Status is CRASHED."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:121
msgid "Service Status is SHUTDOWN."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:145
msgid "Preparing Guest as Redis Server"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:147
msgid "Installing Redis"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:178
msgid "Enabling Redis on boot."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:185
msgid "Command to enable Redis on boot not found."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:192
msgid "Disabling Redis on boot."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:206
msgid "Stopping redis..."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:215
msgid "Could not stop Redis!"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:242
msgid "Starting redis with conf changes..."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:259
msgid "Starting redis..."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:270
msgid "Start up of redis failed!"
msgstr ""

#: trove/guestagent/strategies/restore/base.py:102
#, python-format
msgid "Restored %s bytes from stream."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:41
msgid "The mysqld daemon is up and running."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:44
#: trove/guestagent/strategies/restore/mysql_impl.py:52
msgid "The mysqld daemon is not running."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:49
msgid "The mysqld daemon is still running."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:69
msgid "Starting mysqld daemon"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:71
msgid "wait_and_close_proc failed"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:79
msgid "Root password reset successfully!"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:80
msgid "Cleaning up the temp mysqld process..."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:121
#, python-format
msgid "Cleaning out restore location: %s"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:129
#: trove/guestagent/strategies/restore/mysql_impl.py:188
#, python-format
msgid "Running innobackupex prepare: %s"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:131
#: trove/guestagent/strategies/restore/mysql_impl.py:190
msgid "Innobackupex prepare finished successfully"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:205
#, python-format
msgid "Restoring parent: %(parent_location)s checksum: %(parent_checksum)s"
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:235
#, python-format
msgid "Writing metadata: %s"
msgstr ""

#: trove/instance/models.py:297
#, python-format
msgid ""
"While shutting down instance (%(instance)s): server had status "
"(%(status)s)."
msgstr ""

#: trove/instance/models.py:567
#, python-format
msgid "Settting task status to NONE on instance %s..."
msgstr ""

#: trove/instance/models.py:751
#, python-format
msgid "Instance %s has no volume."
msgstr ""

#: trove/instance/models.py:755
#, python-format
msgid "The new volume 'size' must be larger than the current volume size of '%s'"
msgstr ""

#: trove/instance/models.py:905
#, python-format
msgid "Server %(server)s for instance %(instance)s wasfound twice!"
msgstr ""

#: trove/instance/models.py:966 trove/instance/models.py:972
#, python-format
msgid "Server status could not be read for instance id(%s)"
msgstr ""

#: trove/instance/models.py:969
#, python-format
msgid "Server api_status(%s)"
msgstr ""

#: trove/instance/service.py:145
#, python-format
msgid "Indexing backups for instance '%s'"
msgstr ""

#: trove/instance/service.py:169
#, python-format
msgid "Deleting a database instance for tenant '%s'"
msgstr ""

#: trove/instance/service.py:180
#, python-format
msgid "Creating a database instance for tenant '%s'"
msgstr ""

#: trove/instance/service.py:243
#, python-format
msgid "Updating instance for tenant id %s"
msgstr ""

#: trove/instance/service.py:244
#, python-format
msgid "req: %s"
msgstr ""

#: trove/instance/service.py:245
#, python-format
msgid "body: %s"
msgstr ""

#: trove/openstack/common/eventlet_backdoor.py:142
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr ""

#: trove/openstack/common/exception.py:104
msgid "Uncaught exception"
msgstr ""

#: trove/openstack/common/excutils.py:64
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: trove/openstack/common/excutils.py:93
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: trove/openstack/common/extensions.py:195
#, python-format
msgid "Extension with alias %s does not exist"
msgstr ""

#: trove/openstack/common/extensions.py:262
#, python-format
msgid "Extended resource: %s"
msgstr ""

#: trove/openstack/common/extensions.py:280
#, python-format
msgid "Extended action: %s"
msgstr ""

#: trove/openstack/common/extensions.py:288
#, python-format
msgid "Extended request: %s"
msgstr ""

#: trove/openstack/common/extensions.py:347
msgid "Initializing extension manager."
msgstr ""

#: trove/openstack/common/extensions.py:397
#, python-format
msgid "Ext name: %s"
msgstr ""

#: trove/openstack/common/extensions.py:398
#, python-format
msgid "Ext alias: %s"
msgstr ""

#: trove/openstack/common/extensions.py:399
#, python-format
msgid "Ext description: %s"
msgstr ""

#: trove/openstack/common/extensions.py:400
#, python-format
msgid "Ext namespace: %s"
msgstr ""

#: trove/openstack/common/extensions.py:401
#, python-format
msgid "Ext updated: %s"
msgstr ""

#: trove/openstack/common/extensions.py:403
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: trove/openstack/common/extensions.py:430
#, python-format
msgid "Loading extension file: %s"
msgstr ""

#: trove/openstack/common/extensions.py:438
#, python-format
msgid "Did not find expected name \"%(ext_name)s\" in %(file)s"
msgstr ""

#: trove/openstack/common/extensions.py:452
#, python-format
msgid "Loaded extension: %s"
msgstr ""

#: trove/openstack/common/lockutils.py:105
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: trove/openstack/common/lockutils.py:170
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: trove/openstack/common/lockutils.py:179
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr ""

#: trove/openstack/common/lockutils.py:189
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: trove/openstack/common/lockutils.py:207
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: trove/openstack/common/lockutils.py:211
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: trove/openstack/common/lockutils.py:249
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: trove/openstack/common/lockutils.py:253
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: trove/openstack/common/log.py:301
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: trove/openstack/common/log.py:402
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: trove/openstack/common/log.py:453
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: trove/openstack/common/log.py:623
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: trove/openstack/common/loopingcall.py:84
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: trove/openstack/common/loopingcall.py:91
msgid "in fixed duration looping call"
msgstr ""

#: trove/openstack/common/loopingcall.py:131
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: trove/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: trove/openstack/common/periodic_task.py:97
#, python-format
msgid "Skipping %(full_task_name)s, %(ticks_to_skip)s ticks left until next run"
msgstr ""

#: trove/openstack/common/periodic_task.py:105
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr ""

#: trove/openstack/common/periodic_task.py:113
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: trove/openstack/common/policy.py:394
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr ""

#: trove/openstack/common/policy.py:404
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: trove/openstack/common/policy.py:679
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr ""

#: trove/openstack/common/processutils.py:122
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: trove/openstack/common/processutils.py:137
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: trove/openstack/common/processutils.py:162
#, python-format
msgid "Result was %s"
msgstr ""

#: trove/openstack/common/processutils.py:174
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: trove/openstack/common/service.py:118 trove/openstack/common/service.py:335
msgid "Full set of CONF:"
msgstr ""

#: trove/openstack/common/service.py:127 trove/openstack/common/service.py:217
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: trove/openstack/common/service.py:139
msgid "Exception during rpc cleanup."
msgstr ""

#: trove/openstack/common/service.py:188
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: trove/openstack/common/service.py:223
msgid "Unhandled exception"
msgstr ""

#: trove/openstack/common/service.py:256
msgid "Forking too fast, sleeping"
msgstr ""

#: trove/openstack/common/service.py:278
#, python-format
msgid "Started child %d"
msgstr ""

#: trove/openstack/common/service.py:288
#, python-format
msgid "Starting %d workers"
msgstr ""

#: trove/openstack/common/service.py:305
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: trove/openstack/common/service.py:309
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: trove/openstack/common/service.py:313
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: trove/openstack/common/service.py:345
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: trove/openstack/common/service.py:363
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: trove/openstack/common/sslutils.py:52
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: trove/openstack/common/sslutils.py:55
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: trove/openstack/common/sslutils.py:58
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: trove/openstack/common/sslutils.py:61
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: trove/openstack/common/sslutils.py:100
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: trove/openstack/common/versionutils.py:69
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: trove/openstack/common/versionutils.py:73
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: trove/openstack/common/wsgi.py:114
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: trove/openstack/common/wsgi.py:375
msgid "Unsupported Content-Type"
msgstr ""

#: trove/openstack/common/wsgi.py:378
msgid "Malformed request body"
msgstr ""

#: trove/openstack/common/wsgi.py:664
msgid "Empty body provided in request"
msgstr ""

#: trove/openstack/common/wsgi.py:670
msgid "Unrecognized Content-Type provided in request"
msgstr ""

#: trove/openstack/common/wsgi.py:674
msgid "No Content-Type provided in request"
msgstr ""

#: trove/openstack/common/wsgi.py:680
msgid "Unable to deserialize body as provided Content-Type"
msgstr ""

#: trove/openstack/common/wsgi.py:730
msgid "cannot understand JSON"
msgstr ""

#: trove/openstack/common/wsgi.py:754
msgid "cannot understand XML"
msgstr ""

#: trove/openstack/common/crypto/utils.py:29
msgid "An unknown error occurred in crypto utils."
msgstr ""

#: trove/openstack/common/crypto/utils.py:36
#, python-format
msgid "Block size of %(given)d is too big, max = %(maximum)d"
msgstr ""

#: trove/openstack/common/crypto/utils.py:45
#, python-format
msgid "Length of %(given)d is too long, max = %(maximum)d"
msgstr ""

#: trove/openstack/common/notifier/api.py:125
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: trove/openstack/common/notifier/api.py:141
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: trove/openstack/common/notifier/api.py:171
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr ""

#: trove/openstack/common/notifier/rabbit_notifier.py:27
msgid "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."
msgstr ""

#: trove/openstack/common/notifier/rpc_notifier.py:45
#: trove/openstack/common/notifier/rpc_notifier2.py:51
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: trove/openstack/common/rpc/__init__.py:105
#, python-format
msgid ""
"A RPC is being made while holding a lock. The locks currently held are "
"%(locks)s. This is probably a bug. Please report it. Include the "
"following: [%(stack)s]."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:75
msgid "Pool creating new connection"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:202
#, python-format
msgid "No calling threads waiting for msg_id : %(msg_id)s, message : %(data)s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:205
#, python-format
msgid "_call_waiters: %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:212
#, python-format
msgid ""
"Number of call waiters is greater than warning threshhold: %d. There "
"could be a MulticallProxyWaiter leak."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:290
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:341
#, python-format
msgid "UNIQUE_ID is %s."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:413
#, python-format
msgid "received %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:421
#, python-format
msgid "no method for message: %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:422
#, python-format
msgid "No method for message: %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:450
#: trove/openstack/common/rpc/impl_zmq.py:280
#, python-format
msgid "Expected exception during message handling (%s)"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:458
#: trove/openstack/common/rpc/impl_zmq.py:286
msgid "Exception during message handling"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:532
#, python-format
msgid "Making synchronous call on %s ..."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:535
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:561
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:570
msgid "Making asynchronous fanout cast..."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:598
#, python-format
msgid "Sending %(event_type)s on %(topic)s"
msgstr ""

#: trove/openstack/common/rpc/common.py:76
msgid "An unknown RPC related exception occurred."
msgstr ""

#: trove/openstack/common/rpc/common.py:88
msgid "Exception in string format operation"
msgstr ""

#: trove/openstack/common/rpc/common.py:106
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: trove/openstack/common/rpc/common.py:123
#, python-format
msgid ""
"Timeout while waiting on RPC response - topic: \"%(topic)s\", RPC method:"
" \"%(method)s\" info: \"%(info)s\""
msgstr ""

#: trove/openstack/common/rpc/common.py:140
#: trove/openstack/common/rpc/common.py:141
#: trove/openstack/common/rpc/common.py:142
msgid "<unknown>"
msgstr ""

#: trove/openstack/common/rpc/common.py:146
#, python-format
msgid "Found duplicate message(%(msg_id)s). Skipping it."
msgstr ""

#: trove/openstack/common/rpc/common.py:150
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: trove/openstack/common/rpc/common.py:154
#, python-format
msgid "Specified RPC version, %(version)s, not supported by this endpoint."
msgstr ""

#: trove/openstack/common/rpc/common.py:159
#, python-format
msgid ""
"Specified RPC envelope version, %(version)s, not supported by this "
"endpoint."
msgstr ""

#: trove/openstack/common/rpc/common.py:164
#, python-format
msgid "Specified RPC version cap, %(version_cap)s, is too low"
msgstr ""

#: trove/openstack/common/rpc/common.py:292
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:157
msgid "Failed to process message ... skipping it."
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:161
msgid "Failed to process message ... will requeue."
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:496
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:518
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:555
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:569
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:623
#: trove/openstack/common/rpc/impl_qpid.py:492
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:641
#: trove/openstack/common/rpc/impl_qpid.py:507
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:645
#: trove/openstack/common/rpc/impl_qpid.py:511
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:684
#: trove/openstack/common/rpc/impl_qpid.py:546
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: trove/openstack/common/rpc/impl_qpid.py:161
msgid "Failed to process message... skipping it."
msgstr ""

#: trove/openstack/common/rpc/impl_qpid.py:434
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""

#: trove/openstack/common/rpc/impl_qpid.py:440
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: trove/openstack/common/rpc/impl_qpid.py:453
msgid "Re-established AMQP queues"
msgstr ""

#: trove/openstack/common/rpc/impl_qpid.py:519
msgid "Error processing message.  Skipping it."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:96
msgid "JSON serialization failed."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:101
#, python-format
msgid "Deserializing: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:136
#, python-format
msgid "Connecting to %(addr)s with %(type)s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:137
#, python-format
msgid "-> Subscribed to %(subscribe)s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:138
#, python-format
msgid "-> bind: %(bind)s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:146
msgid "Could not open socket."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:158
#, python-format
msgid "Subscribing to %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:200
msgid "You cannot recv on this socket."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:205
msgid "You cannot send on this socket."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:267
#, python-format
msgid "Running func with context: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:305
msgid "Sending reply"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:339
msgid "RPC message did not include method."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:371
msgid "Registering reactor"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:383
msgid "In reactor registered"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:388
msgid "Consuming socket"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:438
#, python-format
msgid "Creating proxy for topic: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:444
msgid "Topic contained dangerous characters."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:476
msgid "Topic socket file creation failed."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:482
#, python-format
msgid "Local per-topic backlog buffer full for topic %(topic)s. Dropping message."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:498
#, python-format
msgid "Required IPC directory does not exist at %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:507
#, python-format
msgid "Permission denied to IPC directory at %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:510
msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:544
#, python-format
msgid "CONSUMER RECEIVED DATA: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:563
msgid "ZMQ Envelope version unsupported or unknown."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:591
msgid "Skipping topic registration. Already registered."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:598
#, python-format
msgid "Consumer is a zmq.%s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:650
msgid "Creating payload"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:663
msgid "Creating queue socket for reply waiter"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:676
msgid "Sending cast"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:679
msgid "Cast sent; Waiting reply"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:682
#, python-format
msgid "Received message: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:683
msgid "Unpacking response"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:692
msgid "Unsupported or unknown ZMQ envelope returned."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:699
msgid "RPC Message Invalid."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:722
#, python-format
msgid "%(msg)s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:725
#, python-format
msgid "Sending message(s) to: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:729
msgid "No matchmaker results. Not casting."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:732
msgid "No match from matchmaker."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:814
#, python-format
msgid "rpc_zmq_matchmaker = %(orig)s is deprecated; use %(new)s instead"
msgstr ""

#: trove/openstack/common/rpc/matchmaker.py:47
msgid "Match not found by MatchMaker."
msgstr ""

#: trove/openstack/common/rpc/matchmaker.py:81
msgid "Matchmaker does not implement registration or heartbeat."
msgstr ""

#: trove/openstack/common/rpc/matchmaker.py:217
#, python-format
msgid "Matchmaker unregistered: %(key)s, %(host)s"
msgstr ""

#: trove/openstack/common/rpc/matchmaker.py:229
msgid "Register before starting heartbeat."
msgstr ""

#: trove/openstack/common/rpc/matchmaker_ring.py:77
#: trove/openstack/common/rpc/matchmaker_ring.py:95
#, python-format
msgid "No key defining hosts for topic '%s', see ringfile"
msgstr ""

#: trove/openstack/common/rpc/service.py:49
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: trove/quota/quota.py:290
#, python-format
msgid "Failed to commit reservations %(reservations)s"
msgstr ""

#: trove/quota/quota.py:303
#, python-format
msgid "Failed to roll back reservations %(reservations)s"
msgstr ""

#: trove/taskmanager/models.py:180
#, python-format
msgid "Error creating security group for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:245
#, python-format
msgid "Error creating DNS entry for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:262
msgid "Timeout for service changing to active. No usage create-event sent."
msgstr ""

#: trove/taskmanager/models.py:267
msgid "Error during create-event call."
msgstr ""

#: trove/taskmanager/models.py:282
#, python-format
msgid "Service status: %(status)s"
msgstr ""

#: trove/taskmanager/models.py:285
#, python-format
msgid "Service error description: %(desc)s"
msgstr ""

#: trove/taskmanager/models.py:293
#, python-format
msgid "Trove instance status: %(action)s"
msgstr ""

#: trove/taskmanager/models.py:296
#, python-format
msgid "Trove instance status description: %(text)s"
msgstr ""

#: trove/taskmanager/models.py:317
#, python-format
msgid "Service not active, status: %s"
msgstr ""

#: trove/taskmanager/models.py:323
#, python-format
msgid "Server not active, status: %s"
msgstr ""

#: trove/taskmanager/models.py:360
#, python-format
msgid "Error creating server and volume for instance %s"
msgstr ""

#: trove/taskmanager/models.py:387
msgid "heat template ascii encode issue"
msgstr ""

#: trove/taskmanager/models.py:409
msgid "Timeout during stack status tracing"
msgstr ""

#: trove/taskmanager/models.py:464
#, python-format
msgid "Error creating server for instance %s"
msgstr ""

#: trove/taskmanager/models.py:480
#, python-format
msgid "Error provisioning volume for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:582
msgid "Entering guest_prepare"
msgstr ""

#: trove/taskmanager/models.py:606
#, python-format
msgid "Polling for ip addresses: $%s "
msgstr ""

#: trove/taskmanager/models.py:615
#, python-format
msgid ""
"Instance IP not available, instance (%(instance)s): server had status "
"(%(status)s)."
msgstr ""

#: trove/taskmanager/models.py:626
msgid "Creating dns entry..."
msgstr ""

#: trove/taskmanager/models.py:646
#, python-format
msgid ""
"Error creating security group rules. Invalid port format. FromPort = "
"%(from)s, ToPort = %(to)s"
msgstr ""

#: trove/taskmanager/models.py:707
#, python-format
msgid "Error during delete compute server %s"
msgstr ""

#: trove/taskmanager/models.py:716
#, python-format
msgid "Error during dns entry of instance %(id)s: %(ex)s"
msgstr ""

#: trove/taskmanager/models.py:725
#, python-format
msgid ""
"Server %(server_id)s got into ERROR status during delete of instance "
"%(instance_id)s!"
msgstr ""

#: trove/taskmanager/models.py:736
#, python-format
msgid "Timout during nova server delete of server: %s"
msgstr ""

#: trove/taskmanager/models.py:792
#, python-format
msgid "Failed to reboot instance %(id)s: %(e)s"
msgstr ""

#: trove/taskmanager/models.py:804
#, python-format
msgid "Failure to restart datastore for instance %s."
msgstr ""

#: trove/taskmanager/models.py:834
msgid "Failed to update configuration overrides."
msgstr ""

#: trove/taskmanager/models.py:934
#, python-format
msgid "Deleting files with prefix: %(cont)s/%(prefix)s"
msgstr ""

#: trove/taskmanager/models.py:942
#, python-format
msgid "Deleting file: %(cont)s/%(name)s"
msgstr ""

#: trove/taskmanager/models.py:946
#, python-format
msgid "Deleting file: %(cont)s/%(filename)s"
msgstr ""

#: trove/taskmanager/models.py:965
#, python-format
msgid "Exception deleting from swift. Details: %s"
msgstr ""

#: trove/taskmanager/models.py:988
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Setting service status to failed."
msgstr ""

#: trove/taskmanager/models.py:997
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1005
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by mounting the volume and then "
"restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1014
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by attaching and mounting the volume "
"and then restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1116
#, python-format
msgid "Failed to get volume %(vol_id)s"
msgstr ""

#: trove/taskmanager/models.py:1130
#, python-format
msgid "Timeout trying to extend the volume %(vol_id)s for instance %(id)s"
msgstr ""

#: trove/taskmanager/models.py:1143
#, python-format
msgid ""
"Error encountered trying to verify extend for the volume %(vol_id)s for "
"instance %(id)s"
msgstr ""

#: trove/taskmanager/models.py:1190
#, python-format
msgid ""
"Volume resize failed for instance %(id)s. The instance must be in state "
"%(state)s not %(inst_state)s."
msgstr ""

#: trove/taskmanager/models.py:1311
msgid "Exception during nova action."
msgstr ""

#: trove/taskmanager/models.py:1313
#, python-format
msgid "Reverting action for instance %s"
msgstr ""

#: trove/taskmanager/models.py:1319
msgid "Restarting datastore."
msgstr ""

#: trove/taskmanager/models.py:1322
msgid "Cannot restart datastore because Nova server status is not ACTIVE"
msgstr ""

#: trove/taskmanager/models.py:1325
#, python-format
msgid "Error resizing instance %s."
msgstr ""

#: trove/taskmanager/models.py:1387
msgid "Error sending reset_configuration call."
msgstr ""

#: trove/tests/fakes/nova.py:270
#, python-format
msgid "volume status = %s"
msgstr ""

#: trove/tests/fakes/nova.py:297
#, python-format
msgid "FAKE_SERVERS_DB : %s"
msgstr ""

#: trove/tests/fakes/nova.py:320
#, python-format
msgid "Couldn't find server id %(id)s, collection=%(db)s"
msgstr ""

#: trove/tests/fakes/nova.py:340
#, python-format
msgid "Simulated event ended, deleting server %s."
msgstr ""

#: trove/tests/fakes/nova.py:482
#, python-format
msgid "Couldn't find volume id %(id)s, collection=%(db)s"
msgstr ""

