# Translations template for trove.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the trove project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: trove 2014.2.rc1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-10-10 07:48+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: trove/backup/models.py:107
#, python-format
msgid "Unable to create backup record for instance: %s"
msgstr ""

#: trove/backup/models.py:248
#, python-format
msgid "Backup %s cannot be deleted because it is running."
msgstr ""

#: trove/backup/models.py:292
#, python-format
msgid "Bad location for backup object: %s"
msgstr ""

#: trove/backup/service.py:57
#, python-format
msgid "Creating a backup for tenant %s"
msgstr ""

#: trove/backup/service.py:68
#, python-format
msgid "Deleting backup for tenant %(tenant_id)s ID: %(backup_id)s"
msgstr ""

#: trove/cluster/models.py:121
#, python-format
msgid "Setting task to NONE on cluster %s"
msgstr ""

#: trove/cluster/models.py:193 trove/common/strategies/mongodb/api.py:175
#, python-format
msgid ""
"This action cannot be performed on the cluster while the current cluster "
"task is '%s'."
msgstr ""

#: trove/cluster/service.py:56 trove/cluster/service.py:80
#: trove/cluster/service.py:91 trove/cluster/service.py:105
#: trove/cluster/service.py:116 trove/cluster/service.py:131
#: trove/extensions/account/service.py:35
#: trove/extensions/account/service.py:46
#: trove/extensions/mgmt/clusters/service.py:43
#: trove/extensions/mgmt/clusters/service.py:59
#: trove/extensions/mgmt/clusters/service.py:72
#: trove/extensions/mgmt/host/service.py:34
#: trove/extensions/mgmt/host/service.py:43
#: trove/extensions/mgmt/instances/service.py:50
#: trove/extensions/mgmt/instances/service.py:74
#: trove/extensions/mgmt/instances/service.py:152
#: trove/extensions/mgmt/instances/service.py:171
#: trove/extensions/mgmt/instances/service.py:183
#: trove/extensions/mgmt/quota/service.py:33
#: trove/extensions/mgmt/upgrade/service.py:35
#: trove/extensions/mgmt/volume/service.py:33
#: trove/extensions/mysql/service.py:44 trove/extensions/mysql/service.py:52
#: trove/extensions/mysql/service.py:74 trove/extensions/mysql/service.py:85
#: trove/extensions/mysql/service.py:98 trove/extensions/mysql/service.py:121
#: trove/extensions/mysql/service.py:138 trove/extensions/mysql/service.py:160
#: trove/extensions/mysql/service.py:208 trove/extensions/mysql/service.py:224
#: trove/extensions/mysql/service.py:239 trove/extensions/mysql/service.py:262
#: trove/extensions/mysql/service.py:273 trove/extensions/mysql/service.py:283
#, python-format
msgid ""
"req : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:57 trove/cluster/service.py:81
#: trove/cluster/service.py:106 trove/extensions/mgmt/clusters/service.py:60
#: trove/extensions/mgmt/host/service.py:45
#: trove/extensions/mgmt/instances/service.py:76
#: trove/extensions/mgmt/instances/service.py:154
#: trove/extensions/mgmt/instances/service.py:185
#, python-format
msgid ""
"id : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:59 trove/extensions/mgmt/clusters/service.py:74
#: trove/extensions/mgmt/clusters/service.py:94
#: trove/extensions/mgmt/configuration/service.py:80
#: trove/extensions/mgmt/configuration/service.py:107
#: trove/extensions/mgmt/host/instance/service.py:34
#: trove/extensions/mgmt/host/instance/service.py:52
#: trove/extensions/mgmt/instances/service.py:95
#: trove/extensions/mgmt/instances/service.py:118
#: trove/extensions/mgmt/quota/service.py:43 trove/instance/service.py:72
msgid "Invalid request body."
msgstr ""

#: trove/cluster/service.py:71
#, python-format
msgid "No action '%(action)s' supplied by strategy for manager '%(manager)s'"
msgstr ""

#: trove/cluster/service.py:92
#, python-format
msgid ""
"cluster_id : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:93
#, python-format
msgid ""
"instance_id : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:132 trove/extensions/mysql/service.py:86
#: trove/extensions/mysql/service.py:274
#, python-format
msgid ""
"body : '%s'\n"
"\n"
msgstr ""

#: trove/cmd/manage.py:180
#, python-format
msgid "Possible wrong number of arguments supplied %s"
msgstr ""

#: trove/cmd/manage.py:183
msgid "Command failed, please check log for more info."
msgstr ""

#: trove/common/auth.py:63
#, python-format
msgid "Authorized tenant '%(tenant_id)s' request: %(request)s"
msgstr ""

#: trove/common/auth.py:67
#, python-format
msgid "User with tenant id %s cannot access this resource"
msgstr ""

#: trove/common/debug_utils.py:103
#, python-format
msgid ""
"Can't connect to remote debug server. Continuing to work in standard "
"mode. Error: %s."
msgstr ""

#: trove/common/exception.py:55
#, python-format
msgid "Failed to save %(model_name)s because: %(error)s."
msgstr ""

#: trove/common/exception.py:60
msgid "Invalid RPC Connection Reuse."
msgstr ""

#: trove/common/exception.py:65 trove/common/exception.py:80
#, python-format
msgid "Resource %(uuid)s cannot be found."
msgstr ""

#: trove/common/exception.py:70
#, python-format
msgid "Capability '%(capability)s' cannot be found."
msgstr ""

#: trove/common/exception.py:75
#, python-format
msgid "Capability '%(capability)s' is disabled."
msgstr ""

#: trove/common/exception.py:85
#, python-format
msgid "User %(uuid)s cannot be found on the instance."
msgstr ""

#: trove/common/exception.py:90
#, python-format
msgid "Database %(uuid)s cannot be found on the instance."
msgstr ""

#: trove/common/exception.py:95
#, python-format
msgid "Cannot find compute instance %(server_id)s for instance %(instance_id)s."
msgstr ""

#: trove/common/exception.py:98
#, python-format
msgid "Resource %(instance_id)s can not be retrieved."
msgstr ""

#: trove/common/exception.py:103
#, python-format
msgid "DnsRecord with name= %(name)s not found."
msgstr ""

#: trove/common/exception.py:108
#, python-format
msgid "Datastore '%(datastore)s' cannot be found."
msgstr ""

#: trove/common/exception.py:113
#, python-format
msgid "Datastore version '%(version)s' cannot be found."
msgstr ""

#: trove/common/exception.py:118
msgid "Datastores cannot be found."
msgstr ""

#: trove/common/exception.py:123
#, python-format
msgid "Datastore '%(datastore)s' has no version '%(version)s'."
msgstr ""

#: trove/common/exception.py:128
#, python-format
msgid "Datastore version '%(version)s' is not active."
msgstr ""

#: trove/common/exception.py:133
msgid "Please specify datastore."
msgstr ""

#: trove/common/exception.py:138
#, python-format
msgid "Default version for datastore '%(datastore)s' not found."
msgstr ""

#: trove/common/exception.py:143
#, python-format
msgid "Datastore manager %(datastore_manager)s cannot be found."
msgstr ""

#: trove/common/exception.py:148
#, python-format
msgid ""
"The '%(operation)s' operation is not supported for the '%(datastore)s' "
"datastore."
msgstr ""

#: trove/common/exception.py:154
#, python-format
msgid "Multiple matches found for '%(name)s', use an UUID to be more specific."
msgstr ""

#: trove/common/exception.py:160
msgid "The server rejected the request due to its size or rate."
msgstr ""

#: trove/common/exception.py:166
#, python-format
msgid "Quota exceeded for resources: %(overs)s."
msgstr ""

#: trove/common/exception.py:171
msgid "Instance volume quota exceeded."
msgstr ""

#: trove/common/exception.py:176
#, python-format
msgid "An error occurred communicating with the guest: %(original_message)s."
msgstr ""

#: trove/common/exception.py:182
msgid "Timeout trying to connect to the Guest Agent."
msgstr ""

#: trove/common/exception.py:187
msgid ""
"The server could not comply with the request since it is either malformed"
" or otherwise incorrect."
msgstr ""

#: trove/common/exception.py:193
#, python-format
msgid "Required element/key - %(key)s was not specified."
msgstr ""

#: trove/common/exception.py:198
#, python-format
msgid "A database with the name \"%(name)s\" already exists."
msgstr ""

#: trove/common/exception.py:203
#, python-format
msgid "A user with the name \"%(name)s\" already exists."
msgstr ""

#: trove/common/exception.py:208
msgid ""
"A configuration group cannot be deleted if it is associated with one or "
"more non-terminated instances. Detach the configuration group from all "
"non-terminated instances and please try again."
msgstr ""

#: trove/common/exception.py:216
msgid "Unable to process the contained request."
msgstr ""

#: trove/common/exception.py:221
msgid "No change was requested in the size of the instance."
msgstr ""

#: trove/common/exception.py:226
msgid "Cannot find the volumes attached to compute instance %(server_id)."
msgstr ""

#: trove/common/exception.py:232
msgid "Failed to create a volume in Nova."
msgstr ""

#: trove/common/exception.py:237
msgid "Volume size was not specified."
msgstr ""

#: trove/common/exception.py:242
#, python-format
msgid "Local storage not specified in flavor ID: %(flavor)s."
msgstr ""

#: trove/common/exception.py:247
msgid "Local storage support is not enabled."
msgstr ""

#: trove/common/exception.py:252
msgid "Volume support is not enabled."
msgstr ""

#: trove/common/exception.py:257
#, python-format
msgid "Replication is not supported for the '%(datastore)s' datastore."
msgstr ""

#: trove/common/exception.py:263
#, python-format
msgid ""
"An error occurred communicating with the task manager: "
"%(original_message)s."
msgstr ""

#: trove/common/exception.py:269
#, python-format
msgid "Value could not be converted: %(msg)s."
msgstr ""

#: trove/common/exception.py:274
msgid "Polling request timed out."
msgstr ""

#: trove/common/exception.py:279
msgid "User does not have admin privileges."
msgstr ""

#: trove/common/exception.py:284
#, python-format
msgid "The following values are invalid: %(errors)s."
msgstr ""

#: trove/common/exception.py:289
msgid "Not Found."
msgstr ""

#: trove/common/exception.py:294
msgid "Failed to update instances."
msgstr ""

#: trove/common/exception.py:299
msgid "Config file not found."
msgstr ""

#: trove/common/exception.py:304
msgid "Paste app not found."
msgstr ""

#: trove/common/exception.py:308
msgid "Quota could not be found."
msgstr ""

#: trove/common/exception.py:312
#, python-format
msgid "Quota for tenant %(tenant_id)s could not be found."
msgstr ""

#: trove/common/exception.py:316
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: trove/common/exception.py:320
msgid "Unable to upload Backup to swift."
msgstr ""

#: trove/common/exception.py:324
msgid "Unable to download Backup from swift"
msgstr ""

#: trove/common/exception.py:328
msgid "Unable to create Backup."
msgstr ""

#: trove/common/exception.py:332
msgid "Unable to update Backup table in database."
msgstr ""

#: trove/common/exception.py:337
msgid "Failed to create Security Group."
msgstr ""

#: trove/common/exception.py:342
msgid "Failed to delete Security Group."
msgstr ""

#: trove/common/exception.py:347
msgid "Failed to create Security Group Rule."
msgstr ""

#: trove/common/exception.py:352
msgid "Failed to delete Security Group Rule."
msgstr ""

#: trove/common/exception.py:357
#, python-format
msgid ""
"Error creating security group rules. Malformed port(s). Port must be an "
"integer. FromPort = %(from)s greater than ToPort = %(to)s."
msgstr ""

#: trove/common/exception.py:364
#, python-format
msgid "Unable to create instance because backup %(backup_id)s is not completed."
msgstr ""

#: trove/common/exception.py:369
#, python-format
msgid "Backup file in %(location)s was not found in the object storage."
msgstr ""

#: trove/common/exception.py:374
#, python-format
msgid ""
"The datastore from which the backup was taken, %(datastore1)s, does not "
"match the destination datastore of %(datastore2)s."
msgstr ""

#: trove/common/exception.py:380
#, python-format
msgid "Swift account not accessible for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:384
#, python-format
msgid ""
"The request indicates that user %(user)s should have access to database "
"%(database)s, but database %(database)s is not included in the initial "
"databases list."
msgstr ""

#: trove/common/exception.py:390
msgid ""
"Two or more databases share the same name in the initial databases list. "
"Please correct the names or remove the duplicate entries."
msgstr ""

#: trove/common/exception.py:396
msgid ""
"Two or more users share the same name and host in the initial users list."
" Please correct the names or remove the duplicate entries."
msgstr ""

#: trove/common/exception.py:402
#, python-format
msgid ""
"Current Swift object checksum does not match original checksum for backup"
" %(backup_id)s."
msgstr ""

#: trove/common/exception.py:407
#, python-format
msgid "%(key)s is not a supported configuration parameter."
msgstr ""

#: trove/common/exception.py:411
#, python-format
msgid "No configuration parser found for datastore %(datastore_manager)s."
msgstr ""

#: trove/common/exception.py:416
#, python-format
msgid ""
"Datastore Version on Configuration %(config_datastore_version)s does not "
"match the Datastore Version on the instance "
"%(instance_datastore_version)s."
msgstr ""

#: trove/common/exception.py:423
#, python-format
msgid ""
"%(parameter_name)s parameter can no longer be set as of "
"%(parameter_deleted_at)s."
msgstr ""

#: trove/common/exception.py:428
#, python-format
msgid ""
"%(parameter_name)s parameter already exists for datastore version "
"%(datastore_version)s."
msgstr ""

#: trove/common/exception.py:433
#, python-format
msgid ""
"Instance %(instance_id)s already has a Configuration Group attached: "
"%(configuration_id)s."
msgstr ""

#: trove/common/exception.py:438
#, python-format
msgid ""
"The operation you have requested cannot be executed because the instance "
"status is currently: %(status)s."
msgstr ""

#: trove/common/exception.py:444
#, python-format
msgid ""
"Multiple matches for service_type=%(service_type)s and "
"endpoint_region=%(endpoint_region)s. This generally means that a region "
"is required and you have not supplied one."
msgstr ""

#: trove/common/exception.py:451
#, python-format
msgid ""
"Endpoint not found for service_type=%(service_type)s, "
"endpoint_type=%(endpoint_type)s, endpoint_region=%(endpoint_region)s."
msgstr ""

#: trove/common/exception.py:458
msgid "Empty catalog."
msgstr ""

#: trove/common/exception.py:462
#, python-format
msgid ""
"Instance with replication strategy %(guest_strategy)s cannot replicate "
"from instance with replication strategy %(replication_strategy)s."
msgstr ""

#: trove/common/exception.py:468
#, python-format
msgid ""
"The target instance has only %(slave_volume_size)sG free, but the "
"replication snapshot contains %(dataset_size)sG of data."
msgstr ""

#: trove/common/exception.py:474
msgid "The replica source cannot be deleted without detaching the replicas."
msgstr ""

#: trove/common/exception.py:479
#, python-format
msgid "Cluster '%(cluster)s' cannot be found."
msgstr ""

#: trove/common/exception.py:483
msgid "The flavor for each instance in a cluster must be equal."
msgstr ""

#: trove/common/exception.py:487
msgid "The volume size for each instance in a cluster must be equal."
msgstr ""

#: trove/common/exception.py:492
#, python-format
msgid ""
"The number of instances for your initial cluster must be "
"%(num_instances)s."
msgstr ""

#: trove/common/exception.py:497
msgid "Operation not supported for instances that are part of a cluster."
msgstr ""

#: trove/common/exception.py:502
#, python-format
msgid "Operation not allowed for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:506
#, python-format
msgid "Clusters not supported for %(datastore)s-%(datastore_version)s."
msgstr ""

#: trove/common/extensions.py:203
#, python-format
msgid "Extension with alias %s does not exist"
msgstr ""

#: trove/common/extensions.py:400
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: trove/common/limits.py:87
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: trove/common/limits.py:211
msgid "This request was rate-limited."
msgstr ""

#: trove/common/template.py:134
#, python-format
msgid "Missing heat template for %(s_datastore_manager)s."
msgstr ""

#: trove/common/utils.py:221
msgid "In looping call."
msgstr ""

#: trove/common/utils.py:283
#, python-format
msgid ""
"Command '%(cmd)s' failed. %(description)s Exit code: %(exit_code)s\n"
"stderr: %(stderr)s\n"
"stdout: %(stdout)s"
msgstr ""

#: trove/common/utils.py:292
msgid "Got a timeout but not the one expected."
msgstr ""

#: trove/common/utils.py:295
#, python-format
msgid ""
"Time out after waiting %(time)s seconds when running proc: %(args)s "
"%(kwargs)s."
msgstr ""

#: trove/common/wsgi.py:145
msgid "version not supported"
msgstr ""

#: trove/common/wsgi.py:304
msgid "Unserializable result detected."
msgstr ""

#: trove/common/wsgi.py:526
msgid "Invalid service catalog json."
msgstr ""

#: trove/common/wsgi.py:571
#, python-format
msgid "Caught error: %s."
msgstr ""

#: trove/common/strategies/mongodb/taskmanager.py:133
msgid "Timeout for all instance service statuses to become ready."
msgstr ""

#: trove/common/strategies/mongodb/taskmanager.py:140
#, python-format
msgid "Some instances failed to become ready: %s"
msgstr ""

#: trove/common/strategies/mongodb/taskmanager.py:166
msgid "error adding members"
msgstr ""

#: trove/common/strategies/mongodb/taskmanager.py:180
msgid "error adding shard"
msgstr ""

#: trove/common/strategies/mongodb/taskmanager.py:231
msgid "error adding config servers"
msgstr ""

#: trove/common/strategies/mongodb/taskmanager.py:254
msgid "timeout for building cluster."
msgstr ""

#: trove/common/strategies/mongodb/taskmanager.py:305
msgid "timeout for building shard."
msgstr ""

#: trove/conductor/manager.py:46
#, python-format
msgid "[Instance %s] sent field not present. Cannot compare."
msgstr ""

#: trove/conductor/manager.py:76
#, python-format
msgid "[Instance %s] Rec'd message is older than last seen. Discarding."
msgstr ""

#: trove/conductor/manager.py:109
#, python-format
msgid ""
"[Instance: %(instance)s] Backup IDs mismatch! Expected %(expected)s, "
"found %(found)s"
msgstr ""

#: trove/conductor/manager.py:118
#, python-format
msgid ""
"[Instance: %(instance)s] Backup instance IDs mismatch! Expected "
"%(expected)s, found %(found)s"
msgstr ""

#: trove/configuration/models.py:141
#, python-format
msgid "Configuration group with ID %s could not be found."
msgstr ""

#: trove/configuration/service.py:91
#, python-format
msgid ""
"Creating configuration group on tenant %(tenant_id)s with name: "
"%(cfg_name)s"
msgstr ""

#: trove/configuration/service.py:121
#, python-format
msgid "Deleting configuration group %(cfg_id)s on tenant: %(tenant_id)s"
msgstr ""

#: trove/configuration/service.py:137
#, python-format
msgid "Updating configuration group %(cfg_id)s for tenant id %(tenant_id)s"
msgstr ""

#: trove/configuration/service.py:194
msgid "Validating configuration values"
msgstr ""

#: trove/configuration/service.py:201
#, python-format
msgid "The parameter provided for the configuration %(key)s is not available."
msgstr ""

#: trove/configuration/service.py:211
#, python-format
msgid ""
"The value provided for the configuration parameter %(key)s is not of type"
" %(type)s."
msgstr ""

#: trove/configuration/service.py:220
msgid ""
"Invalid or unsupported min value defined in the configuration-parameters "
"configuration file. Expected integer."
msgstr ""

#: trove/configuration/service.py:226
#, python-format
msgid ""
"The value for the configuration parameter %(key)s is less than the "
"minimum allowed: %(min)s"
msgstr ""

#: trove/configuration/service.py:234
msgid ""
"Invalid or unsupported max value defined in the configuration-parameters "
"configuration file. Expected integer."
msgstr ""

#: trove/configuration/service.py:240
#, python-format
msgid ""
"The value for the configuration parameter %(key)s is greater than the "
"maximum allowed: %(max)s"
msgstr ""

#: trove/configuration/service.py:254
msgid ""
"Invalid or unsupported type defined in the configuration-parameters "
"configuration file."
msgstr ""

#: trove/configuration/service.py:264
#, python-format
msgid "%s is not a supported configuration parameter."
msgstr ""

#: trove/datastore/models.py:209
#, python-format
msgid ""
"Somehow we got a datastore version capability without a parent, that "
"shouldn't happen. %s"
msgstr ""

#: trove/datastore/models.py:252
#, python-format
msgid "Capability Override not found for capability %s"
msgstr ""

#: trove/db/models.py:98
#, python-format
msgid "%(s_name)s Not Found"
msgstr ""

#: trove/db/models.py:103
#, python-format
msgid "Tenant %(s_tenant)s tried to access %(s_name)s, owned by %(s_owner)s."
msgstr ""

#: trove/db/models.py:109
#, python-format
msgid "Tenant %(s_tenant)s cannot access %(s_name)s"
msgstr ""

#: trove/db/sqlalchemy/session.py:79
#, python-format
msgid "Creating SQLAlchemy engine with args: %s"
msgstr ""

#: trove/dns/models.py:68
#, python-format
msgid "%s Not Found"
msgstr ""

#: trove/extensions/account/service.py:36
#, python-format
msgid "Showing account information for '%(account)s' to '%(tenant)s'"
msgstr ""

#: trove/extensions/account/service.py:47
#, python-format
msgid "Showing all accounts with instances for '%s'"
msgstr ""

#: trove/extensions/mgmt/clusters/service.py:84
#: trove/extensions/mgmt/host/instance/service.py:42
#: trove/extensions/mgmt/instances/service.py:108
msgid "Only one action can be specified per request."
msgstr ""

#: trove/extensions/mgmt/clusters/service.py:88
#, python-format
msgid "Invalid cluster action: %s."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:61
msgid "max_size is required for integer data type."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:64
msgid "min_size is required for integer data type."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:70
msgid "max_size must be greater than or equal to min_size."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:76
msgid "Creating configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:103
msgid "Updating configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:128
msgid "Deleting configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:134
#, python-format
msgid "Parameter %s does not exist in the database."
msgstr ""

#: trove/extensions/mgmt/host/service.py:35
#, python-format
msgid "Indexing a host for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/host/service.py:44
#, python-format
msgid "Showing a host for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/host/instance/service.py:46
#, python-format
msgid "Invalid host action: %s"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:51
#, python-format
msgid "Indexing a database instance for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:75
#, python-format
msgid "Showing a database instance for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:112
#, python-format
msgid "Invalid instance action: %s"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:153
#, python-format
msgid "Showing root history for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:172
#, python-format
msgid "Showing hardware info for instance '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:184
#, python-format
msgid "Showing a instance diagnostics for instance '%s'"
msgstr ""

#: trove/extensions/mgmt/quota/service.py:34
#, python-format
msgid "Indexing quota info for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/upgrade/service.py:36
msgid "Sending upgrade notification"
msgstr ""

#: trove/extensions/mgmt/upgrade/service.py:37
#, python-format
msgid "Admin tenant_id: %s"
msgstr ""

#: trove/extensions/mgmt/volume/service.py:34
#, python-format
msgid "Indexing storage info for tenant '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:43
#, python-format
msgid "Getting root enabled for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:51
#, python-format
msgid "Enabling root for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:73
#, python-format
msgid "Listing users for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:84
#, python-format
msgid "Creating users for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:97
#, python-format
msgid "Deleting user for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:120
#, python-format
msgid "Showing a user for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:137
#, python-format
msgid "Updating user attributes for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:159
#, python-format
msgid "Updating user passwords for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:207
#, python-format
msgid "Showing user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:214 trove/extensions/mysql/service.py:229
#: trove/extensions/mysql/service.py:244
#, python-format
msgid "No such user: %(user)s "
msgstr ""

#: trove/extensions/mysql/service.py:223
#, python-format
msgid "Granting user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:238
#, python-format
msgid "Revoking user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:261
#, python-format
msgid "Listing schemas for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:272
#, python-format
msgid "Creating schema for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:282
#, python-format
msgid "Deleting schema for instance '%s'"
msgstr ""

#: trove/extensions/security_group/models.py:76 trove/taskmanager/models.py:567
#, python-format
msgid "Security Group for %s"
msgstr ""

#: trove/extensions/security_group/models.py:130
#, python-format
msgid "Security Group with id: %(id)s already had been deleted"
msgstr ""

#: trove/extensions/security_group/service.py:129
#, python-format
msgid "Create Security Group Rules Required field(s) - %s"
msgstr ""

#: trove/guestagent/api.py:59 trove/guestagent/api.py:62
#: trove/guestagent/api.py:74 trove/guestagent/api.py:77
#: trove/guestagent/api.py:86 trove/guestagent/api.py:89
#, python-format
msgid "Error calling %s"
msgstr ""

#: trove/guestagent/dbaas.py:74
msgid "Error getting volume stats."
msgstr ""

#: trove/guestagent/models.py:86
#, python-format
msgid "Error finding instance %s"
msgstr ""

#: trove/guestagent/pkg.py:117
#, python-format
msgid "Error removing conflict %(package)s"
msgstr ""

#: trove/guestagent/pkg.py:216
#, python-format
msgid "Unexpected output from rpm command. (%(output)s)"
msgstr ""

#: trove/guestagent/pkg.py:239
msgid "Error fixing dpkg"
msgstr ""

#: trove/guestagent/pkg.py:346
msgid "Error updating the apt sources"
msgstr ""

#: trove/guestagent/volume.py:62
msgid "Error getting device status"
msgstr ""

#: trove/guestagent/volume.py:63
#, python-format
msgid "InvalidDevicePath(path=%s)"
msgstr ""

#: trove/guestagent/volume.py:79
msgid "Device path at {0} did not seem to be {1}."
msgstr ""

#: trove/guestagent/volume.py:83
msgid "Volume was not formatted."
msgstr ""

#: trove/guestagent/volume.py:126
msgid "Error resizing file system."
msgstr ""

#: trove/guestagent/volume.py:127
#, python-format
msgid "Error resizing the filesystem: %s"
msgstr ""

#: trove/guestagent/volume.py:140
#, python-format
msgid "Device %(device)s is already mounted in %(mount_point)s. Unmounting now."
msgstr ""

#: trove/guestagent/volume.py:153
msgid "Error retrieving mount points"
msgstr ""

#: trove/guestagent/volume.py:154
#, python-format
msgid "Could not obtain a list of mount points for device: %s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:120
#, python-format
msgid "Error saving backup: %(backup_id)s."
msgstr ""

#: trove/guestagent/backup/backupagent.py:124
#, python-format
msgid "Completed backup %(backup_id)s."
msgstr ""

#: trove/guestagent/backup/backupagent.py:180
#, python-format
msgid "Error restoring backup %(id)s."
msgstr ""

#: trove/guestagent/datastore/service.py:81
#, python-format
msgid "Updating database status to %s."
msgstr ""

#: trove/guestagent/datastore/service.py:133
msgid ""
"DB server is not installed or is in restart mode, so for now we'll skip "
"determining the status of DB on this instance."
msgstr ""

#: trove/guestagent/datastore/service.py:157
msgid "Timeout while waiting for database status to change."
msgstr ""

#: trove/guestagent/datastore/cassandra/manager.py:65
msgid "Setting status of instance to BUILDING."
msgstr ""

#: trove/guestagent/datastore/cassandra/manager.py:100
msgid "Completed setup of Cassandra database instance."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:46
msgid "Preparing Guest as a Cassandra Server"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:67
msgid "Error while initiating storage structure."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:75
msgid "Error starting Cassandra"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:87
msgid "Error killing Cassandra start command."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:89
msgid "Could not start Cassandra"
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:101
#: trove/guestagent/datastore/cassandra/service.py:103
msgid "Could not stop Cassandra."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:108
msgid "Restarting Cassandra server."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:128
msgid "Writing new config."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:183
msgid "Starting Cassandra with configuration changes."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:187
#, python-format
msgid "Cannot execute start_db_with_conf_changes because Cassandra state == %s."
msgstr ""

#: trove/guestagent/datastore/cassandra/service.py:213
msgid "Error getting Cassandra status"
msgstr ""

#: trove/guestagent/datastore/couchbase/manager.py:89
msgid "Completed setup of Couchbase database instance."
msgstr ""

#: trove/guestagent/datastore/couchbase/manager.py:173
#, python-format
msgid "Restoring database from backup %s"
msgstr ""

#: trove/guestagent/datastore/couchbase/manager.py:178
#, python-format
msgid "Error performing restore from backup %s"
msgstr ""

#: trove/guestagent/datastore/couchbase/manager.py:183
msgid "Restored database successfully"
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:60
msgid "Preparing Guest as Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:69
msgid "Couchbase Server change data dir path."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:89
msgid "Couchbase Server initial setup finished."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:91
msgid "Error performing initial Couchbase setup."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:120
msgid "Enabling Couchbase Server on boot."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:127
msgid "Command to enable Couchbase Server on boot not found."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:160
#: trove/guestagent/datastore/couchbase/service.py:162
msgid "Could not stop Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:165
msgid "Restarting Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:177
msgid "Starting Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:193
msgid "Start up of Couchbase Server failed."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:197
msgid "Error killing Couchbase start command."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:205
msgid "Starting Couchbase with configuration changes."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:206
#, python-format
msgid ""
"Configuration contents:\n"
" %s."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:208
#, python-format
msgid "Cannot start Couchbase with configuration changes. Couchbase state == %s."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:244
msgid "Error getting Couchbase status."
msgstr ""

#: trove/guestagent/datastore/couchbase/service.py:294
#, python-format
msgid "An error occurred in saving password (%(errno)s). %(strerror)s."
msgstr ""

#: trove/guestagent/datastore/mongodb/manager.py:99
msgid "\"prepare\" call has finished."
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:46
msgid "Preparing Guest as MongoDB"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:50
msgid "Finished installing MongoDB server"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:61
msgid "Enabling MongoDB on boot"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:67
#: trove/guestagent/datastore/mongodb/service.py:89
msgid "MongoDB service is not discovered."
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:70
msgid "Disabling MongoDB on boot"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:79
msgid "Stopping MongoDB"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:94
#: trove/guestagent/datastore/mongodb/service.py:96
msgid "Could not stop MongoDB"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:99
msgid "Restarting MongoDB"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:108
msgid "Starting MongoDB"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:124
msgid "Start up of MongoDB failed"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:141
msgid "Starting MongoDB with configuration changes"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:142
#, python-format
msgid ""
"Configuration contents:\n"
" %s"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:144
#, python-format
msgid "Cannot start MongoDB with configuration changes. MongoDB state == %s!"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:152
#: trove/guestagent/datastore/redis/service.py:252
msgid "Resetting configuration"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:171
msgid "Updating MongoDB config"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:173
#: trove/guestagent/datastore/mongodb/service.py:241
#, python-format
msgid "Writing %s"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:178
#: trove/guestagent/datastore/mongodb/service.py:245
#, python-format
msgid "Moving %(a)s to %(b)s"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:189
msgid "Empty config_contents. Do nothing"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:196
#, python-format
msgid "Config file %s not found"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:218
#: trove/guestagent/datastore/mongodb/service.py:374
#, python-format
msgid "Process execution %s"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:235
msgid "Rewriting configuration"
msgstr ""

#: trove/guestagent/datastore/mongodb/service.py:377
#, python-format
msgid "OS Error %s"
msgstr ""

#: trove/guestagent/datastore/mysql/manager.py:102
#, python-format
msgid "Restoring database from backup %s."
msgstr ""

#: trove/guestagent/datastore/mysql/manager.py:106
#, python-format
msgid "Error performing restore from backup %s."
msgstr ""

#: trove/guestagent/datastore/mysql/manager.py:110
msgid "Restored database successfully."
msgstr ""

#: trove/guestagent/datastore/mysql/manager.py:159
msgid "Completed setup of MySQL database instance."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:85
msgid "/root/.mysql_secret does not exist."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:95
msgid "Cannot change mysql password."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:168
msgid "MySQL Service Status is RUNNING."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:171
msgid "Failed to get database status."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:178
#, python-format
msgid "MySQL Service Status %(pid)s is BLOCKED."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:182
msgid "Process execution failed."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:187
msgid "MySQL Service Status is CRASHED."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:190
msgid "MySQL Service Status is SHUTDOWN."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:365
msgid "Error Getting user information"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:366
#, python-format
msgid "Username %(user)s is not valid: %(reason)s"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:398
msgid "Error granting access"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:399
#, python-format
msgid "Grant access to %s is not allowed"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:598
msgid "Preparing Guest as MySQL Server."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:607
msgid "Finished installing MySQL server."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:614
msgid "Generating admin password."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:631
msgid "Preserving root access from restore."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:664
msgid "Error enabling MySQL start on boot."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:674
msgid "Error disabling MySQL start on boot."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:678
msgid "Stopping MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:686
msgid "Error stopping MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:691
msgid "Could not stop MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:739
#, python-format
msgid "Unable to set %(key)s with value %(value)s."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:761
msgid "Wiping ib_logfiles."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:781
msgid "Writing my.cnf templates."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:809
msgid "Writing new temp overrides.cnf file."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:813
msgid "Moving overrides.cnf into correct location."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:817
msgid "Setting permissions on overrides.cnf."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:822
msgid "Removing overrides configuration file."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:827
msgid "Writing replication.cnf file."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:840
msgid "Removing replication configuration file."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:845
msgid "Granting Replication Slave privilege."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:856
msgid "Revoking Replication Slave privilege."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:883
#, python-format
msgid "Configuring replication from %s."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:905
msgid "Starting slave replication."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:912
msgid "Stopping slave replication."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:935
#, python-format
msgid "Replication is now %s."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:938
#, python-format
msgid "Replication is not %(status)s after %(max)d seconds."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:942
msgid "Starting MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:965
msgid "Start up of MySQL failed."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:971
msgid "Error killing stalled MySQL start command."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:977
msgid "Starting MySQL with conf changes."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:981
#, python-format
msgid "Cannot execute start_db_with_conf_changes because MySQL state == %s."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:984
#: trove/guestagent/datastore/mysql/service.py:990
msgid "Resetting configuration."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/access.py:37
msgid "{guest_id}: Granting user ({user}) access to database ({database})."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/access.py:60
msgid "{guest_id}: Revoking user ({user}) access to database({database})."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/config.py:112
msgid "{guest_id}: Going into restart mode for config file changes."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/config.py:122
msgid "{guest_id}: Ending restart mode for config file changes."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/database.py:44
msgid "{guest_id}: Creating database {name}."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/database.py:66
msgid "{guest_id}: Dropping database {name}."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/install.py:51
msgid "{guest_id}: Installing ({packages})."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/process.py:36
msgid "{guest_id}: Starting database engine with command ({command})."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/process.py:51
msgid "{guest_id}: Stopping database engine with command ({command})."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/process.py:65
msgid "{guest_id}: Restarting database engine."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/users.py:51
msgid "{guest_id}: Creating user {name} with password {password}."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/users.py:134
msgid "{guest_id}: Dropping user {name}."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/users.py:188
msgid "{guest_id}: Changing password for {user} to {password}."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/users.py:227
msgid "{guest_id}: Changing username for {old} to {new}."
msgstr ""

#: trove/guestagent/datastore/postgresql/service/users.py:242
msgid "{guest_id}: Regranting permissions from {old} to {new}."
msgstr ""

#: trove/guestagent/datastore/redis/manager.py:93
msgid "Securing redis now."
msgstr ""

#: trove/guestagent/datastore/redis/manager.py:96
msgid "\"prepare\" redis call has finished."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:86
msgid "Password is set running ping with password"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:95
msgid "Password not set running ping without password"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:101
msgid "Redis is RUNNING."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:104
msgid "Process execution error on redis-cli"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:110
#, python-format
msgid "Redis pid: %s"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:112
msgid "Service Status is BLOCKED."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:118
msgid "Service Status is CRASHED."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:121
msgid "Service Status is SHUTDOWN."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:145
msgid "Preparing Guest as Redis Server"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:147
msgid "Installing Redis"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:149
msgid "Dbaas install_if_needed complete"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:178
msgid "Enabling Redis on boot."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:185
msgid "Command to enable Redis on boot not found."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:192
msgid "Disabling Redis on boot."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:206
msgid "Stopping redis..."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:215
msgid "Could not stop Redis!"
msgstr ""

#: trove/guestagent/datastore/redis/service.py:242
msgid "Starting redis with conf changes..."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:246
msgid "Initiating config."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:259
msgid "Starting redis..."
msgstr ""

#: trove/guestagent/datastore/redis/service.py:270
msgid "Start up of redis failed!"
msgstr ""

#: trove/guestagent/strategies/backup/couchbase_impl.py:88
msgid "All buckets are memcached.  Skipping backup."
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:66
msgid "Innobackupex log file empty."
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:70
msgid "Innobackupex did not complete successfully."
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:84
#, python-format
msgid "Metadata for backup: %s."
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:61
msgid "Unable to determine binlog position (from file %(binlog_file))."
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:93
msgid "Replication user retry count exceeded"
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:154
#, python-format
msgid "Setting read permissions on %s"
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:156
#, python-format
msgid "Reading log position from %s"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:69
msgid "Starting MySQL"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:71
msgid "Got a timeout launching mysqld_safe"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:79
msgid "Root password reset successfully."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:121
#, python-format
msgid "Cleaning out restore location: %s."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:132
#: trove/guestagent/strategies/restore/mysql_impl.py:191
msgid "Innobackupex prepare finished successfully."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:206
#, python-format
msgid "Restoring parent: %(parent_location)s checksum: %(parent_checksum)s."
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:131
#, python-format
msgid ""
"Error saving data segment to swift. ETAG: %(tag)s Segment MD5: "
"%(checksum)s."
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:162
#, python-format
msgid "Error saving data to swift. Manifest ETAG: %(tag)s Swift MD5: %(checksum)s"
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:179
#, python-format
msgid ""
"Original checksum: %(original)s does not match the current checksum: "
"%(current)s"
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:236
#, python-format
msgid "Writing metadata: %s"
msgstr ""

#: trove/instance/models.py:74
#, python-format
msgid "Could not find nova server_id(%s)."
msgstr ""

#: trove/instance/models.py:309
#, python-format
msgid ""
"While shutting down instance (%(instance)s): server had status "
"(%(status)s)."
msgstr ""

#: trove/instance/models.py:446
#, python-format
msgid "Could not load instance %s."
msgstr ""

#: trove/instance/models.py:466
#, python-format
msgid "Could not load compute instance %s."
msgstr ""

#: trove/instance/models.py:557
msgid "Detach replicas before deleting replica source."
msgstr ""

#: trove/instance/models.py:624
#, python-format
msgid "Resetting task status to NONE on instance %s."
msgstr ""

#: trove/instance/models.py:790
#, python-format
msgid "Resizing instance %(instance_id)s flavor to %(flavor_id)s."
msgstr ""

#: trove/instance/models.py:830
#, python-format
msgid "Resizing volume of instance %s."
msgstr ""

#: trove/instance/models.py:835
#, python-format
msgid "The new volume 'size' must be larger than the current volume size of '%s'."
msgstr ""

#: trove/instance/models.py:843
#, python-format
msgid "Instance %s has no volume."
msgstr ""

#: trove/instance/models.py:853 trove/taskmanager/models.py:965
#, python-format
msgid "Rebooting instance %s."
msgstr ""

#: trove/instance/models.py:861
#, python-format
msgid "Restarting datastore on instance %s."
msgstr ""

#: trove/instance/models.py:875
#, python-format
msgid "Detaching instance %s from its replication source."
msgstr ""

#: trove/instance/models.py:878
#, python-format
msgid "Instance %s is not a replica."
msgstr ""

#: trove/instance/models.py:884
#, python-format
msgid "Migrating instance id = %(instance_id)s to host = %(host)s."
msgstr ""

#: trove/instance/models.py:908
#, python-format
msgid ""
"Instance %(instance_id)s is not currently available for an action to be "
"performed (status was %(action_status)s)."
msgstr ""

#: trove/instance/models.py:1001
#, python-format
msgid "Server %(server)s for instance %(instance)s was found twice!"
msgstr ""

#: trove/instance/models.py:1080 trove/instance/models.py:1086
#, python-format
msgid "Server status could not be read for instance id(%s)."
msgstr ""

#: trove/instance/service.py:86
#, python-format
msgid ""
"Performing %(action_name)s action against instance %(instance_id)s for "
"tenant '%(tenant_id)s'"
msgstr ""

#: trove/instance/service.py:133
#, python-format
msgid "Listing database instances for tenant '%s'"
msgstr ""

#: trove/instance/service.py:146
#, python-format
msgid "Listing backups for instance '%s'"
msgstr ""

#: trove/instance/service.py:158
#, python-format
msgid "Showing database instance '%(instance_id)s' for tenant '%(tenant_id)s'"
msgstr ""

#: trove/instance/service.py:171
#, python-format
msgid "Deleting database instance '%(instance_id)s' for tenant '%(tenant_id)s'"
msgstr ""

#: trove/instance/service.py:184
#, python-format
msgid "Creating a database instance for tenant '%s'"
msgstr ""

#: trove/instance/service.py:244
#, python-format
msgid "Updating database instance '%(instance_id)s' for tenant '%(tenant_id)s'"
msgstr ""

#: trove/instance/service.py:270
#, python-format
msgid "Editing instance for tenant id %s."
msgstr ""

#: trove/instance/service.py:287
#, python-format
msgid "Getting default configuration for instance %s"
msgstr ""

#: trove/openstack/common/eventlet_backdoor.py:142
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr ""

#: trove/openstack/common/exception.py:104
msgid "Uncaught exception"
msgstr ""

#: trove/openstack/common/excutils.py:64
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: trove/openstack/common/excutils.py:93
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: trove/openstack/common/gettextutils.py:301
msgid "Message objects do not support addition."
msgstr ""

#: trove/openstack/common/gettextutils.py:311
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: trove/openstack/common/lockutils.py:105
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: trove/openstack/common/lockutils.py:170
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: trove/openstack/common/lockutils.py:179
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr ""

#: trove/openstack/common/lockutils.py:189
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: trove/openstack/common/lockutils.py:207
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: trove/openstack/common/lockutils.py:211
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: trove/openstack/common/lockutils.py:249
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: trove/openstack/common/lockutils.py:253
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: trove/openstack/common/log.py:287
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: trove/openstack/common/log.py:396
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: trove/openstack/common/log.py:457
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: trove/openstack/common/log.py:700
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: trove/openstack/common/loopingcall.py:84
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: trove/openstack/common/loopingcall.py:91
msgid "in fixed duration looping call"
msgstr ""

#: trove/openstack/common/loopingcall.py:131
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: trove/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: trove/openstack/common/periodic_task.py:97
#, python-format
msgid "Skipping %(full_task_name)s, %(ticks_to_skip)s ticks left until next run"
msgstr ""

#: trove/openstack/common/periodic_task.py:105
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr ""

#: trove/openstack/common/periodic_task.py:113
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: trove/openstack/common/policy.py:394
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr ""

#: trove/openstack/common/policy.py:404
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: trove/openstack/common/policy.py:679
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr ""

#: trove/openstack/common/processutils.py:59
msgid "Unexpected error while running command."
msgstr ""

#: trove/openstack/common/processutils.py:62
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: trove/openstack/common/processutils.py:143
#, python-format
msgid "Got unknown keyword args: %r"
msgstr ""

#: trove/openstack/common/processutils.py:148
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: trove/openstack/common/processutils.py:158
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: trove/openstack/common/processutils.py:206
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: trove/openstack/common/processutils.py:248
msgid "Environment not supported over SSH"
msgstr ""

#: trove/openstack/common/processutils.py:252
msgid "process_input not supported over SSH"
msgstr ""

#: trove/openstack/common/sslutils.py:52
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: trove/openstack/common/sslutils.py:55
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: trove/openstack/common/sslutils.py:58
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: trove/openstack/common/sslutils.py:61
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: trove/openstack/common/sslutils.py:100
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: trove/openstack/common/strutils.py:125
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: trove/openstack/common/strutils.py:230
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: trove/openstack/common/strutils.py:239
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: trove/openstack/common/versionutils.py:69
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: trove/openstack/common/versionutils.py:73
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: trove/openstack/common/wsgi.py:114
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: trove/openstack/common/wsgi.py:375
msgid "Unsupported Content-Type"
msgstr ""

#: trove/openstack/common/wsgi.py:378
msgid "Malformed request body"
msgstr ""

#: trove/openstack/common/wsgi.py:664
msgid "Empty body provided in request"
msgstr ""

#: trove/openstack/common/wsgi.py:670
msgid "Unrecognized Content-Type provided in request"
msgstr ""

#: trove/openstack/common/wsgi.py:674
msgid "No Content-Type provided in request"
msgstr ""

#: trove/openstack/common/wsgi.py:680
msgid "Unable to deserialize body as provided Content-Type"
msgstr ""

#: trove/openstack/common/wsgi.py:730
msgid "cannot understand JSON"
msgstr ""

#: trove/openstack/common/wsgi.py:754
msgid "cannot understand XML"
msgstr ""

#: trove/openstack/common/crypto/utils.py:29
msgid "An unknown error occurred in crypto utils."
msgstr ""

#: trove/openstack/common/crypto/utils.py:36
#, python-format
msgid "Block size of %(given)d is too big, max = %(maximum)d"
msgstr ""

#: trove/openstack/common/crypto/utils.py:45
#, python-format
msgid "Length of %(given)d is too long, max = %(maximum)d"
msgstr ""

#: trove/openstack/common/notifier/api.py:125
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: trove/openstack/common/notifier/api.py:141
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: trove/openstack/common/notifier/api.py:171
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr ""

#: trove/openstack/common/notifier/rabbit_notifier.py:27
msgid "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."
msgstr ""

#: trove/openstack/common/notifier/rpc_notifier.py:45
#: trove/openstack/common/notifier/rpc_notifier2.py:51
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: trove/openstack/common/rpc/__init__.py:105
#, python-format
msgid ""
"A RPC is being made while holding a lock. The locks currently held are "
"%(locks)s. This is probably a bug. Please report it. Include the "
"following: [%(stack)s]."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:75
msgid "Pool creating new connection"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:202
#, python-format
msgid "No calling threads waiting for msg_id : %(msg_id)s, message : %(data)s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:205
#, python-format
msgid "_call_waiters: %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:212
#, python-format
msgid ""
"Number of call waiters is greater than warning threshhold: %d. There "
"could be a MulticallProxyWaiter leak."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:290
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:341
#, python-format
msgid "UNIQUE_ID is %s."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:413
#, python-format
msgid "received %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:421
#, python-format
msgid "no method for message: %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:422
#, python-format
msgid "No method for message: %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:450
#: trove/openstack/common/rpc/impl_zmq.py:280
#, python-format
msgid "Expected exception during message handling (%s)"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:458
#: trove/openstack/common/rpc/impl_zmq.py:286
msgid "Exception during message handling"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:532
#, python-format
msgid "Making synchronous call on %s ..."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:535
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: trove/openstack/common/rpc/amqp.py:561
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:570
msgid "Making asynchronous fanout cast..."
msgstr ""

#: trove/openstack/common/rpc/amqp.py:598
#, python-format
msgid "Sending %(event_type)s on %(topic)s"
msgstr ""

#: trove/openstack/common/rpc/common.py:76
msgid "An unknown RPC related exception occurred."
msgstr ""

#: trove/openstack/common/rpc/common.py:88
msgid "Exception in string format operation"
msgstr ""

#: trove/openstack/common/rpc/common.py:106
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: trove/openstack/common/rpc/common.py:123
#, python-format
msgid ""
"Timeout while waiting on RPC response - topic: \"%(topic)s\", RPC method:"
" \"%(method)s\" info: \"%(info)s\""
msgstr ""

#: trove/openstack/common/rpc/common.py:140
#: trove/openstack/common/rpc/common.py:141
#: trove/openstack/common/rpc/common.py:142
msgid "<unknown>"
msgstr ""

#: trove/openstack/common/rpc/common.py:146
#, python-format
msgid "Found duplicate message(%(msg_id)s). Skipping it."
msgstr ""

#: trove/openstack/common/rpc/common.py:150
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: trove/openstack/common/rpc/common.py:154
#, python-format
msgid "Specified RPC version, %(version)s, not supported by this endpoint."
msgstr ""

#: trove/openstack/common/rpc/common.py:159
#, python-format
msgid ""
"Specified RPC envelope version, %(version)s, not supported by this "
"endpoint."
msgstr ""

#: trove/openstack/common/rpc/common.py:164
#, python-format
msgid "Specified RPC version cap, %(version_cap)s, is too low"
msgstr ""

#: trove/openstack/common/rpc/common.py:292
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:157
msgid "Failed to process message ... skipping it."
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:161
msgid "Failed to process message ... will requeue."
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:496
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:518
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:555
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:569
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:623
#: trove/openstack/common/rpc/impl_qpid.py:493
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:641
#: trove/openstack/common/rpc/impl_qpid.py:508
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:645
#: trove/openstack/common/rpc/impl_qpid.py:512
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_kombu.py:684
#: trove/openstack/common/rpc/impl_qpid.py:547
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: trove/openstack/common/rpc/impl_qpid.py:161
msgid "Failed to process message... skipping it."
msgstr ""

#: trove/openstack/common/rpc/impl_qpid.py:435
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""

#: trove/openstack/common/rpc/impl_qpid.py:441
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: trove/openstack/common/rpc/impl_qpid.py:454
msgid "Re-established AMQP queues"
msgstr ""

#: trove/openstack/common/rpc/impl_qpid.py:520
msgid "Error processing message.  Skipping it."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:96
msgid "JSON serialization failed."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:101
#, python-format
msgid "Deserializing: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:136
#, python-format
msgid "Connecting to %(addr)s with %(type)s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:137
#, python-format
msgid "-> Subscribed to %(subscribe)s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:138
#, python-format
msgid "-> bind: %(bind)s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:146
msgid "Could not open socket."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:158
#, python-format
msgid "Subscribing to %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:200
msgid "You cannot recv on this socket."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:205
msgid "You cannot send on this socket."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:267
#, python-format
msgid "Running func with context: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:305
msgid "Sending reply"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:339
msgid "RPC message did not include method."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:371
msgid "Registering reactor"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:383
msgid "In reactor registered"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:388
msgid "Consuming socket"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:438
#, python-format
msgid "Creating proxy for topic: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:444
msgid "Topic contained dangerous characters."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:476
msgid "Topic socket file creation failed."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:482
#, python-format
msgid "Local per-topic backlog buffer full for topic %(topic)s. Dropping message."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:498
#, python-format
msgid "Required IPC directory does not exist at %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:507
#, python-format
msgid "Permission denied to IPC directory at %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:510
msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:544
#, python-format
msgid "CONSUMER RECEIVED DATA: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:563
msgid "ZMQ Envelope version unsupported or unknown."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:591
msgid "Skipping topic registration. Already registered."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:598
#, python-format
msgid "Consumer is a zmq.%s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:650
msgid "Creating payload"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:663
msgid "Creating queue socket for reply waiter"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:676
msgid "Sending cast"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:679
msgid "Cast sent; Waiting reply"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:682
#, python-format
msgid "Received message: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:683
msgid "Unpacking response"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:692
msgid "Unsupported or unknown ZMQ envelope returned."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:699
msgid "RPC Message Invalid."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:722
#, python-format
msgid "%(msg)s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:725
#, python-format
msgid "Sending message(s) to: %s"
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:729
msgid "No matchmaker results. Not casting."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:732
msgid "No match from matchmaker."
msgstr ""

#: trove/openstack/common/rpc/impl_zmq.py:814
#, python-format
msgid "rpc_zmq_matchmaker = %(orig)s is deprecated; use %(new)s instead"
msgstr ""

#: trove/openstack/common/rpc/matchmaker.py:47
msgid "Match not found by MatchMaker."
msgstr ""

#: trove/openstack/common/rpc/matchmaker.py:81
msgid "Matchmaker does not implement registration or heartbeat."
msgstr ""

#: trove/openstack/common/rpc/matchmaker.py:217
#, python-format
msgid "Matchmaker unregistered: %(key)s, %(host)s"
msgstr ""

#: trove/openstack/common/rpc/matchmaker.py:229
msgid "Register before starting heartbeat."
msgstr ""

#: trove/openstack/common/rpc/matchmaker_ring.py:77
#: trove/openstack/common/rpc/matchmaker_ring.py:95
#, python-format
msgid "No key defining hosts for topic '%s', see ringfile"
msgstr ""

#: trove/openstack/common/rpc/service.py:49
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: trove/quota/quota.py:312
#, python-format
msgid "Failed to commit reservations %(reservations)s"
msgstr ""

#: trove/quota/quota.py:325
#, python-format
msgid "Failed to roll back reservations %(reservations)s"
msgstr ""

#: trove/taskmanager/models.py:203
msgid "timeout for instances to be marked as deleted."
msgstr ""

#: trove/taskmanager/models.py:221
#, python-format
msgid "Creating instance %s."
msgstr ""

#: trove/taskmanager/models.py:233
#, python-format
msgid "Error creating security group for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:301
#, python-format
msgid "Error creating DNS entry for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:317
#, python-format
msgid "Created instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:320
#, python-format
msgid ""
"Failed to create instance %s. Timeout waiting for instance to become "
"active. No usage create-event was sent."
msgstr ""

#: trove/taskmanager/models.py:325
#, python-format
msgid "Failed to send usage create-event for instance %s."
msgstr ""

#: trove/taskmanager/models.py:335
#, python-format
msgid "Error attaching instance %s as replica."
msgstr ""

#: trove/taskmanager/models.py:356
#, python-format
msgid "Unable to create replication snapshot record for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:372
#, python-format
msgid ""
"Error creating replication snapshot from instance %(source)s for new "
"replica %(replica)s."
msgstr ""

#: trove/taskmanager/models.py:394
#, python-format
msgid "Service status: %(status)s"
msgstr ""

#: trove/taskmanager/models.py:397
#, python-format
msgid "Service error description: %(desc)s"
msgstr ""

#: trove/taskmanager/models.py:405
#, python-format
msgid "Trove instance status: %(action)s"
msgstr ""

#: trove/taskmanager/models.py:408
#, python-format
msgid "Trove instance status description: %(text)s"
msgstr ""

#: trove/taskmanager/models.py:430
#, python-format
msgid "Service not active, status: %s"
msgstr ""

#: trove/taskmanager/models.py:436
#, python-format
msgid "Server not active, status: %s"
msgstr ""

#: trove/taskmanager/models.py:474
#, python-format
msgid "Error creating server and volume for instance %s"
msgstr ""

#: trove/taskmanager/models.py:579
#, python-format
msgid "Error occurred during Heat stack creation for instance %s."
msgstr ""

#: trove/taskmanager/models.py:610
#, python-format
msgid "Failed to create server for instance %s"
msgstr ""

#: trove/taskmanager/models.py:628
#, python-format
msgid "Failed to create volume for instance %s"
msgstr ""

#: trove/taskmanager/models.py:732
msgid "Entering guest_prepare"
msgstr ""

#: trove/taskmanager/models.py:765
#, python-format
msgid ""
"Failed to create DNS entry for instance %(instance)s. Server status was "
"%(status)s)."
msgstr ""

#: trove/taskmanager/models.py:776
msgid "Creating dns entry..."
msgstr ""

#: trove/taskmanager/models.py:797
#, python-format
msgid ""
"Failed to create security group rules for instance %(instance_id)s: "
"Invalid port format - FromPort = %(from)s, ToPort = %(to)s"
msgstr ""

#: trove/taskmanager/models.py:859
#, python-format
msgid "Error during delete compute server %s"
msgstr ""

#: trove/taskmanager/models.py:868
#, python-format
msgid "Error during dns entry of instance %(id)s: %(ex)s"
msgstr ""

#: trove/taskmanager/models.py:877
#, python-format
msgid ""
"Server %(server_id)s entered ERROR status when deleting instance "
"%(instance_id)s!"
msgstr ""

#: trove/taskmanager/models.py:888
#, python-format
msgid ""
"Failed to delete instance %(instance_id)s: Timeout deleting compute "
"server %(server_id)s"
msgstr ""

#: trove/taskmanager/models.py:904
#, python-format
msgid ""
"Resizing volume for instance %(instance_id)s from %(old_size)s GB to "
"%(new_size)s GB."
msgstr ""

#: trove/taskmanager/models.py:910
#, python-format
msgid "Resized volume for instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:913
#, python-format
msgid ""
"Resizing instance %(instance_id)s from flavor %(old_flavor)s to "
"%(new_flavor)s."
msgstr ""

#: trove/taskmanager/models.py:919
#, python-format
msgid "Resized instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:922
#, python-format
msgid "Initiating migration to host %s."
msgstr ""

#: trove/taskmanager/models.py:927
#, python-format
msgid "Initiating backup for instance %s."
msgstr ""

#: trove/taskmanager/models.py:941
#, python-format
msgid "Failed to get replication snapshot from %s"
msgstr ""

#: trove/taskmanager/models.py:955
#, python-format
msgid "Failed to detach replica %s."
msgstr ""

#: trove/taskmanager/models.py:983
#, python-format
msgid "Rebooted instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:985
#, python-format
msgid "Failed to reboot instance %(id)s: %(e)s"
msgstr ""

#: trove/taskmanager/models.py:992
#, python-format
msgid "Initiating datastore restart on instance %s."
msgstr ""

#: trove/taskmanager/models.py:996
#, python-format
msgid "Failed to initiate datastore restart on instance %s."
msgstr ""

#: trove/taskmanager/models.py:1002
#, python-format
msgid "Initiating datastore configurations update on instance %s."
msgstr ""

#: trove/taskmanager/models.py:1025
#, python-format
msgid "Failed to initiate datastore configurations update on instance %s."
msgstr ""

#: trove/taskmanager/models.py:1029
#, python-format
msgid ""
"Initiating configuration group %(config_id)s removal from instance "
"%(instance_id)s."
msgstr ""

#: trove/taskmanager/models.py:1145
#, python-format
msgid "Deleting backup %s."
msgstr ""

#: trove/taskmanager/models.py:1158
#, python-format
msgid "Error occurred when deleting from swift. Details: %s"
msgstr ""

#: trove/taskmanager/models.py:1166
#, python-format
msgid "Deleted backup %s successfully."
msgstr ""

#: trove/taskmanager/models.py:1186
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Setting service status to failed."
msgstr ""

#: trove/taskmanager/models.py:1195
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1203
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by mounting the volume and then "
"restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1212
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by attaching and mounting the volume "
"and then restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1318
#, python-format
msgid "Failed to get volume %(vol_id)s"
msgstr ""

#: trove/taskmanager/models.py:1332
#, python-format
msgid "Timeout trying to extend the volume %(vol_id)s for instance %(id)s"
msgstr ""

#: trove/taskmanager/models.py:1345
#, python-format
msgid ""
"Error encountered trying to verify extend for the volume %(vol_id)s for "
"instance %(id)s"
msgstr ""

#: trove/taskmanager/models.py:1392
#, python-format
msgid ""
"Failed to resize instance %(id)s volume for server %(server_id)s. The "
"instance must be in state %(state)s not %(inst_state)s."
msgstr ""

#: trove/taskmanager/models.py:1515
msgid "Exception during nova action."
msgstr ""

#: trove/taskmanager/models.py:1517
#, python-format
msgid "Reverting action for instance %s"
msgstr ""

#: trove/taskmanager/models.py:1523
msgid "Restarting datastore."
msgstr ""

#: trove/taskmanager/models.py:1526
msgid "Cannot restart datastore because Nova server status is not ACTIVE"
msgstr ""

#: trove/taskmanager/models.py:1529
#, python-format
msgid "Error resizing instance %s."
msgstr ""

#: trove/taskmanager/models.py:1591
msgid "Error sending reset_configuration call."
msgstr ""

#: trove/tests/db/migrations.py:76
#, python-format
msgid ""
"The following migration scripts are missing a downgrade implementation:\n"
"\t%s"
msgstr ""

#: trove/tests/fakes/nova.py:271
#, python-format
msgid "volume status = %s"
msgstr ""

#: trove/tests/fakes/nova.py:300
#, python-format
msgid "FAKE_SERVERS_DB : %s"
msgstr ""

#: trove/tests/fakes/nova.py:323
#, python-format
msgid "Couldn't find server id %(id)s, collection=%(db)s"
msgstr ""

#: trove/tests/fakes/nova.py:343
#, python-format
msgid "Simulated event ended, deleting server %s."
msgstr ""

#: trove/tests/fakes/nova.py:486
#, python-format
msgid "Couldn't find volume id %(id)s, collection=%(db)s"
msgstr ""

