# Translations template for trove.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the trove project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: trove 5.0.0.dev33\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-11-05 06:14+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"

#: trove/backup/models.py:97
#, python-format
msgid "Unable to create backup record for instance: %s"
msgstr ""

#: trove/backup/models.py:260
#, python-format
msgid "Backup %s cannot be deleted because it is running."
msgstr ""

#: trove/backup/models.py:310
#, python-format
msgid "Bad location for backup object: %s"
msgstr ""

#: trove/backup/service.py:58
#, python-format
msgid "Creating a backup for tenant %s"
msgstr ""

#: trove/backup/service.py:69
#, python-format
msgid "Deleting backup for tenant %(tenant_id)s ID: %(backup_id)s"
msgstr ""

#: trove/cluster/models.py:129
#, python-format
msgid "Setting task to NONE on cluster %s"
msgstr ""

#: trove/cluster/models.py:208
#: trove/common/strategies/cluster/experimental/mongodb/api.py:245
#: trove/common/strategies/cluster/experimental/mongodb/api.py:448
#, python-format
msgid ""
"This action cannot be performed on the cluster while the current cluster "
"task is '%s'."
msgstr ""

#: trove/cluster/service.py:56 trove/cluster/service.py:86
#: trove/cluster/service.py:97 trove/cluster/service.py:111
#: trove/cluster/service.py:122 trove/cluster/service.py:137
#: trove/extensions/account/service.py:35
#: trove/extensions/account/service.py:46
#: trove/extensions/mgmt/clusters/service.py:44
#: trove/extensions/mgmt/clusters/service.py:60
#: trove/extensions/mgmt/clusters/service.py:73
#: trove/extensions/mgmt/host/service.py:34
#: trove/extensions/mgmt/host/service.py:43
#: trove/extensions/mgmt/instances/service.py:50
#: trove/extensions/mgmt/instances/service.py:74
#: trove/extensions/mgmt/instances/service.py:154
#: trove/extensions/mgmt/instances/service.py:173
#: trove/extensions/mgmt/instances/service.py:185
#: trove/extensions/mgmt/instances/service.py:198
#: trove/extensions/mgmt/quota/service.py:34
#: trove/extensions/mgmt/upgrade/service.py:36
#: trove/extensions/mgmt/volume/service.py:34
#: trove/extensions/mysql/service.py:57 trove/extensions/mysql/service.py:68
#: trove/extensions/mysql/service.py:81 trove/extensions/mysql/service.py:104
#: trove/extensions/mysql/service.py:121 trove/extensions/mysql/service.py:143
#: trove/extensions/mysql/service.py:191 trove/extensions/mysql/service.py:207
#: trove/extensions/mysql/service.py:222 trove/extensions/mysql/service.py:245
#: trove/extensions/mysql/service.py:256 trove/extensions/mysql/service.py:266
#, python-format
msgid ""
"req : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:57 trove/cluster/service.py:87
#: trove/cluster/service.py:112 trove/extensions/mgmt/clusters/service.py:61
#: trove/extensions/mgmt/host/service.py:45
#: trove/extensions/mgmt/instances/service.py:76
#: trove/extensions/mgmt/instances/service.py:156
#: trove/extensions/mgmt/instances/service.py:187
#: trove/extensions/mgmt/instances/service.py:199
#, python-format
msgid ""
"id : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:59 trove/extensions/mgmt/clusters/service.py:75
#: trove/extensions/mgmt/configuration/service.py:81
#: trove/extensions/mgmt/configuration/service.py:108
#: trove/extensions/mgmt/host/instance/service.py:35
#: trove/extensions/mgmt/host/instance/service.py:53
#: trove/extensions/mgmt/instances/service.py:97
#: trove/extensions/mgmt/instances/service.py:120
#: trove/extensions/mgmt/quota/service.py:44 trove/instance/service.py:74
msgid "Invalid request body."
msgstr ""

#: trove/cluster/service.py:71
#, python-format
msgid "No action '%(action)s' supplied by strategy for manager '%(manager)s'"
msgstr ""

#: trove/cluster/service.py:98
#, python-format
msgid ""
"cluster_id : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:99
#, python-format
msgid ""
"instance_id : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:138 trove/extensions/mysql/service.py:69
#: trove/extensions/mysql/service.py:257
#, python-format
msgid ""
"body : '%s'\n"
"\n"
msgstr ""

#: trove/cmd/manage.py:223
#, python-format
msgid "Possible wrong number of arguments supplied %s."
msgstr ""

#: trove/cmd/manage.py:226
msgid "Command failed, please check log for more info."
msgstr ""

#: trove/common/auth.py:65
#, python-format
msgid "Authorized tenant '%(tenant_id)s' request: %(request)s"
msgstr ""

#: trove/common/auth.py:70
#, python-format
msgid "User with tenant id %s cannot access this resource."
msgstr ""

#: trove/common/base_exception.py:103
msgid "Uncaught exception"
msgstr ""

#: trove/common/base_wsgi.py:112
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: trove/common/base_wsgi.py:373
msgid "Unsupported Content-Type"
msgstr ""

#: trove/common/base_wsgi.py:376
msgid "Malformed request body"
msgstr ""

#: trove/common/base_wsgi.py:662
msgid "Empty body provided in request"
msgstr ""

#: trove/common/base_wsgi.py:668
msgid "Unrecognized Content-Type provided in request"
msgstr ""

#: trove/common/base_wsgi.py:672
msgid "No Content-Type provided in request"
msgstr ""

#: trove/common/base_wsgi.py:678
msgid "Unable to deserialize body as provided Content-Type"
msgstr ""

#: trove/common/base_wsgi.py:728
msgid "cannot understand JSON"
msgstr ""

#: trove/common/base_wsgi.py:752
msgid "cannot understand XML"
msgstr ""

#: trove/common/debug_utils.py:100
msgid ""
"Enabling debugging with eventlet monkey patched could produce unexpected "
"behavior."
msgstr ""

#: trove/common/debug_utils.py:121
#, python-format
msgid ""
"Can't connect to remote debug server. Continuing to work in standard "
"mode. Error: %s."
msgstr ""

#: trove/common/exception.py:56
#, python-format
msgid "Failed to save %(model_name)s because: %(error)s."
msgstr ""

#: trove/common/exception.py:61
msgid "Invalid RPC Connection Reuse."
msgstr ""

#: trove/common/exception.py:66 trove/common/exception.py:81
#, python-format
msgid "Resource %(uuid)s cannot be found."
msgstr ""

#: trove/common/exception.py:71
#, python-format
msgid "Capability '%(capability)s' cannot be found."
msgstr ""

#: trove/common/exception.py:76
#, python-format
msgid "Capability '%(capability)s' is disabled."
msgstr ""

#: trove/common/exception.py:86
#, python-format
msgid "User %(uuid)s cannot be found on the instance."
msgstr ""

#: trove/common/exception.py:91
#, python-format
msgid "Database %(uuid)s cannot be found on the instance."
msgstr ""

#: trove/common/exception.py:96
#, python-format
msgid "Cannot find compute instance %(server_id)s for instance %(instance_id)s."
msgstr ""

#: trove/common/exception.py:99
#, python-format
msgid "Resource %(instance_id)s can not be retrieved."
msgstr ""

#: trove/common/exception.py:104
#, python-format
msgid "DnsRecord with name= %(name)s not found."
msgstr ""

#: trove/common/exception.py:109
#, python-format
msgid "Datastore '%(datastore)s' cannot be found."
msgstr ""

#: trove/common/exception.py:114
#, python-format
msgid "Datastore version '%(version)s' cannot be found."
msgstr ""

#: trove/common/exception.py:119
msgid "Datastores cannot be found."
msgstr ""

#: trove/common/exception.py:124
#, python-format
msgid ""
"Datastore '%(datastore)s' version id %(version_id)s and flavor "
"%(flavor_id)s mapping not found."
msgstr ""

#: trove/common/exception.py:130
#, python-format
msgid ""
"Datastore '%(datastore)s' version %(datastore_version)s and flavor "
"%(flavor_id)s mapping already exists."
msgstr ""

#: trove/common/exception.py:136
#, python-format
msgid "Datastore '%(datastore)s' has no version '%(version)s'."
msgstr ""

#: trove/common/exception.py:141
#, python-format
msgid "Datastore version '%(version)s' is not active."
msgstr ""

#: trove/common/exception.py:146
msgid "Please specify datastore. Default datastore cannot be found."
msgstr ""

#: trove/common/exception.py:152
#, python-format
msgid "Default version for datastore '%(datastore)s' not found."
msgstr ""

#: trove/common/exception.py:157
#, python-format
msgid "Datastore manager %(datastore_manager)s cannot be found."
msgstr ""

#: trove/common/exception.py:162
#, python-format
msgid ""
"The '%(operation)s' operation is not supported for the '%(datastore)s' "
"datastore."
msgstr ""

#: trove/common/exception.py:168
#, python-format
msgid "Multiple matches found for '%(name)s', use an UUID to be more specific."
msgstr ""

#: trove/common/exception.py:174
msgid "The server rejected the request due to its size or rate."
msgstr ""

#: trove/common/exception.py:180
#, python-format
msgid "Quota exceeded for resources: %(overs)s."
msgstr ""

#: trove/common/exception.py:185
msgid "Instance volume quota exceeded."
msgstr ""

#: trove/common/exception.py:190
#, python-format
msgid "An error occurred communicating with the guest: %(original_message)s."
msgstr ""

#: trove/common/exception.py:196
msgid "Timeout trying to connect to the Guest Agent."
msgstr ""

#: trove/common/exception.py:201
msgid ""
"The server could not comply with the request since it is either malformed"
" or otherwise incorrect."
msgstr ""

#: trove/common/exception.py:207
#, python-format
msgid "Required element/key - %(key)s was not specified."
msgstr ""

#: trove/common/exception.py:212
#, python-format
msgid "A database with the name \"%(name)s\" already exists."
msgstr ""

#: trove/common/exception.py:217
#, python-format
msgid "A user with the name \"%(name)s\" already exists."
msgstr ""

#: trove/common/exception.py:222
msgid ""
"A configuration group cannot be deleted if it is associated with one or "
"more non-terminated instances. Detach the configuration group from all "
"non-terminated instances and please try again."
msgstr ""

#: trove/common/exception.py:230
msgid "Unable to process the contained request."
msgstr ""

#: trove/common/exception.py:235
msgid "No change was requested in the size of the instance."
msgstr ""

#: trove/common/exception.py:240
msgid "Cannot find the volumes attached to compute instance %(server_id)."
msgstr ""

#: trove/common/exception.py:246
msgid "Failed to create a volume in Nova."
msgstr ""

#: trove/common/exception.py:251
msgid "Volume size was not specified."
msgstr ""

#: trove/common/exception.py:256
#, python-format
msgid "Local storage not specified in flavor ID: %(flavor)s."
msgstr ""

#: trove/common/exception.py:261
msgid "Local storage support is not enabled."
msgstr ""

#: trove/common/exception.py:266
msgid "Volume support is not enabled."
msgstr ""

#: trove/common/exception.py:271
#, python-format
msgid "Replication is not supported for the '%(datastore)s' datastore."
msgstr ""

#: trove/common/exception.py:277
msgid "Exception encountered attaching slave to new replica source."
msgstr ""

#: trove/common/exception.py:282
#, python-format
msgid ""
"An error occurred communicating with the task manager: "
"%(original_message)s."
msgstr ""

#: trove/common/exception.py:288
#, python-format
msgid "Value could not be converted: %(msg)s."
msgstr ""

#: trove/common/exception.py:293
msgid "Polling request timed out."
msgstr ""

#: trove/common/exception.py:298
msgid "User does not have admin privileges."
msgstr ""

#: trove/common/exception.py:303
#, python-format
msgid "The following values are invalid: %(errors)s."
msgstr ""

#: trove/common/exception.py:308
msgid "Not Found."
msgstr ""

#: trove/common/exception.py:313
msgid "Failed to update instances."
msgstr ""

#: trove/common/exception.py:318
msgid "Config file not found."
msgstr ""

#: trove/common/exception.py:323
msgid "Paste app not found."
msgstr ""

#: trove/common/exception.py:327
msgid "Quota could not be found."
msgstr ""

#: trove/common/exception.py:331
#, python-format
msgid "Quota for tenant %(tenant_id)s could not be found."
msgstr ""

#: trove/common/exception.py:335
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: trove/common/exception.py:339
msgid "Unable to upload Backup to swift."
msgstr ""

#: trove/common/exception.py:343
msgid "Unable to download Backup from swift"
msgstr ""

#: trove/common/exception.py:347
msgid "Unable to create Backup."
msgstr ""

#: trove/common/exception.py:351
msgid "Unable to update Backup table in database."
msgstr ""

#: trove/common/exception.py:356 trove/extensions/security_group/models.py:60
msgid "Failed to create Security Group."
msgstr ""

#: trove/common/exception.py:361
msgid "Failed to delete Security Group."
msgstr ""

#: trove/common/exception.py:366
msgid "Failed to create Security Group Rule."
msgstr ""

#: trove/common/exception.py:371
msgid "Failed to delete Security Group Rule."
msgstr ""

#: trove/common/exception.py:376
#, python-format
msgid ""
"Error creating security group rules. Malformed port(s). Port must be an "
"integer. FromPort = %(from)s greater than ToPort = %(to)s."
msgstr ""

#: trove/common/exception.py:383
#, python-format
msgid ""
"Unable to create instance because backup %(backup_id)s is not completed. "
"Actual state: %(state)s."
msgstr ""

#: trove/common/exception.py:388
#, python-format
msgid "Backup file in %(location)s was not found in the object storage."
msgstr ""

#: trove/common/exception.py:393
#, python-format
msgid ""
"The datastore from which the backup was taken, %(datastore1)s, does not "
"match the destination datastore of %(datastore2)s."
msgstr ""

#: trove/common/exception.py:399
#, python-format
msgid "Swift account not accessible for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:403
#, python-format
msgid "Swift is disabled for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:407
#, python-format
msgid ""
"The request indicates that user %(user)s should have access to database "
"%(database)s, but database %(database)s is not included in the initial "
"databases list."
msgstr ""

#: trove/common/exception.py:413
msgid ""
"Two or more databases share the same name in the initial databases list. "
"Please correct the names or remove the duplicate entries."
msgstr ""

#: trove/common/exception.py:419
msgid ""
"Two or more users share the same name and host in the initial users list."
" Please correct the names or remove the duplicate entries."
msgstr ""

#: trove/common/exception.py:425
#, python-format
msgid ""
"Current Swift object checksum does not match original checksum for backup"
" %(backup_id)s."
msgstr ""

#: trove/common/exception.py:430
#, python-format
msgid "%(key)s is not a supported configuration parameter."
msgstr ""

#: trove/common/exception.py:434
#, python-format
msgid "No configuration parser found for datastore %(datastore_manager)s."
msgstr ""

#: trove/common/exception.py:439
#, python-format
msgid ""
"Datastore Version on Configuration %(config_datastore_version)s does not "
"match the Datastore Version on the instance "
"%(instance_datastore_version)s."
msgstr ""

#: trove/common/exception.py:446
#, python-format
msgid ""
"%(parameter_name)s parameter can no longer be set as of "
"%(parameter_deleted_at)s."
msgstr ""

#: trove/common/exception.py:451
#, python-format
msgid ""
"%(parameter_name)s parameter already exists for datastore version "
"%(datastore_version)s."
msgstr ""

#: trove/common/exception.py:456
#, python-format
msgid ""
"Instance %(instance_id)s already has a Configuration Group attached: "
"%(configuration_id)s."
msgstr ""

#: trove/common/exception.py:461
#, python-format
msgid ""
"The operation you have requested cannot be executed because the instance "
"status is currently: %(status)s."
msgstr ""

#: trove/common/exception.py:467
#, python-format
msgid ""
"Endpoint not found for service_type=%(service_type)s, "
"endpoint_type=%(endpoint_type)s, endpoint_region=%(endpoint_region)s."
msgstr ""

#: trove/common/exception.py:474
msgid "Empty catalog."
msgstr ""

#: trove/common/exception.py:478
#, python-format
msgid ""
"Instance with replication strategy %(guest_strategy)s cannot replicate "
"from instance with replication strategy %(replication_strategy)s."
msgstr ""

#: trove/common/exception.py:484
#, python-format
msgid ""
"The target instance has only %(slave_volume_size)sG free, but the "
"replication snapshot contains %(dataset_size)sG of data."
msgstr ""

#: trove/common/exception.py:490
msgid "The replica source cannot be deleted without detaching the replicas."
msgstr ""

#: trove/common/exception.py:495
#, python-format
msgid "Cluster '%(cluster)s' cannot be found."
msgstr ""

#: trove/common/exception.py:499
msgid "The flavor for each instance in a cluster must be the same."
msgstr ""

#: trove/common/exception.py:503
msgid "A volume size is required for each instance in the cluster."
msgstr ""

#: trove/common/exception.py:507
msgid "The volume size for each instance in a cluster must be the same."
msgstr ""

#: trove/common/exception.py:512
#, python-format
msgid ""
"The number of instances for your initial cluster must be "
"%(num_instances)s."
msgstr ""

#: trove/common/exception.py:517
#, python-format
msgid ""
"The number of instances for your initial cluster must be at least "
"%(num_instances)s."
msgstr ""

#: trove/common/exception.py:522
msgid "Operation not supported for instances that are part of a cluster."
msgstr ""

#: trove/common/exception.py:528
#, python-format
msgid "The '%(operation)s' operation is not supported for cluster."
msgstr ""

#: trove/common/exception.py:532
#, python-format
msgid "Operation not allowed for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:536
#, python-format
msgid "Clusters not supported for %(datastore)s-%(datastore_version)s."
msgstr ""

#: trove/common/exception.py:541
#, python-format
msgid ""
"Backup is too large for given flavor or volume. Backup size: "
"%(backup_size)s GBs. Available size: %(disk_size)s GBs."
msgstr ""

#: trove/common/exception.py:548
#, python-format
msgid "Image %(uuid)s cannot be found."
msgstr ""

#: trove/common/exception.py:553
#, python-format
msgid "A datastore version with the name '%(name)s' already exists."
msgstr ""

#: trove/common/extensions.py:203
#, python-format
msgid "Extension with alias %s does not exist"
msgstr ""

#: trove/common/extensions.py:400
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: trove/common/limits.py:88
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: trove/common/limits.py:212
msgid "This request was rate-limited."
msgstr ""

#: trove/common/template.py:136
#, python-format
msgid "Missing heat template for %(s_datastore_manager)s."
msgstr ""

#: trove/common/utils.py:235
#, python-format
msgid ""
"Command '%(cmd)s' failed. %(description)s Exit code: %(exit_code)s\n"
"stderr: %(stderr)s\n"
"stdout: %(stdout)s"
msgstr ""

#: trove/common/utils.py:244
msgid "Got a timeout but not the one expected."
msgstr ""

#: trove/common/utils.py:247
#, python-format
msgid ""
"Time out after waiting %(time)s seconds when running proc: %(args)s "
"%(kwargs)s."
msgstr ""

#: trove/common/wsgi.py:144
msgid "version not supported"
msgstr ""

#: trove/common/wsgi.py:303
msgid "Unserializable result detected."
msgstr ""

#: trove/common/wsgi.py:529
msgid "Invalid service catalog json."
msgstr ""

#: trove/common/wsgi.py:574
#, python-format
msgid "Caught error: %s."
msgstr ""

#: trove/common/rpc/service.py:81
msgid "Failed to stop RPC server before shutdown. "
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:74
#, python-format
msgid ""
"An instance with the options %(given)s is missing the MongoDB required "
"option %(expected)s."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:81
#, python-format
msgid ""
"The value %(value)s for key %(key)s is invalid. Allowed values are "
"%(valid)s."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:100
#, python-format
msgid "The arguments %s are not supported by MongoDB."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:255
msgid ""
"This action cannot be performed on the cluster as no reference shard "
"exists."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:308
#: trove/common/strategies/cluster/experimental/mongodb/api.py:339
msgid "Not instances specified for grow operation."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:355
#, python-format
msgid ""
"Instances %s cannot be deleted. MongoDB cluster shink only supports "
"removing replicas and query routers."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:365
msgid ""
"Cannot delete all remaining query routers. At least one query router must"
" be available in the cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:390
#, python-format
msgid ""
"MongoDB cluster shrink only supports removing an entire shard. Shard "
"%(shard)s has members: %(instances)s"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:476
#, python-format
msgid "Replica instance does not have required field(s) %s."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:484
#, python-format
msgid "Instance type %s not supported for MongoDB cluster grow."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:515
msgid "Duplicate member names not allowed."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:520
#, python-format
msgid "related_to target(s) %(targets)s do not match any specified names."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:542
msgid "Members of the same shard have mismatching flavorRef and/or volume values."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:576
#, python-format
msgid ""
"Shard with instance %s is still active. Please remove the shard from the "
"MongoDB cluster before shrinking."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:123
#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:397
msgid "error adding config servers"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:142
msgid "timeout for building cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:189
msgid "timeout for building shard."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:263
msgid "timeout for growing cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:287
#: trove/taskmanager/models.py:274
msgid "timeout for instances to be marked as deleted."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:298
msgid "timeout for shrinking cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:332
msgid "error initializing replica set"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:353
msgid "error adding shard"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:367
msgid "no query routers ready to accept requests"
msgstr ""

#: trove/common/strategies/cluster/experimental/pxc/taskmanager.py:130
#: trove/common/strategies/cluster/experimental/redis/taskmanager.py:88
#: trove/common/strategies/cluster/experimental/vertica/taskmanager.py:86
msgid "Error creating cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/pxc/taskmanager.py:140
#: trove/common/strategies/cluster/experimental/redis/taskmanager.py:98
#: trove/common/strategies/cluster/experimental/vertica/taskmanager.py:96
msgid "Timeout for building cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/redis/api.py:194
msgid "Some nodes cannot be removed (check slots)"
msgstr ""

#: trove/common/strategies/cluster/experimental/redis/taskmanager.py:144
msgid "Timeout for growing cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/redis/taskmanager.py:147
#, python-format
msgid "Error growing cluster %s."
msgstr ""

#: trove/conductor/manager.py:50
#, python-format
msgid "[Instance %s] sent field not present. Cannot compare."
msgstr ""

#: trove/conductor/manager.py:80
#, python-format
msgid "[Instance %s] Rec'd message is older than last seen. Discarding."
msgstr ""

#: trove/conductor/manager.py:113
#, python-format
msgid ""
"[Instance: %(instance)s] Backup IDs mismatch! Expected %(expected)s, "
"found %(found)s"
msgstr ""

#: trove/conductor/manager.py:122
#, python-format
msgid ""
"[Instance: %(instance)s] Backup instance IDs mismatch! Expected "
"%(expected)s, found %(found)s"
msgstr ""

#: trove/configuration/models.py:139
#, python-format
msgid "Configuration group with ID %s could not be found."
msgstr ""

#: trove/configuration/service.py:92
#, python-format
msgid ""
"Creating configuration group on tenant %(tenant_id)s with name: "
"%(cfg_name)s"
msgstr ""

#: trove/configuration/service.py:124
#, python-format
msgid "Deleting configuration group %(cfg_id)s on tenant: %(tenant_id)s"
msgstr ""

#: trove/configuration/service.py:140
#, python-format
msgid "Updating configuration group %(cfg_id)s for tenant id %(tenant_id)s"
msgstr ""

#: trove/configuration/service.py:209
msgid "Validating configuration values"
msgstr ""

#: trove/configuration/service.py:220
#, python-format
msgid ""
"Configuration groups are not supported for this datastore: %(name)s "
"%(version)s"
msgstr ""

#: trove/configuration/service.py:231
#, python-format
msgid ""
"The configuration parameter %(key)s is not supported for this datastore: "
"%(name)s %(version)s."
msgstr ""

#: trove/configuration/service.py:244
#, python-format
msgid ""
"The value provided for the configuration parameter %(key)s is not of type"
" %(type)s."
msgstr ""

#: trove/configuration/service.py:254
msgid ""
"Invalid or unsupported min value defined in the configuration-parameters "
"configuration file. Expected integer."
msgstr ""

#: trove/configuration/service.py:260
#, python-format
msgid ""
"The value for the configuration parameter %(key)s is less than the "
"minimum allowed: %(min)s"
msgstr ""

#: trove/configuration/service.py:270
msgid ""
"Invalid or unsupported max value defined in the configuration-parameters "
"configuration file. Expected integer."
msgstr ""

#: trove/configuration/service.py:276
#, python-format
msgid ""
"The value for the configuration parameter %(key)s is greater than the "
"maximum allowed: %(max)s"
msgstr ""

#: trove/configuration/service.py:291
msgid ""
"Invalid or unsupported type defined in the configuration-parameters "
"configuration file."
msgstr ""

#: trove/configuration/service.py:301
#, python-format
msgid "%s is not a supported configuration parameter."
msgstr ""

#: trove/datastore/models.py:219
#, python-format
msgid ""
"Somehow we got a datastore version capability without a parent, that "
"shouldn't happen. %s"
msgstr ""

#: trove/datastore/models.py:262
#, python-format
msgid "Capability Override not found for capability %s"
msgstr ""

#: trove/datastore/models.py:667
msgid "Specify both the datastore and datastore_version_id."
msgstr ""

#: trove/db/models.py:99
#, python-format
msgid "%(s_name)s Not Found"
msgstr ""

#: trove/db/models.py:104
#, python-format
msgid "Tenant %(s_tenant)s tried to access %(s_name)s, owned by %(s_owner)s."
msgstr ""

#: trove/db/models.py:110
#, python-format
msgid "Tenant %(s_tenant)s cannot access %(s_name)s"
msgstr ""

#: trove/db/sqlalchemy/session.py:82
#, python-format
msgid "Creating SQLAlchemy engine with args: %s"
msgstr ""

#: trove/dns/models.py:69
#, python-format
msgid "%s Not Found"
msgstr ""

#: trove/extensions/account/service.py:36
#, python-format
msgid "Showing account information for '%(account)s' to '%(tenant)s'"
msgstr ""

#: trove/extensions/account/service.py:47
#, python-format
msgid "Showing all accounts with instances for '%s'"
msgstr ""

#: trove/extensions/mgmt/clusters/service.py:82
msgid "Invalid cluster action requested."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:62
msgid "max_size is required for integer data type."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:65
msgid "min_size is required for integer data type."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:71
msgid "max_size must be greater than or equal to min_size."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:77
msgid "Creating configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:104
msgid "Updating configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:129
msgid "Deleting configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:135
#, python-format
msgid "Parameter %s does not exist in the database."
msgstr ""

#: trove/extensions/mgmt/datastores/service.py:51
#, python-format
msgid ""
"Tenant: '%(tenant)s' is adding the datastore version: '%(version)s' to "
"datastore: '%(datastore)s'"
msgstr ""

#: trove/extensions/mgmt/datastores/service.py:66
#, python-format
msgid "Creating datastore %s"
msgstr ""

#: trove/extensions/mgmt/datastores/service.py:109
#, python-format
msgid ""
"Tenant: '%(tenant)s' is updating the datastore version: '%(version)s' for"
" datastore: '%(datastore)s'"
msgstr ""

#: trove/extensions/mgmt/datastores/service.py:147
#, python-format
msgid ""
"Tenant: '%(tenant)s' is removing the datastore version: '%(version)s' for"
" datastore: '%(datastore)s'"
msgstr ""

#: trove/extensions/mgmt/host/models.py:75
#, python-format
msgid "Compute Instance ID found with no associated RD instance: %s."
msgstr ""

#: trove/extensions/mgmt/host/models.py:89
#, python-format
msgid "Unable to update instance: %s."
msgstr ""

#: trove/extensions/mgmt/host/models.py:92
#, python-format
msgid "Failed to update instances: %s."
msgstr ""

#: trove/extensions/mgmt/host/service.py:35
#, python-format
msgid "Indexing a host for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/host/service.py:44
#, python-format
msgid "Showing a host for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/host/instance/service.py:43
#: trove/extensions/mgmt/instances/service.py:110
msgid "Only one action can be specified per request."
msgstr ""

#: trove/extensions/mgmt/host/instance/service.py:47
#, python-format
msgid "Invalid host action: %s"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:51
#, python-format
msgid "Indexing a database instance for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:75
#, python-format
msgid "Showing a database instance for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:114
#, python-format
msgid "Invalid instance action: %s"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:155
#, python-format
msgid "Showing root history for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:174
#, python-format
msgid "Showing hardware info for instance '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:186
#, python-format
msgid "Showing instance diagnostics for the instance '%s'"
msgstr ""

#: trove/extensions/mgmt/quota/service.py:35
#, python-format
msgid "Indexing quota info for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/upgrade/service.py:37
msgid "Sending upgrade notification"
msgstr ""

#: trove/extensions/mgmt/upgrade/service.py:38
#, python-format
msgid "Admin tenant_id: %s"
msgstr ""

#: trove/extensions/mgmt/volume/service.py:35
#, python-format
msgid "Indexing storage info for tenant '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:56
#, python-format
msgid "Listing users for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:67
#, python-format
msgid "Creating users for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:80
#, python-format
msgid "Deleting user for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:103
#, python-format
msgid "Showing a user for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:120
#, python-format
msgid "Updating user attributes for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:142
#, python-format
msgid "Updating user passwords for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:190
#, python-format
msgid "Showing user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:197 trove/extensions/mysql/service.py:212
#: trove/extensions/mysql/service.py:227
#, python-format
msgid "No such user: %(user)s "
msgstr ""

#: trove/extensions/mysql/service.py:206
#, python-format
msgid "Granting user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:221
#, python-format
msgid "Revoking user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:244
#, python-format
msgid "Listing schemas for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:255
#, python-format
msgid "Creating schema for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:265
#, python-format
msgid "Deleting schema for instance '%s'"
msgstr ""

#: trove/extensions/security_group/models.py:70
#: trove/extensions/security_group/models.py:167
msgid "Failed to create remote security group."
msgstr ""

#: trove/extensions/security_group/models.py:77 trove/taskmanager/models.py:715
#, python-format
msgid "Security Group for %s"
msgstr ""

#: trove/extensions/security_group/models.py:115
#: trove/extensions/security_group/models.py:181
msgid "Failed to delete security group."
msgstr ""

#: trove/extensions/security_group/models.py:131
#, python-format
msgid "Security Group with id: %(id)s already had been deleted"
msgstr ""

#: trove/extensions/security_group/models.py:215
msgid "Security Group does not have id defined!"
msgstr ""

#: trove/extensions/security_group/service.py:131
#, python-format
msgid "Create Security Group Rules Required field(s) - %s"
msgstr ""

#: trove/guestagent/api.py:67 trove/guestagent/api.py:70
#: trove/guestagent/api.py:81 trove/guestagent/api.py:84
#, python-format
msgid "Error calling %s"
msgstr ""

#: trove/guestagent/dbaas.py:92
msgid "Error getting volume stats."
msgstr ""

#: trove/guestagent/models.py:87
#, python-format
msgid "Error finding instance %s"
msgstr ""

#: trove/guestagent/pkg.py:122
#, python-format
msgid "Error removing conflict %(package)s"
msgstr ""

#: trove/guestagent/pkg.py:221
#, python-format
msgid "Unexpected output from rpm command. (%(output)s)"
msgstr ""

#: trove/guestagent/pkg.py:244
msgid "Error fixing dpkg"
msgstr ""

#: trove/guestagent/pkg.py:356
msgid "Error updating the apt sources"
msgstr ""

#: trove/guestagent/volume.py:69
msgid "Error getting device status"
msgstr ""

#: trove/guestagent/volume.py:70
#, python-format
msgid "InvalidDevicePath(path=%s)"
msgstr ""

#: trove/guestagent/volume.py:86
msgid "Device path at {0} did not seem to be {1}."
msgstr ""

#: trove/guestagent/volume.py:90
msgid "Volume was not formatted."
msgstr ""

#: trove/guestagent/volume.py:133
msgid "Error resizing file system."
msgstr ""

#: trove/guestagent/volume.py:134
#, python-format
msgid "Error resizing the filesystem: %s"
msgstr ""

#: trove/guestagent/volume.py:147
#, python-format
msgid "Device %(device)s is already mounted in %(mount_point)s. Unmounting now."
msgstr ""

#: trove/guestagent/volume.py:160
msgid "Error retrieving mount points"
msgstr ""

#: trove/guestagent/volume.py:161
#, python-format
msgid "Could not obtain a list of mount points for device: %s"
msgstr ""

#: trove/guestagent/volume.py:172
#, python-format
msgid "Error setting readhead size to %(size)s for device %(device)s."
msgstr ""

#: trove/guestagent/volume.py:175
#, python-format
msgid "Error setting readhead size: %s."
msgstr ""

#: trove/guestagent/backup/backupagent.py:117
#, python-format
msgid "Error saving backup: %(backup_id)s."
msgstr ""

#: trove/guestagent/backup/backupagent.py:121
#, python-format
msgid "Completed backup %(backup_id)s."
msgstr ""

#: trove/guestagent/backup/backupagent.py:178
#, python-format
msgid "Error restoring backup %(id)s."
msgstr ""

#: trove/guestagent/common/operating_system.py:61
#, python-format
msgid "File does not exist: %s"
msgstr ""

#: trove/guestagent/common/operating_system.py:106
#, python-format
msgid "Invalid path: %s"
msgstr ""

#: trove/guestagent/common/operating_system.py:286
#, python-format
msgid "Service control command not available: %s"
msgstr ""

#: trove/guestagent/common/operating_system.py:289
msgid "Candidate service names not specified."
msgstr ""

#: trove/guestagent/common/operating_system.py:382
msgid "Cannot create a blank directory."
msgstr ""

#: trove/guestagent/common/operating_system.py:411
msgid "Cannot change ownership of a blank file or directory."
msgstr ""

#: trove/guestagent/common/operating_system.py:414
msgid "Please specify owner or group, or both."
msgstr ""

#: trove/guestagent/common/operating_system.py:470
msgid "Cannot change mode of a blank file."
msgstr ""

#: trove/guestagent/common/operating_system.py:500
msgid "No file mode specified."
msgstr ""

#: trove/guestagent/common/operating_system.py:524
msgid "Cannot remove a blank file."
msgstr ""

#: trove/guestagent/common/operating_system.py:548
#: trove/guestagent/common/operating_system.py:585
msgid "Missing source path."
msgstr ""

#: trove/guestagent/common/operating_system.py:550
#: trove/guestagent/common/operating_system.py:587
msgid "Missing destination path."
msgstr ""

#: trove/guestagent/common/operating_system.py:626
#, python-format
msgid "Got unknown keyword args: %r"
msgstr ""

#: trove/guestagent/datastore/manager.py:103
#, python-format
msgid "Starting datastore prepare for '%s'."
msgstr ""

#: trove/guestagent/datastore/manager.py:113
#, python-format
msgid "An error occurred preparing datastore: %s"
msgstr ""

#: trove/guestagent/datastore/manager.py:117
#, python-format
msgid "Ending datastore prepare for '%s'."
msgstr ""

#: trove/guestagent/datastore/manager.py:124
msgid "Completed setup of datastore successfully."
msgstr ""

#: trove/guestagent/datastore/manager.py:137
#, python-format
msgid "An error occurred creating databases/users: %s"
msgstr ""

#: trove/guestagent/datastore/manager.py:148
#, python-format
msgid "An error occurred in post prepare: %s"
msgstr ""

#: trove/guestagent/datastore/service.py:119
#, python-format
msgid "Set final status to %s."
msgstr ""

#: trove/guestagent/datastore/service.py:126
msgid "Ending restart."
msgstr ""

#: trove/guestagent/datastore/service.py:134
#, python-format
msgid "Current database status is '%s'."
msgstr ""

#: trove/guestagent/datastore/service.py:183
msgid ""
"DB server is not installed or is in restart mode, so for now we'll skip "
"determining the status of DB on this instance."
msgstr ""

#: trove/guestagent/datastore/service.py:213
msgid "Database restart failed."
msgstr ""

#: trove/guestagent/datastore/service.py:240
msgid "Starting database service."
msgstr ""

#: trove/guestagent/datastore/service.py:246
msgid "Database failed to start."
msgstr ""

#: trove/guestagent/datastore/service.py:248
msgid "Database has started successfully."
msgstr ""

#: trove/guestagent/datastore/service.py:251
msgid "Enable service auto-start on boot."
msgstr ""

#: trove/guestagent/datastore/service.py:274
msgid "Stopping database service."
msgstr ""

#: trove/guestagent/datastore/service.py:280
msgid "Database failed to stop."
msgstr ""

#: trove/guestagent/datastore/service.py:282
msgid "Database has stopped successfully."
msgstr ""

#: trove/guestagent/datastore/service.py:285
msgid "Disable service auto-start on boot."
msgstr ""

#: trove/guestagent/datastore/service.py:304
#, python-format
msgid ""
"Service status did not change to %(status)s within the given timeout: "
"%(timeout)ds"
msgstr ""

#: trove/guestagent/datastore/service.py:336
msgid "Timeout while waiting for database status to change."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:51
msgid "Preparing Guest as a Cassandra Server"
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:68
msgid "Error while initiating storage structure."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:76
msgid "Error starting Cassandra"
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:88
msgid "Error killing Cassandra start command."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:90
msgid "Could not start Cassandra"
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:102
#: trove/guestagent/datastore/experimental/cassandra/service.py:104
msgid "Could not stop Cassandra."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:109
msgid "Restarting Cassandra server."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:150
#, python-format
msgid "Exception generating Cassandra configuration %s."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:157
msgid "Wrote new Cassandra configuration."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:206
msgid "Starting Cassandra with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:210
#, python-format
msgid "Cannot execute start_db_with_conf_changes because Cassandra state == %s."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:236
msgid "Error getting Cassandra status"
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/manager.py:161
#, python-format
msgid "Restoring database from backup %s"
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/manager.py:166
#, python-format
msgid "Error performing restore from backup %s"
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/manager.py:171
msgid "Restored database successfully"
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:62
msgid "Preparing Guest as Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:71
msgid "Couchbase Server change data dir path."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:90
msgid "Couchbase Server initial setup finished."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:92
msgid "Error performing initial Couchbase setup."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:112
msgid "Enabling Couchbase Server on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:119
msgid "Command to enable Couchbase Server on boot not found."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:152
#: trove/guestagent/datastore/experimental/couchbase/service.py:154
msgid "Could not stop Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:157
msgid "Restarting Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:169
msgid "Starting Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:185
msgid "Start up of Couchbase Server failed."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:189
msgid "Error killing Couchbase start command."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:197
msgid "Starting Couchbase with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:198
#, python-format
msgid ""
"Configuration contents:\n"
" %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:200
#, python-format
msgid "Cannot start Couchbase with configuration changes. Couchbase state == %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:230
msgid "Error getting the Couchbase status."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:236
msgid "Error getting the root password from the native Couchbase config file."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:250
msgid ""
"Error getting Couchbase status using the password parsed from the native "
"Couchbase config file."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:319
#, python-format
msgid "An error occurred in saving password (%(errno)s). %(strerror)s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:61
msgid "Preparing guest as a CouchDB server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:65
msgid "Finished installing CouchDB server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:101
msgid "Error changing permissions."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:133
msgid "Stopping CouchDB."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:143
msgid "CouchDB service is not discovered."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:148
#: trove/guestagent/datastore/experimental/couchdb/service.py:150
msgid "Could not stop CouchDB."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:156
msgid "Starting CouchDB server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:172
msgid "Start up of CouchDB server failed."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:177
msgid "Restarting CouchDB server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:194
msgid "Error while trying to update bind address of CouchDB server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:205
msgid "Starting CouchDB with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:232
msgid "Error getting CouchDB status."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:62
msgid "Command to change ownership of  DB2 data directory failed."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:70
msgid "Command to enable DB2 server on boot failed."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:78
msgid "Command to disable DB2 server on boot failed."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:89
msgid "Starting DB2 with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:103
msgid "Start of DB2 server instance failed."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:105
msgid "Could not start DB2."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:119
#: trove/guestagent/datastore/experimental/db2/service.py:121
msgid "Could not stop DB2."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:147
msgid "Error getting the DB2 server status."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:174
#, python-format
msgid "There was an error creating database: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:179
#, python-format
msgid "Creating the following databases failed: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:192
#, python-format
msgid "There was an error while deleting database:%s."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:194
#, python-format
msgid "Unable to delete database: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:239
#, python-format
msgid "An error occurred listing databases: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:257
#, python-format
msgid "Error creating user: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:275
#, python-format
msgid "An error occurred creating users: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:311
#, python-format
msgid "There was an error while deleting user: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:313
#, python-format
msgid "Unable to delete user: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/manager.py:185
#: trove/guestagent/datastore/experimental/redis/manager.py:73
#: trove/guestagent/datastore/mysql_common/manager.py:138
#, python-format
msgid "Restoring database from backup %s."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/manager.py:189
#: trove/guestagent/datastore/experimental/redis/manager.py:77
#: trove/guestagent/datastore/mysql_common/manager.py:142
#, python-format
msgid "Error performing restore from backup %s."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/manager.py:193
#: trove/guestagent/datastore/experimental/redis/manager.py:81
#: trove/guestagent/datastore/mysql_common/manager.py:146
msgid "Restored database successfully."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:87
msgid "Preparing Guest as MongoDB."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:91
msgid "Finished installing MongoDB server."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:102
msgid "Enabling MongoDB on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:108
#: trove/guestagent/datastore/experimental/mongodb/service.py:130
msgid "MongoDB service is not discovered."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:111
msgid "Disabling MongoDB on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:120
msgid "Stopping MongoDB."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:135
msgid "Could not stop MongoDB."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:137
msgid "Could not stop MongoDB"
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:140
msgid "Restarting MongoDB."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:149
msgid "Starting MongoDB."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:168
msgid "Start up of MongoDB failed."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:178
msgid "Error killing MongoDB start command."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:192
msgid "Starting MongoDB with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:197
#: trove/guestagent/datastore/experimental/redis/service.py:237
msgid "Initiating config."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:206
#: trove/guestagent/datastore/experimental/redis/service.py:245
#: trove/guestagent/datastore/mysql_common/service.py:970
#: trove/guestagent/datastore/mysql_common/service.py:976
msgid "Resetting configuration."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:260
#, python-format
msgid "Bad cluster configuration; instance type given as %s."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:268
msgid "Configuring instance as a cluster query router."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:302
msgid "Configuring instance as a cluster config server."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:308
msgid "Configuring instance as a cluster member."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:348
msgid "Error clearing storage."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:364
#, python-format
msgid "Setting config servers: %s"
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:492
msgid "Cannot secure the instance. The service is still running."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:557
msgid "Error getting MongoDB status."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:601
msgid "User's password is empty."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/access.py:38
msgid "{guest_id}: Granting user ({user}) access to database ({database})."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/access.py:60
msgid "{guest_id}: Revoking user ({user}) access to database({database})."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/config.py:107
msgid "{guest_id}: Going into restart mode for config file changes."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/config.py:117
msgid "{guest_id}: Ending restart mode for config file changes."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/database.py:46
msgid "{guest_id}: Creating database {name}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/database.py:68
msgid "{guest_id}: Dropping database {name}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/install.py:50
msgid "{guest_id}: Installing ({packages})."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:54
msgid "{guest_id}: Creating user {name} with password {password}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:137
msgid "{guest_id}: Dropping user {name}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:191
msgid "{guest_id}: Changing password for {user} to {password}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:230
msgid "{guest_id}: Changing username for {old} to {new}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:245
msgid "{guest_id}: Regranting permissions from {old} to {new}."
msgstr ""

#: trove/guestagent/datastore/experimental/pxc/manager.py:74
#: trove/guestagent/datastore/experimental/vertica/manager.py:201
msgid "Cluster installation failed."
msgstr ""

#: trove/guestagent/datastore/experimental/pxc/service.py:67
#: trove/guestagent/datastore/mysql_common/service.py:661
msgid "Generating admin password."
msgstr ""

#: trove/guestagent/datastore/experimental/pxc/service.py:103
#: trove/guestagent/datastore/mysql_common/service.py:849
msgid "Granting Replication Slave privilege."
msgstr ""

#: trove/guestagent/datastore/experimental/pxc/service.py:113
msgid "Bootstraping cluster."
msgstr ""

#: trove/guestagent/datastore/experimental/pxc/service.py:121
msgid "Error bootstrapping cluster."
msgstr ""

#: trove/guestagent/datastore/experimental/pxc/service.py:122
msgid "Service is not discovered."
msgstr ""

#: trove/guestagent/datastore/experimental/pxc/service.py:126
msgid "Installing cluster configuration."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/manager.py:98
msgid "Writing redis configuration."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/manager.py:338
msgid "Retrieving latest repl offset."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/manager.py:342
#, python-format
msgid "Waiting on repl offset '%s'."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/manager.py:352
#, python-format
msgid "Timeout occurred waiting for Redis repl offset to change to '%s'."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:64
msgid "Error getting Redis status."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:125
msgid "Preparing Guest as Redis Server."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:127
msgid "Installing Redis."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:129
msgid "Redis installed completely."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:148
msgid "Enabling Redis on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:155
msgid "Disabling Redis on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:162
msgid "Stopping redis."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:170
msgid "Could not stop Redis."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:232
msgid "Starting redis with conf changes."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:253
msgid "Starting redis."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:259
msgid "Start up of redis failed."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:266
msgid "Error killing stalled redis start command."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:396
#, python-format
msgid "Error joining node to cluster at %s."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:409
#, python-format
msgid "Error executing addslots: %s"
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:413
#, python-format
msgid "Error adding slots %(first_slot)s-%(last_slot)s to cluster."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:424
msgid "Error getting node info."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:431
msgid "Unable to determine node details"
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:446
msgid "Error validating node to for removal."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:455
msgid "Error removing node from cluster."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:494
#, python-format
msgid "Could not set configuration property '%(name)s' to '%(value)s'."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:511
#, python-format
msgid "Redis command '%(cmd_name)s %(cmd_args)s' failed."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:525
#, python-format
msgid "Output from Redis command: %s"
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:526
#, python-format
msgid "Field %(field)s not found (Section: '%(sec)s')."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:534
#, python-format
msgid ""
"Timeout occurred waiting for Redis field '%(field)s' to change to "
"'%(val)s'."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/manager.py:64
#, python-format
msgid "Bad cluster configuration: instance type given as %s."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:50
msgid "Service Status is RUNNING."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:53
msgid "Service Status is SHUTDOWN."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:56
#: trove/guestagent/datastore/mysql_common/service.py:152
msgid "Failed to get database status."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:76
msgid "Failed to enable db on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:86
msgid "Failed to disable db on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:91
msgid "Stopping Vertica."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:109
msgid "Could not stop Vertica."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:116
msgid "Failed to stop database."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:121
msgid "Starting Vertica."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:144
msgid "Starting Vertica with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:158
msgid "Creating database on Vertica host."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:167
#: trove/guestagent/datastore/experimental/vertica/service.py:168
msgid "Vertica database create failed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:169
msgid "Vertica database create completed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:173
msgid "Installing Vertica Server."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:180
#: trove/guestagent/datastore/experimental/vertica/service.py:181
msgid "install_vertica failed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:183
msgid "install_vertica completed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:218
#, python-format
msgid "Failed to read config %s."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:227
msgid "Preparing Guest as Vertica Server."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:249
msgid "Failed to prepare for install_vertica."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:254
msgid "Creating user in Vertica database."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:262
#, python-format
msgid "Failed to create user %s."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:293
#: trove/guestagent/datastore/experimental/vertica/service.py:296
#: trove/guestagent/datastore/experimental/vertica/service.py:297
#, python-format
msgid "Failed to update %s password."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:310
#: trove/guestagent/datastore/experimental/vertica/service.py:312
msgid "Failed to query for root user."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:331
msgid "Cannot read public key."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:358
msgid "Cannot install public keys."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:371
msgid "Cannot export configuration."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:96
msgid "/root/.mysql_secret does not exist."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:106
msgid "Cannot change mysql password."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:149
msgid "MySQL Service Status is RUNNING."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:159
#, python-format
msgid "MySQL Service Status %(pid)s is BLOCKED."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:163
msgid "Process execution failed."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:168
msgid "MySQL Service Status is CRASHED."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:171
msgid "MySQL Service Status is SHUTDOWN."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:365
msgid "Error Getting user information"
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:366
#, python-format
msgid "Username %(user)s is not valid: %(reason)s"
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:398
msgid "Error granting access"
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:399
#, python-format
msgid "Grant access to %s is not allowed"
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:648
msgid "Preparing Guest as MySQL Server."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:657
msgid "Finished installing MySQL server."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:694
msgid "Preserving root access from restore."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:725
msgid "Error enabling MySQL start on boot."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:735
msgid "Error disabling MySQL start on boot."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:739
msgid "Stopping MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:747
msgid "Error stopping MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:752
msgid "Could not stop MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:794
#, python-format
msgid "Unable to set %(key)s with value %(value)s."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:809
msgid "Wiping ib_logfiles."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:827
msgid "Removing replication configuration file."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:881
msgid "Starting slave replication."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:888
msgid "Stopping slave replication."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:902
msgid "Stopping replication master."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:917
#, python-format
msgid "Replication is now %s."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:920
#, python-format
msgid "Replication is not %(status)s after %(max)d seconds."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:924
msgid "Starting MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:951
msgid "Start up of MySQL failed."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:957
msgid "Error killing stalled MySQL start command."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:963
msgid "Starting MySQL with conf changes."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:967
#, python-format
msgid "Cannot execute start_db_with_conf_changes because MySQL state == %s."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:981
#: trove/guestagent/datastore/mysql_common/service.py:1018
msgid "Retrieving latest txn id."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:1022
#, python-format
msgid "Waiting on txn '%s'."
msgstr ""

#: trove/guestagent/db/models.py:62 trove/guestagent/db/models.py:490
#, python-format
msgid "Bad dictionary. Keys: %(keys)s. Required: %(reqs)s"
msgstr ""

#: trove/guestagent/db/models.py:95
#, python-format
msgid "Schema name '%(name)s' is too long. Max length = %(max_length)d."
msgstr ""

#: trove/guestagent/db/models.py:100
#, python-format
msgid "'%s' is not a valid schema name."
msgstr ""

#: trove/guestagent/db/models.py:138
#, python-format
msgid "Bad args. name: %(name)s, deserializing %(deser)s."
msgstr ""

#: trove/guestagent/db/models.py:432
#, python-format
msgid "%(val)s not a valid collation for charset %(char)s."
msgstr ""

#: trove/guestagent/db/models.py:438
#, python-format
msgid "'%s' not a valid collation."
msgstr ""

#: trove/guestagent/db/models.py:456
#, python-format
msgid "'%s' not a valid character set."
msgstr ""

#: trove/guestagent/db/models.py:468
#, python-format
msgid "'%s' is not a valid database name."
msgstr ""

#: trove/guestagent/db/models.py:470
#, python-format
msgid "Database name '%s' is too long. Max length = 64."
msgstr ""

#: trove/guestagent/db/models.py:516 trove/guestagent/db/models.py:812
#, python-format
msgid "'%s' is not a valid password."
msgstr ""

#: trove/guestagent/db/models.py:538 trove/guestagent/db/models.py:835
#, python-format
msgid "'%s' is not a valid hostname."
msgstr ""

#: trove/guestagent/db/models.py:556
#, python-format
msgid "User name '%(name)s' is too long. Max length = %(max_length)d."
msgstr ""

#: trove/guestagent/db/models.py:561 trove/guestagent/db/models.py:798
#, python-format
msgid "'%s' is not a valid user name."
msgstr ""

#: trove/guestagent/db/models.py:617
#, python-format
msgid "Bad args. name: %(name)s, password %(pass)s, deserializing %(deser)s."
msgstr ""

#: trove/guestagent/db/models.py:657
#, python-format
msgid "MongoDB user's name missing %s."
msgstr ""

#: trove/guestagent/db/models.py:662
msgid "MongoDB user missing database."
msgstr ""

#: trove/guestagent/db/models.py:666
msgid "MongoDB user missing username."
msgstr ""

#: trove/guestagent/db/models.py:710
#, python-format
msgid "MongoDB user name \"%s\" not in <database>.<username> format."
msgstr ""

#: trove/guestagent/db/models.py:730
#, python-format
msgid "Role %s is invalid."
msgstr ""

#: trove/guestagent/db/models.py:800
#, python-format
msgid "User name '%s' is too long. Max length = 16."
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:69
msgid "Innobackupex log file empty."
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:73
msgid "Innobackupex did not complete successfully."
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:87
#, python-format
msgid "Metadata for backup: %s."
msgstr ""

#: trove/guestagent/strategies/backup/experimental/couchbase_impl.py:90
msgid "All buckets are memcached.  Skipping backup."
msgstr ""

#: trove/guestagent/strategies/backup/experimental/mongo_impl.py:56
#, python-format
msgid ""
"Need more free space to run mongodump, estimated %(est_dump_size)s and "
"found %(avail)s bytes free "
msgstr ""

#: trove/guestagent/strategies/replication/mysql_base.py:79
msgid "Replication user retry count exceeded"
msgstr ""

#: trove/guestagent/strategies/replication/mysql_base.py:130
msgid "Exception enabling guest as replica"
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:40
msgid "Unable to determine binlog position (from file %(binlog_file))."
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:67
#, python-format
msgid "Setting read permissions on %s"
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:69
#, python-format
msgid "Reading log position from %s"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:91
msgid "Starting MySQL"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:93
msgid "Got a timeout launching mysqld_safe"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:109
msgid "Root password reset successfully."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:207
#: trove/guestagent/strategies/restore/experimental/redis_impl.py:47
#, python-format
msgid "Cleaning out restore location: %s."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:216
#: trove/guestagent/strategies/restore/mysql_impl.py:273
msgid "Innobackupex prepare finished successfully."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:288
#, python-format
msgid "Restoring parent: %(parent_location)s checksum: %(parent_checksum)s."
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:132
#, python-format
msgid ""
"Error saving data segment to swift. ETAG: %(tag)s Segment MD5: "
"%(checksum)s."
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:163
#, python-format
msgid "Error saving data to swift. Manifest ETAG: %(tag)s Swift MD5: %(checksum)s"
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:180
#, python-format
msgid ""
"Original checksum: %(original)s does not match the current checksum: "
"%(current)s"
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:237
#, python-format
msgid "Writing metadata: %s"
msgstr ""

#: trove/instance/models.py:571
msgid "Detach replicas before deleting replica source."
msgstr ""

#: trove/instance/models.py:746
#, python-format
msgid "Cannot create a replica of a replica %(id)s."
msgstr ""

#: trove/instance/models.py:762
#, python-format
msgid "Cannot create a replica of %(id)s as that instance could not be found."
msgstr ""

#: trove/instance/models.py:767
#, python-format
msgid ""
"Replica count only valid when creating replicas. Cannot create %(count)d "
"instances."
msgstr ""

#: trove/instance/models.py:880
#, python-format
msgid "The new flavor id must be different than the current flavor id of '%s'."
msgstr ""

#: trove/instance/models.py:912
#, python-format
msgid "The new volume 'size' must be larger than the current volume size of '%s'."
msgstr ""

#: trove/instance/models.py:920
#, python-format
msgid "Instance %s has no volume."
msgstr ""

#: trove/instance/models.py:955 trove/instance/models.py:963
#, python-format
msgid "Instance %s is not a replica."
msgstr ""

#: trove/instance/models.py:980
#, python-format
msgid "Instance %s is not a replica source."
msgstr ""

#: trove/instance/models.py:986
#, python-format
msgid "Replica Source %s cannot be ejected as it has a current heartbeat"
msgstr ""

#: trove/instance/models.py:1023
#, python-format
msgid ""
"Instance %(instance_id)s is not currently available for an action to be "
"performed (status was %(action_status)s)."
msgstr ""

#: trove/quota/quota.py:311
#, python-format
msgid "Failed to commit reservations %(reservations)s"
msgstr ""

#: trove/quota/quota.py:324
#, python-format
msgid "Failed to roll back reservations %(reservations)s"
msgstr ""

#: trove/taskmanager/manager.py:112
#, python-format
msgid ""
"promote-to-replica-source: Unable to migrate replica %(slave)s from old "
"replica source %(old_master)s to new source %(new_master)s."
msgstr ""

#: trove/taskmanager/manager.py:126
msgid "Exception demoting old replica source"
msgstr ""

#: trove/taskmanager/manager.py:134
#, python-format
msgid ""
"promote-to-replica-source %(id)s: The following replicas may not have "
"been switched: %(replicas)s"
msgstr ""

#: trove/taskmanager/manager.py:170
#, python-format
msgid "Replicas of %s not all replicating from same master"
msgstr ""

#: trove/taskmanager/manager.py:196
#, python-format
msgid ""
"eject-replica-source: Unable to migrate replica %(slave)s from old "
"replica source %(old_master)s to new source %(new_master)s."
msgstr ""

#: trove/taskmanager/manager.py:212
#, python-format
msgid ""
"eject-replica-source %(id)s: The following replicas may not have been "
"switched: %(replicas)s"
msgstr ""

#: trove/taskmanager/manager.py:291
#, python-format
msgid "Could not create replica %(num)d of %(count)d."
msgstr ""

#: trove/taskmanager/manager.py:319
msgid "Cannot create multiple non-replica instances."
msgstr ""

#: trove/taskmanager/models.py:246
msgid "Timeout for all instance service statuses to become ready."
msgstr ""

#: trove/taskmanager/models.py:253
#, python-format
msgid "Some instances failed to become ready: %s"
msgstr ""

#: trove/taskmanager/models.py:322
#, python-format
msgid "Created instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:325
#, python-format
msgid ""
"Failed to create instance %s. Timeout waiting for instance to become "
"active. No usage create-event was sent."
msgstr ""

#: trove/taskmanager/models.py:330
#, python-format
msgid "Failed to send usage create-event for instance %s."
msgstr ""

#: trove/taskmanager/models.py:341
#, python-format
msgid "Creating instance %s."
msgstr ""

#: trove/taskmanager/models.py:353
#, python-format
msgid "Error creating security group for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:422
#, python-format
msgid "Error creating DNS entry for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:433
#, python-format
msgid "Error attaching instance %s as replica."
msgstr ""

#: trove/taskmanager/models.py:474
#, python-format
msgid "Unable to create replication snapshot record for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:508
#, python-format
msgid ""
"Error creating replication snapshot from instance %(source)s for new "
"replica %(replica)s."
msgstr ""

#: trove/taskmanager/models.py:524
#, python-format
msgid ""
"An error occurred while deleting a bad replication snapshot from instance"
" %(source)s."
msgstr ""

#: trove/taskmanager/models.py:545
#, python-format
msgid "Service status: %(status)s"
msgstr ""

#: trove/taskmanager/models.py:548
#, python-format
msgid "Service error description: %(desc)s"
msgstr ""

#: trove/taskmanager/models.py:556
#, python-format
msgid "Trove instance status: %(action)s"
msgstr ""

#: trove/taskmanager/models.py:559
#, python-format
msgid "Trove instance status description: %(text)s"
msgstr ""

#: trove/taskmanager/models.py:581
#, python-format
msgid "Service not active, status: %s"
msgstr ""

#: trove/taskmanager/models.py:587
#, python-format
msgid "Server not active, status: %s"
msgstr ""

#: trove/taskmanager/models.py:622
#, python-format
msgid "Error creating server and volume for instance %s"
msgstr ""

#: trove/taskmanager/models.py:727
#, python-format
msgid "Error occurred during Heat stack creation for instance %s."
msgstr ""

#: trove/taskmanager/models.py:758
#, python-format
msgid "Failed to create server for instance %s"
msgstr ""

#: trove/taskmanager/models.py:776
#, python-format
msgid "Failed to create volume for instance %s"
msgstr ""

#: trove/taskmanager/models.py:909
#, python-format
msgid ""
"Failed to create DNS entry for instance %(instance)s. Server status was "
"%(status)s)."
msgstr ""

#: trove/taskmanager/models.py:920
msgid "Creating dns entry..."
msgstr ""

#: trove/taskmanager/models.py:943
#, python-format
msgid ""
"Failed to create security group rules for instance %(instance_id)s: "
"Invalid port format - FromPort = %(from)s, ToPort = %(to)s"
msgstr ""

#: trove/taskmanager/models.py:1001
#, python-format
msgid "Error stopping the datastore before attempting to delete instance id %s."
msgstr ""

#: trove/taskmanager/models.py:1012
#, python-format
msgid "Error during delete compute server %s"
msgstr ""

#: trove/taskmanager/models.py:1021
#, python-format
msgid "Error during dns entry of instance %(id)s: %(ex)s"
msgstr ""

#: trove/taskmanager/models.py:1030
#, python-format
msgid ""
"Server %(server_id)s entered ERROR status when deleting instance "
"%(instance_id)s!"
msgstr ""

#: trove/taskmanager/models.py:1041
#, python-format
msgid ""
"Failed to delete instance %(instance_id)s: Timeout deleting compute "
"server %(server_id)s"
msgstr ""

#: trove/taskmanager/models.py:1051
#, python-format
msgid "Deleting volume %(v)s for instance: %(i)s."
msgstr ""

#: trove/taskmanager/models.py:1055
#, python-format
msgid "Error deleting volume of instance %(id)s."
msgstr ""

#: trove/taskmanager/models.py:1070
#, python-format
msgid ""
"Resizing volume for instance %(instance_id)s from %(old_size)s GB to "
"%(new_size)s GB."
msgstr ""

#: trove/taskmanager/models.py:1076
#, python-format
msgid "Resized volume for instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:1079
#, python-format
msgid ""
"Resizing instance %(instance_id)s from flavor %(old_flavor)s to "
"%(new_flavor)s."
msgstr ""

#: trove/taskmanager/models.py:1085
#, python-format
msgid "Resized instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:1088
#, python-format
msgid "Initiating migration to host %s."
msgstr ""

#: trove/taskmanager/models.py:1093
#, python-format
msgid "Initiating backup for instance %s."
msgstr ""

#: trove/taskmanager/models.py:1112
#, python-format
msgid "Failed to get replication snapshot from %s."
msgstr ""

#: trove/taskmanager/models.py:1126
#, python-format
msgid "Failed to detach replica %s."
msgstr ""

#: trove/taskmanager/models.py:1139
#, python-format
msgid "Failed to attach replica %s."
msgstr ""

#: trove/taskmanager/models.py:1218
#, python-format
msgid "Cannot reboot instance. DB status is %s."
msgstr ""

#: trove/taskmanager/models.py:1224
#, python-format
msgid "Rebooting instance %s."
msgstr ""

#: trove/taskmanager/models.py:1241
#, python-format
msgid "Rebooted instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:1243
#, python-format
msgid "Failed to reboot instance %(id)s: %(e)s"
msgstr ""

#: trove/taskmanager/models.py:1250
#, python-format
msgid "Initiating datastore restart on instance %s."
msgstr ""

#: trove/taskmanager/models.py:1254
#, python-format
msgid "Failed to initiate datastore restart on instance %s."
msgstr ""

#: trove/taskmanager/models.py:1324
#, python-format
msgid "Deleting backup %s."
msgstr ""

#: trove/taskmanager/models.py:1337
#, python-format
msgid "Error occurred when deleting from swift. Details: %s"
msgstr ""

#: trove/taskmanager/models.py:1345
#, python-format
msgid "Deleted backup %s successfully."
msgstr ""

#: trove/taskmanager/models.py:1365
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Setting service status to failed."
msgstr ""

#: trove/taskmanager/models.py:1375
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1383
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by mounting the volume and then "
"restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1392
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by attaching and mounting the volume "
"and then restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1500
#, python-format
msgid "Failed to get volume %(vol_id)s"
msgstr ""

#: trove/taskmanager/models.py:1514
#, python-format
msgid "Timeout trying to extend the volume %(vol_id)s for instance %(id)s"
msgstr ""

#: trove/taskmanager/models.py:1527
#, python-format
msgid ""
"Error encountered trying to verify extend for the volume %(vol_id)s for "
"instance %(id)s"
msgstr ""

#: trove/taskmanager/models.py:1574
#, python-format
msgid ""
"Failed to resize instance %(id)s volume for server %(server_id)s. The "
"instance must be in state %(state)s not %(inst_state)s."
msgstr ""

#: trove/taskmanager/models.py:1697
msgid "Exception during nova action."
msgstr ""

#: trove/taskmanager/models.py:1699
#, python-format
msgid "Reverting action for instance %s"
msgstr ""

#: trove/taskmanager/models.py:1705
msgid "Restarting datastore."
msgstr ""

#: trove/taskmanager/models.py:1708
msgid "Cannot restart datastore because Nova server status is not ACTIVE"
msgstr ""

#: trove/taskmanager/models.py:1711
#, python-format
msgid "Error resizing instance %s."
msgstr ""

#: trove/taskmanager/models.py:1773
msgid "Error sending reset_configuration call."
msgstr ""

#: trove/tests/db/migrations.py:74
#, python-format
msgid ""
"The following migration scripts are missing a downgrade implementation:\n"
"\t%s"
msgstr ""

#: trove/tests/fakes/nova.py:282
#, python-format
msgid "volume status = %s"
msgstr ""

#: trove/tests/fakes/nova.py:334
#, python-format
msgid "Couldn't find server id %(id)s, collection=%(db)s"
msgstr ""

#: trove/tests/fakes/nova.py:354
#, python-format
msgid "Simulated event ended, deleting server %s."
msgstr ""

#: trove/tests/fakes/nova.py:497
#, python-format
msgid "Couldn't find volume id %(id)s, collection=%(db)s"
msgstr ""

