# Translations template for trove.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the trove project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: trove 2015.1.dev48\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-13 06:10+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: trove/backup/models.py:97
#, python-format
msgid "Unable to create backup record for instance: %s"
msgstr ""

#: trove/backup/models.py:238
#, python-format
msgid "Backup %s cannot be deleted because it is running."
msgstr ""

#: trove/backup/models.py:288
#, python-format
msgid "Bad location for backup object: %s"
msgstr ""

#: trove/backup/service.py:57
#, python-format
msgid "Creating a backup for tenant %s"
msgstr ""

#: trove/backup/service.py:68
#, python-format
msgid "Deleting backup for tenant %(tenant_id)s ID: %(backup_id)s"
msgstr ""

#: trove/cluster/models.py:121
#, python-format
msgid "Setting task to NONE on cluster %s"
msgstr ""

#: trove/cluster/models.py:193
#: trove/common/strategies/cluster/experimental/mongodb/api.py:177
#, python-format
msgid ""
"This action cannot be performed on the cluster while the current cluster "
"task is '%s'."
msgstr ""

#: trove/cluster/service.py:56 trove/cluster/service.py:80
#: trove/cluster/service.py:91 trove/cluster/service.py:105
#: trove/cluster/service.py:116 trove/cluster/service.py:131
#: trove/extensions/account/service.py:35
#: trove/extensions/account/service.py:46
#: trove/extensions/mgmt/clusters/service.py:43
#: trove/extensions/mgmt/clusters/service.py:59
#: trove/extensions/mgmt/clusters/service.py:72
#: trove/extensions/mgmt/host/service.py:34
#: trove/extensions/mgmt/host/service.py:43
#: trove/extensions/mgmt/instances/service.py:50
#: trove/extensions/mgmt/instances/service.py:74
#: trove/extensions/mgmt/instances/service.py:152
#: trove/extensions/mgmt/instances/service.py:171
#: trove/extensions/mgmt/instances/service.py:183
#: trove/extensions/mgmt/quota/service.py:33
#: trove/extensions/mgmt/upgrade/service.py:35
#: trove/extensions/mgmt/volume/service.py:33
#: trove/extensions/mysql/service.py:46 trove/extensions/mysql/service.py:54
#: trove/extensions/mysql/service.py:76 trove/extensions/mysql/service.py:87
#: trove/extensions/mysql/service.py:100 trove/extensions/mysql/service.py:123
#: trove/extensions/mysql/service.py:140 trove/extensions/mysql/service.py:162
#: trove/extensions/mysql/service.py:210 trove/extensions/mysql/service.py:226
#: trove/extensions/mysql/service.py:241 trove/extensions/mysql/service.py:264
#: trove/extensions/mysql/service.py:275 trove/extensions/mysql/service.py:285
#, python-format
msgid ""
"req : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:57 trove/cluster/service.py:81
#: trove/cluster/service.py:106 trove/extensions/mgmt/clusters/service.py:60
#: trove/extensions/mgmt/host/service.py:45
#: trove/extensions/mgmt/instances/service.py:76
#: trove/extensions/mgmt/instances/service.py:154
#: trove/extensions/mgmt/instances/service.py:185
#, python-format
msgid ""
"id : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:59 trove/extensions/mgmt/clusters/service.py:74
#: trove/extensions/mgmt/clusters/service.py:94
#: trove/extensions/mgmt/configuration/service.py:80
#: trove/extensions/mgmt/configuration/service.py:107
#: trove/extensions/mgmt/host/instance/service.py:34
#: trove/extensions/mgmt/host/instance/service.py:52
#: trove/extensions/mgmt/instances/service.py:95
#: trove/extensions/mgmt/instances/service.py:118
#: trove/extensions/mgmt/quota/service.py:43 trove/instance/service.py:75
msgid "Invalid request body."
msgstr ""

#: trove/cluster/service.py:71
#, python-format
msgid "No action '%(action)s' supplied by strategy for manager '%(manager)s'"
msgstr ""

#: trove/cluster/service.py:92
#, python-format
msgid ""
"cluster_id : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:93
#, python-format
msgid ""
"instance_id : '%s'\n"
"\n"
msgstr ""

#: trove/cluster/service.py:132 trove/extensions/mysql/service.py:88
#: trove/extensions/mysql/service.py:276
#, python-format
msgid ""
"body : '%s'\n"
"\n"
msgstr ""

#: trove/cmd/manage.py:180
#, python-format
msgid "Possible wrong number of arguments supplied %s"
msgstr ""

#: trove/cmd/manage.py:183
msgid "Command failed, please check log for more info."
msgstr ""

#: trove/common/auth.py:65
#, python-format
msgid "Authorized tenant '%(tenant_id)s' request: %(request)s"
msgstr ""

#: trove/common/auth.py:69
#, python-format
msgid "User with tenant id %s cannot access this resource"
msgstr ""

#: trove/common/base_exception.py:102 trove/openstack/common/exception.py:104
msgid "Uncaught exception"
msgstr ""

#: trove/common/base_wsgi.py:112 trove/openstack/common/wsgi.py:114
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: trove/common/base_wsgi.py:373 trove/openstack/common/wsgi.py:375
msgid "Unsupported Content-Type"
msgstr ""

#: trove/common/base_wsgi.py:376 trove/openstack/common/wsgi.py:378
msgid "Malformed request body"
msgstr ""

#: trove/common/base_wsgi.py:662 trove/openstack/common/wsgi.py:664
msgid "Empty body provided in request"
msgstr ""

#: trove/common/base_wsgi.py:668 trove/openstack/common/wsgi.py:670
msgid "Unrecognized Content-Type provided in request"
msgstr ""

#: trove/common/base_wsgi.py:672 trove/openstack/common/wsgi.py:674
msgid "No Content-Type provided in request"
msgstr ""

#: trove/common/base_wsgi.py:678 trove/openstack/common/wsgi.py:680
msgid "Unable to deserialize body as provided Content-Type"
msgstr ""

#: trove/common/base_wsgi.py:728 trove/openstack/common/wsgi.py:730
msgid "cannot understand JSON"
msgstr ""

#: trove/common/base_wsgi.py:752 trove/openstack/common/wsgi.py:754
msgid "cannot understand XML"
msgstr ""

#: trove/common/debug_utils.py:103
#, python-format
msgid ""
"Can't connect to remote debug server. Continuing to work in standard "
"mode. Error: %s."
msgstr ""

#: trove/common/exception.py:56
#, python-format
msgid "Failed to save %(model_name)s because: %(error)s."
msgstr ""

#: trove/common/exception.py:61
msgid "Invalid RPC Connection Reuse."
msgstr ""

#: trove/common/exception.py:66 trove/common/exception.py:81
#, python-format
msgid "Resource %(uuid)s cannot be found."
msgstr ""

#: trove/common/exception.py:71
#, python-format
msgid "Capability '%(capability)s' cannot be found."
msgstr ""

#: trove/common/exception.py:76
#, python-format
msgid "Capability '%(capability)s' is disabled."
msgstr ""

#: trove/common/exception.py:86
#, python-format
msgid "User %(uuid)s cannot be found on the instance."
msgstr ""

#: trove/common/exception.py:91
#, python-format
msgid "Database %(uuid)s cannot be found on the instance."
msgstr ""

#: trove/common/exception.py:96
#, python-format
msgid "Cannot find compute instance %(server_id)s for instance %(instance_id)s."
msgstr ""

#: trove/common/exception.py:99
#, python-format
msgid "Resource %(instance_id)s can not be retrieved."
msgstr ""

#: trove/common/exception.py:104
#, python-format
msgid "DnsRecord with name= %(name)s not found."
msgstr ""

#: trove/common/exception.py:109
#, python-format
msgid "Datastore '%(datastore)s' cannot be found."
msgstr ""

#: trove/common/exception.py:114
#, python-format
msgid "Datastore version '%(version)s' cannot be found."
msgstr ""

#: trove/common/exception.py:119
msgid "Datastores cannot be found."
msgstr ""

#: trove/common/exception.py:124
#, python-format
msgid "Datastore '%(datastore)s' has no version '%(version)s'."
msgstr ""

#: trove/common/exception.py:129
#, python-format
msgid "Datastore version '%(version)s' is not active."
msgstr ""

#: trove/common/exception.py:134
msgid "Please specify datastore. Default datastore cannot be found."
msgstr ""

#: trove/common/exception.py:140
#, python-format
msgid "Default version for datastore '%(datastore)s' not found."
msgstr ""

#: trove/common/exception.py:145
#, python-format
msgid "Datastore manager %(datastore_manager)s cannot be found."
msgstr ""

#: trove/common/exception.py:150
#, python-format
msgid ""
"The '%(operation)s' operation is not supported for the '%(datastore)s' "
"datastore."
msgstr ""

#: trove/common/exception.py:156
#, python-format
msgid "Multiple matches found for '%(name)s', use an UUID to be more specific."
msgstr ""

#: trove/common/exception.py:162
msgid "The server rejected the request due to its size or rate."
msgstr ""

#: trove/common/exception.py:168
#, python-format
msgid "Quota exceeded for resources: %(overs)s."
msgstr ""

#: trove/common/exception.py:173
msgid "Instance volume quota exceeded."
msgstr ""

#: trove/common/exception.py:178
#, python-format
msgid "An error occurred communicating with the guest: %(original_message)s."
msgstr ""

#: trove/common/exception.py:184
msgid "Timeout trying to connect to the Guest Agent."
msgstr ""

#: trove/common/exception.py:189
msgid ""
"The server could not comply with the request since it is either malformed"
" or otherwise incorrect."
msgstr ""

#: trove/common/exception.py:195
#, python-format
msgid "Required element/key - %(key)s was not specified."
msgstr ""

#: trove/common/exception.py:200
#, python-format
msgid "A database with the name \"%(name)s\" already exists."
msgstr ""

#: trove/common/exception.py:205
#, python-format
msgid "A user with the name \"%(name)s\" already exists."
msgstr ""

#: trove/common/exception.py:210
msgid ""
"A configuration group cannot be deleted if it is associated with one or "
"more non-terminated instances. Detach the configuration group from all "
"non-terminated instances and please try again."
msgstr ""

#: trove/common/exception.py:218
msgid "Unable to process the contained request."
msgstr ""

#: trove/common/exception.py:223
msgid "No change was requested in the size of the instance."
msgstr ""

#: trove/common/exception.py:228
msgid "Cannot find the volumes attached to compute instance %(server_id)."
msgstr ""

#: trove/common/exception.py:234
msgid "Failed to create a volume in Nova."
msgstr ""

#: trove/common/exception.py:239
msgid "Volume size was not specified."
msgstr ""

#: trove/common/exception.py:244
#, python-format
msgid "Local storage not specified in flavor ID: %(flavor)s."
msgstr ""

#: trove/common/exception.py:249
msgid "Local storage support is not enabled."
msgstr ""

#: trove/common/exception.py:254
msgid "Volume support is not enabled."
msgstr ""

#: trove/common/exception.py:259
#, python-format
msgid "Replication is not supported for the '%(datastore)s' datastore."
msgstr ""

#: trove/common/exception.py:265
#, python-format
msgid ""
"An error occurred communicating with the task manager: "
"%(original_message)s."
msgstr ""

#: trove/common/exception.py:271
#, python-format
msgid "Value could not be converted: %(msg)s."
msgstr ""

#: trove/common/exception.py:276
msgid "Polling request timed out."
msgstr ""

#: trove/common/exception.py:281
msgid "User does not have admin privileges."
msgstr ""

#: trove/common/exception.py:286
#, python-format
msgid "The following values are invalid: %(errors)s."
msgstr ""

#: trove/common/exception.py:291
msgid "Not Found."
msgstr ""

#: trove/common/exception.py:296
msgid "Failed to update instances."
msgstr ""

#: trove/common/exception.py:301
msgid "Config file not found."
msgstr ""

#: trove/common/exception.py:306
msgid "Paste app not found."
msgstr ""

#: trove/common/exception.py:310
msgid "Quota could not be found."
msgstr ""

#: trove/common/exception.py:314
#, python-format
msgid "Quota for tenant %(tenant_id)s could not be found."
msgstr ""

#: trove/common/exception.py:318
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: trove/common/exception.py:322
msgid "Unable to upload Backup to swift."
msgstr ""

#: trove/common/exception.py:326
msgid "Unable to download Backup from swift"
msgstr ""

#: trove/common/exception.py:330
msgid "Unable to create Backup."
msgstr ""

#: trove/common/exception.py:334
msgid "Unable to update Backup table in database."
msgstr ""

#: trove/common/exception.py:339 trove/extensions/security_group/models.py:59
msgid "Failed to create Security Group."
msgstr ""

#: trove/common/exception.py:344
msgid "Failed to delete Security Group."
msgstr ""

#: trove/common/exception.py:349
msgid "Failed to create Security Group Rule."
msgstr ""

#: trove/common/exception.py:354
msgid "Failed to delete Security Group Rule."
msgstr ""

#: trove/common/exception.py:359
#, python-format
msgid ""
"Error creating security group rules. Malformed port(s). Port must be an "
"integer. FromPort = %(from)s greater than ToPort = %(to)s."
msgstr ""

#: trove/common/exception.py:366
#, python-format
msgid ""
"Unable to create instance because backup %(backup_id)s is not completed. "
"Actual state: %(state)s."
msgstr ""

#: trove/common/exception.py:371
#, python-format
msgid "Backup file in %(location)s was not found in the object storage."
msgstr ""

#: trove/common/exception.py:376
#, python-format
msgid ""
"The datastore from which the backup was taken, %(datastore1)s, does not "
"match the destination datastore of %(datastore2)s."
msgstr ""

#: trove/common/exception.py:382
#, python-format
msgid "Swift account not accessible for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:386
#, python-format
msgid "Swift is disabled for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:390
#, python-format
msgid ""
"The request indicates that user %(user)s should have access to database "
"%(database)s, but database %(database)s is not included in the initial "
"databases list."
msgstr ""

#: trove/common/exception.py:396
msgid ""
"Two or more databases share the same name in the initial databases list. "
"Please correct the names or remove the duplicate entries."
msgstr ""

#: trove/common/exception.py:402
msgid ""
"Two or more users share the same name and host in the initial users list."
" Please correct the names or remove the duplicate entries."
msgstr ""

#: trove/common/exception.py:408
#, python-format
msgid ""
"Current Swift object checksum does not match original checksum for backup"
" %(backup_id)s."
msgstr ""

#: trove/common/exception.py:413
#, python-format
msgid "%(key)s is not a supported configuration parameter."
msgstr ""

#: trove/common/exception.py:417
#, python-format
msgid "No configuration parser found for datastore %(datastore_manager)s."
msgstr ""

#: trove/common/exception.py:422
#, python-format
msgid ""
"Datastore Version on Configuration %(config_datastore_version)s does not "
"match the Datastore Version on the instance "
"%(instance_datastore_version)s."
msgstr ""

#: trove/common/exception.py:429
#, python-format
msgid ""
"%(parameter_name)s parameter can no longer be set as of "
"%(parameter_deleted_at)s."
msgstr ""

#: trove/common/exception.py:434
#, python-format
msgid ""
"%(parameter_name)s parameter already exists for datastore version "
"%(datastore_version)s."
msgstr ""

#: trove/common/exception.py:439
#, python-format
msgid ""
"Instance %(instance_id)s already has a Configuration Group attached: "
"%(configuration_id)s."
msgstr ""

#: trove/common/exception.py:444
#, python-format
msgid ""
"The operation you have requested cannot be executed because the instance "
"status is currently: %(status)s."
msgstr ""

#: trove/common/exception.py:450
#, python-format
msgid ""
"Endpoint not found for service_type=%(service_type)s, "
"endpoint_type=%(endpoint_type)s, endpoint_region=%(endpoint_region)s."
msgstr ""

#: trove/common/exception.py:457
msgid "Empty catalog."
msgstr ""

#: trove/common/exception.py:461
#, python-format
msgid ""
"Instance with replication strategy %(guest_strategy)s cannot replicate "
"from instance with replication strategy %(replication_strategy)s."
msgstr ""

#: trove/common/exception.py:467
#, python-format
msgid ""
"The target instance has only %(slave_volume_size)sG free, but the "
"replication snapshot contains %(dataset_size)sG of data."
msgstr ""

#: trove/common/exception.py:473
msgid "The replica source cannot be deleted without detaching the replicas."
msgstr ""

#: trove/common/exception.py:478
#, python-format
msgid "Cluster '%(cluster)s' cannot be found."
msgstr ""

#: trove/common/exception.py:482
msgid "The flavor for each instance in a cluster must be the same."
msgstr ""

#: trove/common/exception.py:486
msgid "A volume size is required for each instance in the cluster."
msgstr ""

#: trove/common/exception.py:490
msgid "The volume size for each instance in a cluster must be the same."
msgstr ""

#: trove/common/exception.py:495
#, python-format
msgid ""
"The number of instances for your initial cluster must be "
"%(num_instances)s."
msgstr ""

#: trove/common/exception.py:500
msgid "Operation not supported for instances that are part of a cluster."
msgstr ""

#: trove/common/exception.py:505
#, python-format
msgid "Operation not allowed for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:509
#, python-format
msgid "Clusters not supported for %(datastore)s-%(datastore_version)s."
msgstr ""

#: trove/common/exception.py:514
#, python-format
msgid ""
"Backup is too large for given flavor or volume. Backup size: "
"%(backup_size)s GBs. Available size: %(disk_size)s GBs."
msgstr ""

#: trove/common/extensions.py:203
#, python-format
msgid "Extension with alias %s does not exist"
msgstr ""

#: trove/common/extensions.py:400
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: trove/common/limits.py:88
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: trove/common/limits.py:212
msgid "This request was rate-limited."
msgstr ""

#: trove/common/template.py:134
#, python-format
msgid "Missing heat template for %(s_datastore_manager)s."
msgstr ""

#: trove/common/utils.py:226
#, python-format
msgid ""
"Command '%(cmd)s' failed. %(description)s Exit code: %(exit_code)s\n"
"stderr: %(stderr)s\n"
"stdout: %(stdout)s"
msgstr ""

#: trove/common/utils.py:235
msgid "Got a timeout but not the one expected."
msgstr ""

#: trove/common/utils.py:238
#, python-format
msgid ""
"Time out after waiting %(time)s seconds when running proc: %(args)s "
"%(kwargs)s."
msgstr ""

#: trove/common/wsgi.py:145
msgid "version not supported"
msgstr ""

#: trove/common/wsgi.py:304
msgid "Unserializable result detected."
msgstr ""

#: trove/common/wsgi.py:529
msgid "Invalid service catalog json."
msgstr ""

#: trove/common/wsgi.py:574
#, python-format
msgid "Caught error: %s."
msgstr ""

#: trove/common/rpc/service.py:80
msgid "Failed to stop RPC server before shutdown. "
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:132
msgid "Timeout for all instance service statuses to become ready."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:139
#, python-format
msgid "Some instances failed to become ready: %s"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:165
msgid "error adding members"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:179
msgid "error adding shard"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:230
msgid "error adding config servers"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:253
msgid "timeout for building cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:304
msgid "timeout for building shard."
msgstr ""

#: trove/conductor/manager.py:50
#, python-format
msgid "[Instance %s] sent field not present. Cannot compare."
msgstr ""

#: trove/conductor/manager.py:80
#, python-format
msgid "[Instance %s] Rec'd message is older than last seen. Discarding."
msgstr ""

#: trove/conductor/manager.py:113
#, python-format
msgid ""
"[Instance: %(instance)s] Backup IDs mismatch! Expected %(expected)s, "
"found %(found)s"
msgstr ""

#: trove/conductor/manager.py:122
#, python-format
msgid ""
"[Instance: %(instance)s] Backup instance IDs mismatch! Expected "
"%(expected)s, found %(found)s"
msgstr ""

#: trove/configuration/models.py:141
#, python-format
msgid "Configuration group with ID %s could not be found."
msgstr ""

#: trove/configuration/service.py:90
#, python-format
msgid ""
"Creating configuration group on tenant %(tenant_id)s with name: "
"%(cfg_name)s"
msgstr ""

#: trove/configuration/service.py:122
#, python-format
msgid "Deleting configuration group %(cfg_id)s on tenant: %(tenant_id)s"
msgstr ""

#: trove/configuration/service.py:138
#, python-format
msgid "Updating configuration group %(cfg_id)s for tenant id %(tenant_id)s"
msgstr ""

#: trove/configuration/service.py:198
msgid "Validating configuration values"
msgstr ""

#: trove/configuration/service.py:209
#, python-format
msgid ""
"Configuration groups are not supported for this datastore: %(name)s "
"%(version)s"
msgstr ""

#: trove/configuration/service.py:220
#, python-format
msgid ""
"The configuration parameter %(key)s is not supported for this datastore: "
"%(name)s %(version)s."
msgstr ""

#: trove/configuration/service.py:233
#, python-format
msgid ""
"The value provided for the configuration parameter %(key)s is not of type"
" %(type)s."
msgstr ""

#: trove/configuration/service.py:242
msgid ""
"Invalid or unsupported min value defined in the configuration-parameters "
"configuration file. Expected integer."
msgstr ""

#: trove/configuration/service.py:248
#, python-format
msgid ""
"The value for the configuration parameter %(key)s is less than the "
"minimum allowed: %(min)s"
msgstr ""

#: trove/configuration/service.py:256
msgid ""
"Invalid or unsupported max value defined in the configuration-parameters "
"configuration file. Expected integer."
msgstr ""

#: trove/configuration/service.py:262
#, python-format
msgid ""
"The value for the configuration parameter %(key)s is greater than the "
"maximum allowed: %(max)s"
msgstr ""

#: trove/configuration/service.py:276
msgid ""
"Invalid or unsupported type defined in the configuration-parameters "
"configuration file."
msgstr ""

#: trove/configuration/service.py:286
#, python-format
msgid "%s is not a supported configuration parameter."
msgstr ""

#: trove/datastore/models.py:209
#, python-format
msgid ""
"Somehow we got a datastore version capability without a parent, that "
"shouldn't happen. %s"
msgstr ""

#: trove/datastore/models.py:252
#, python-format
msgid "Capability Override not found for capability %s"
msgstr ""

#: trove/db/models.py:98
#, python-format
msgid "%(s_name)s Not Found"
msgstr ""

#: trove/db/models.py:103
#, python-format
msgid "Tenant %(s_tenant)s tried to access %(s_name)s, owned by %(s_owner)s."
msgstr ""

#: trove/db/models.py:109
#, python-format
msgid "Tenant %(s_tenant)s cannot access %(s_name)s"
msgstr ""

#: trove/db/sqlalchemy/session.py:81
#, python-format
msgid "Creating SQLAlchemy engine with args: %s"
msgstr ""

#: trove/dns/models.py:68
#, python-format
msgid "%s Not Found"
msgstr ""

#: trove/extensions/account/service.py:36
#, python-format
msgid "Showing account information for '%(account)s' to '%(tenant)s'"
msgstr ""

#: trove/extensions/account/service.py:47
#, python-format
msgid "Showing all accounts with instances for '%s'"
msgstr ""

#: trove/extensions/mgmt/clusters/service.py:84
#: trove/extensions/mgmt/host/instance/service.py:42
#: trove/extensions/mgmt/instances/service.py:108
msgid "Only one action can be specified per request."
msgstr ""

#: trove/extensions/mgmt/clusters/service.py:88
#, python-format
msgid "Invalid cluster action: %s."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:61
msgid "max_size is required for integer data type."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:64
msgid "min_size is required for integer data type."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:70
msgid "max_size must be greater than or equal to min_size."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:76
msgid "Creating configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:103
msgid "Updating configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:128
msgid "Deleting configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:134
#, python-format
msgid "Parameter %s does not exist in the database."
msgstr ""

#: trove/extensions/mgmt/host/models.py:75
#, python-format
msgid "Compute Instance ID found with no associated RD instance: %s."
msgstr ""

#: trove/extensions/mgmt/host/models.py:89
#, python-format
msgid "Unable to update instance: %s."
msgstr ""

#: trove/extensions/mgmt/host/models.py:92
#, python-format
msgid "Failed to update instances: %s."
msgstr ""

#: trove/extensions/mgmt/host/service.py:35
#, python-format
msgid "Indexing a host for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/host/service.py:44
#, python-format
msgid "Showing a host for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/host/instance/service.py:46
#, python-format
msgid "Invalid host action: %s"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:51
#, python-format
msgid "Indexing a database instance for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:75
#, python-format
msgid "Showing a database instance for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:112
#, python-format
msgid "Invalid instance action: %s"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:153
#, python-format
msgid "Showing root history for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:172
#, python-format
msgid "Showing hardware info for instance '%s'"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:184
#, python-format
msgid "Showing a instance diagnostics for instance '%s'"
msgstr ""

#: trove/extensions/mgmt/quota/service.py:34
#, python-format
msgid "Indexing quota info for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/upgrade/service.py:36
msgid "Sending upgrade notification"
msgstr ""

#: trove/extensions/mgmt/upgrade/service.py:37
#, python-format
msgid "Admin tenant_id: %s"
msgstr ""

#: trove/extensions/mgmt/volume/service.py:34
#, python-format
msgid "Indexing storage info for tenant '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:45
#, python-format
msgid "Getting root enabled for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:53
#, python-format
msgid "Enabling root for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:75
#, python-format
msgid "Listing users for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:86
#, python-format
msgid "Creating users for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:99
#, python-format
msgid "Deleting user for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:122
#, python-format
msgid "Showing a user for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:139
#, python-format
msgid "Updating user attributes for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:161
#, python-format
msgid "Updating user passwords for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:209
#, python-format
msgid "Showing user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:216 trove/extensions/mysql/service.py:231
#: trove/extensions/mysql/service.py:246
#, python-format
msgid "No such user: %(user)s "
msgstr ""

#: trove/extensions/mysql/service.py:225
#, python-format
msgid "Granting user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:240
#, python-format
msgid "Revoking user access for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:263
#, python-format
msgid "Listing schemas for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:274
#, python-format
msgid "Creating schema for instance '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:284
#, python-format
msgid "Deleting schema for instance '%s'"
msgstr ""

#: trove/extensions/security_group/models.py:69
#: trove/extensions/security_group/models.py:166
msgid "Failed to create remote security group."
msgstr ""

#: trove/extensions/security_group/models.py:76 trove/taskmanager/models.py:611
#, python-format
msgid "Security Group for %s"
msgstr ""

#: trove/extensions/security_group/models.py:114
#: trove/extensions/security_group/models.py:180
msgid "Failed to delete security group."
msgstr ""

#: trove/extensions/security_group/models.py:130
#, python-format
msgid "Security Group with id: %(id)s already had been deleted"
msgstr ""

#: trove/extensions/security_group/models.py:214
msgid "Security Group does not have id defined!"
msgstr ""

#: trove/extensions/security_group/service.py:129
#, python-format
msgid "Create Security Group Rules Required field(s) - %s"
msgstr ""

#: trove/guestagent/api.py:67 trove/guestagent/api.py:70
#: trove/guestagent/api.py:81 trove/guestagent/api.py:84
#, python-format
msgid "Error calling %s"
msgstr ""

#: trove/guestagent/dbaas.py:81
msgid "Error getting volume stats."
msgstr ""

#: trove/guestagent/models.py:86
#, python-format
msgid "Error finding instance %s"
msgstr ""

#: trove/guestagent/pkg.py:121
#, python-format
msgid "Error removing conflict %(package)s"
msgstr ""

#: trove/guestagent/pkg.py:220
#, python-format
msgid "Unexpected output from rpm command. (%(output)s)"
msgstr ""

#: trove/guestagent/pkg.py:243
msgid "Error fixing dpkg"
msgstr ""

#: trove/guestagent/pkg.py:355
msgid "Error updating the apt sources"
msgstr ""

#: trove/guestagent/volume.py:64
msgid "Error getting device status"
msgstr ""

#: trove/guestagent/volume.py:65
#, python-format
msgid "InvalidDevicePath(path=%s)"
msgstr ""

#: trove/guestagent/volume.py:81
msgid "Device path at {0} did not seem to be {1}."
msgstr ""

#: trove/guestagent/volume.py:85
msgid "Volume was not formatted."
msgstr ""

#: trove/guestagent/volume.py:128
msgid "Error resizing file system."
msgstr ""

#: trove/guestagent/volume.py:129
#, python-format
msgid "Error resizing the filesystem: %s"
msgstr ""

#: trove/guestagent/volume.py:142
#, python-format
msgid "Device %(device)s is already mounted in %(mount_point)s. Unmounting now."
msgstr ""

#: trove/guestagent/volume.py:155
msgid "Error retrieving mount points"
msgstr ""

#: trove/guestagent/volume.py:156
#, python-format
msgid "Could not obtain a list of mount points for device: %s"
msgstr ""

#: trove/guestagent/backup/backupagent.py:120
#, python-format
msgid "Error saving backup: %(backup_id)s."
msgstr ""

#: trove/guestagent/backup/backupagent.py:124
#, python-format
msgid "Completed backup %(backup_id)s."
msgstr ""

#: trove/guestagent/backup/backupagent.py:180
#, python-format
msgid "Error restoring backup %(id)s."
msgstr ""

#: trove/guestagent/datastore/service.py:78
#, python-format
msgid "Updating database status to %s."
msgstr ""

#: trove/guestagent/datastore/service.py:129
msgid ""
"DB server is not installed or is in restart mode, so for now we'll skip "
"determining the status of DB on this instance."
msgstr ""

#: trove/guestagent/datastore/service.py:153
msgid "Timeout while waiting for database status to change."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/manager.py:65
msgid "Setting status of instance to BUILDING."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/manager.py:100
msgid "Completed setup of Cassandra database instance."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:47
msgid "Preparing Guest as a Cassandra Server"
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:68
msgid "Error while initiating storage structure."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:76
msgid "Error starting Cassandra"
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:88
msgid "Error killing Cassandra start command."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:90
msgid "Could not start Cassandra"
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:102
#: trove/guestagent/datastore/experimental/cassandra/service.py:104
msgid "Could not stop Cassandra."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:109
msgid "Restarting Cassandra server."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:147
#, python-format
msgid "Exception generating Cassandra configuration %s."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:154
msgid "Wrote new Cassandra configuration."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:203
msgid "Starting Cassandra with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:207
#, python-format
msgid "Cannot execute start_db_with_conf_changes because Cassandra state == %s."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:233
msgid "Error getting Cassandra status"
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/manager.py:89
msgid "Completed setup of Couchbase database instance."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/manager.py:173
#, python-format
msgid "Restoring database from backup %s"
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/manager.py:178
#, python-format
msgid "Error performing restore from backup %s"
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/manager.py:183
msgid "Restored database successfully"
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:60
msgid "Preparing Guest as Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:69
msgid "Couchbase Server change data dir path."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:89
msgid "Couchbase Server initial setup finished."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:91
msgid "Error performing initial Couchbase setup."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:120
msgid "Enabling Couchbase Server on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:127
msgid "Command to enable Couchbase Server on boot not found."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:160
#: trove/guestagent/datastore/experimental/couchbase/service.py:162
msgid "Could not stop Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:165
msgid "Restarting Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:177
msgid "Starting Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:193
msgid "Start up of Couchbase Server failed."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:197
msgid "Error killing Couchbase start command."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:205
msgid "Starting Couchbase with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:206
#: trove/guestagent/datastore/experimental/mongodb/service.py:141
#, python-format
msgid ""
"Configuration contents:\n"
" %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:208
#, python-format
msgid "Cannot start Couchbase with configuration changes. Couchbase state == %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:238
msgid "Error getting the Couchbase status."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:244
msgid "Error getting the root password from the native Couchbase config file."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:258
msgid ""
"Error getting Couchbase status using the password parsed from the native "
"Couchbase config file."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:328
#, python-format
msgid "An error occurred in saving password (%(errno)s). %(strerror)s."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/manager.py:96
#, python-format
msgid "Bad cluster configuration; instance type given as %s."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/manager.py:102
msgid "Completed setup of MongoDB database instance."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:46
msgid "Preparing Guest as MongoDB."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:50
msgid "Finished installing MongoDB server."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:61
msgid "Enabling MongoDB on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:67
#: trove/guestagent/datastore/experimental/mongodb/service.py:89
msgid "MongoDB service is not discovered."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:70
msgid "Disabling MongoDB on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:79
msgid "Stopping MongoDB."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:94
msgid "Could not stop MongoDB."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:96
msgid "Could not stop MongoDB"
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:99
msgid "Restarting MongoDB."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:108
msgid "Starting MongoDB."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:124
msgid "Start up of MongoDB failed."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:134
msgid "Error killing MongoDB start command."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:140
msgid "Starting MongoDB with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:143
#, python-format
msgid "Cannot start MongoDB with configuration changes. MongoDB state == %s."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:151
#: trove/guestagent/datastore/experimental/redis/service.py:256
#: trove/guestagent/datastore/mysql/service.py:987
#: trove/guestagent/datastore/mysql/service.py:993
msgid "Resetting configuration."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:155
msgid "Updating configuration contents."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:171
msgid "Updating MongoDB config."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:173
#: trove/guestagent/datastore/experimental/mongodb/service.py:243
#, python-format
msgid "Writing %s."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:178
#: trove/guestagent/datastore/experimental/mongodb/service.py:248
#, python-format
msgid "Moving %(a)s to %(b)s."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:196
#, python-format
msgid "Config file %s not found."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:219
msgid "Error clearing storage."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:236
msgid "Rewriting configuration."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:377
#, python-format
msgid "Process execution %s."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:380
#, python-format
msgid "OS Error %s."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/access.py:37
msgid "{guest_id}: Granting user ({user}) access to database ({database})."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/access.py:60
msgid "{guest_id}: Revoking user ({user}) access to database({database})."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/config.py:114
msgid "{guest_id}: Going into restart mode for config file changes."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/config.py:124
msgid "{guest_id}: Ending restart mode for config file changes."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/database.py:44
msgid "{guest_id}: Creating database {name}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/database.py:66
msgid "{guest_id}: Dropping database {name}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/install.py:53
msgid "{guest_id}: Installing ({packages})."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/process.py:37
msgid "{guest_id}: Starting database engine with command ({command})."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/process.py:55
msgid "Error enabling PostgreSQL start on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/process.py:65
msgid "Error disabling PostgreSQL start on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/process.py:74
msgid "{guest_id}: Stopping database engine with command ({command})."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/process.py:88
msgid "{guest_id}: Restarting database engine."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:52
msgid "{guest_id}: Creating user {name} with password {password}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:135
msgid "{guest_id}: Dropping user {name}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:189
msgid "{guest_id}: Changing password for {user} to {password}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:228
msgid "{guest_id}: Changing username for {old} to {new}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:243
msgid "{guest_id}: Regranting permissions from {old} to {new}."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/manager.py:99
msgid "Writing redis configuration."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/manager.py:102
msgid "Redis instance has been setup and configured."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/manager.py:104
msgid "Error setting up Redis instance."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:102
msgid "Redis Service Status is RUNNING."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:105
msgid "Process execution error on redis-cli."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:112
msgid "Redis Service Status is BLOCKED."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:118
msgid "Redis Service Status is CRASHED."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:121
msgid "Redis Service Status is SHUTDOWN."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:145
msgid "Preparing Guest as Redis Server."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:147
msgid "Installing Redis."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:149
msgid "Redis installed completely."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:179
msgid "Enabling Redis on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:186
msgid "Command to enable Redis on boot not found."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:193
msgid "Disabling Redis on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:207
msgid "Stopping redis."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:216
msgid "Could not stop Redis."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:245
msgid "Starting redis with conf changes."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:250
msgid "Initiating config."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:263
msgid "Starting redis."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:274
msgid "Start up of redis failed."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:281
msgid "Error killing stalled redis start command."
msgstr ""

#: trove/guestagent/datastore/mysql/manager.py:102
#, python-format
msgid "Restoring database from backup %s."
msgstr ""

#: trove/guestagent/datastore/mysql/manager.py:106
#, python-format
msgid "Error performing restore from backup %s."
msgstr ""

#: trove/guestagent/datastore/mysql/manager.py:110
msgid "Restored database successfully."
msgstr ""

#: trove/guestagent/datastore/mysql/manager.py:159
msgid "Completed setup of MySQL database instance."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:88
msgid "/root/.mysql_secret does not exist."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:98
msgid "Cannot change mysql password."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:171
msgid "MySQL Service Status is RUNNING."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:174
msgid "Failed to get database status."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:181
#, python-format
msgid "MySQL Service Status %(pid)s is BLOCKED."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:185
msgid "Process execution failed."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:190
msgid "MySQL Service Status is CRASHED."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:193
msgid "MySQL Service Status is SHUTDOWN."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:368
msgid "Error Getting user information"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:369
#, python-format
msgid "Username %(user)s is not valid: %(reason)s"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:401
msgid "Error granting access"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:402
#, python-format
msgid "Grant access to %s is not allowed"
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:601
msgid "Preparing Guest as MySQL Server."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:610
msgid "Finished installing MySQL server."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:617
msgid "Generating admin password."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:634
msgid "Preserving root access from restore."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:667
msgid "Error enabling MySQL start on boot."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:677
msgid "Error disabling MySQL start on boot."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:681
msgid "Stopping MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:689
msgid "Error stopping MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:694
msgid "Could not stop MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:742
#, python-format
msgid "Unable to set %(key)s with value %(value)s."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:764
msgid "Wiping ib_logfiles."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:784
msgid "Writing my.cnf templates."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:812
msgid "Writing new temp overrides.cnf file."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:816
msgid "Moving overrides.cnf into correct location."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:820
msgid "Setting permissions on overrides.cnf."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:825
msgid "Removing overrides configuration file."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:830
msgid "Writing replication.cnf file."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:843
msgid "Removing replication configuration file."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:848
msgid "Granting Replication Slave privilege."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:859
msgid "Revoking Replication Slave privilege."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:886
#, python-format
msgid "Configuring replication from %s."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:908
msgid "Starting slave replication."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:915
msgid "Stopping slave replication."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:938
#, python-format
msgid "Replication is now %s."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:941
#, python-format
msgid "Replication is not %(status)s after %(max)d seconds."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:945
msgid "Starting MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:968
msgid "Start up of MySQL failed."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:974
msgid "Error killing stalled MySQL start command."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:980
msgid "Starting MySQL with conf changes."
msgstr ""

#: trove/guestagent/datastore/mysql/service.py:984
#, python-format
msgid "Cannot execute start_db_with_conf_changes because MySQL state == %s."
msgstr ""

#: trove/guestagent/db/models.py:308
#, python-format
msgid "%(val)s not a valid collation for charset %(char)s."
msgstr ""

#: trove/guestagent/db/models.py:314
#, python-format
msgid "'%s' not a valid collation."
msgstr ""

#: trove/guestagent/db/models.py:332
#, python-format
msgid "'%s' not a valid character set."
msgstr ""

#: trove/guestagent/db/models.py:344
#, python-format
msgid "'%s' is not a valid database name."
msgstr ""

#: trove/guestagent/db/models.py:346
#, python-format
msgid "Database name '%s' is too long. Max length = 64."
msgstr ""

#: trove/guestagent/db/models.py:403
#, python-format
msgid "'%s' is not a valid user name."
msgstr ""

#: trove/guestagent/db/models.py:405
#, python-format
msgid "User name '%s' is too long. Max length = 16."
msgstr ""

#: trove/guestagent/db/models.py:417
#, python-format
msgid "'%s' is not a valid password."
msgstr ""

#: trove/guestagent/db/models.py:440
#, python-format
msgid "'%s' is not a valid hostname."
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:66
msgid "Innobackupex log file empty."
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:70
msgid "Innobackupex did not complete successfully."
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:84
#, python-format
msgid "Metadata for backup: %s."
msgstr ""

#: trove/guestagent/strategies/backup/experimental/couchbase_impl.py:88
msgid "All buckets are memcached.  Skipping backup."
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:61
msgid "Unable to determine binlog position (from file %(binlog_file))."
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:93
msgid "Replication user retry count exceeded"
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:154
#, python-format
msgid "Setting read permissions on %s"
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:156
#, python-format
msgid "Reading log position from %s"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:88
msgid "Starting MySQL"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:90
msgid "Got a timeout launching mysqld_safe"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:106
msgid "Root password reset successfully."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:205
#, python-format
msgid "Cleaning out restore location: %s."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:216
#: trove/guestagent/strategies/restore/mysql_impl.py:275
msgid "Innobackupex prepare finished successfully."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:290
#, python-format
msgid "Restoring parent: %(parent_location)s checksum: %(parent_checksum)s."
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:131
#, python-format
msgid ""
"Error saving data segment to swift. ETAG: %(tag)s Segment MD5: "
"%(checksum)s."
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:162
#, python-format
msgid "Error saving data to swift. Manifest ETAG: %(tag)s Swift MD5: %(checksum)s"
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:179
#, python-format
msgid ""
"Original checksum: %(original)s does not match the current checksum: "
"%(current)s"
msgstr ""

#: trove/guestagent/strategies/storage/swift.py:236
#, python-format
msgid "Writing metadata: %s"
msgstr ""

#: trove/instance/models.py:557
msgid "Detach replicas before deleting replica source."
msgstr ""

#: trove/instance/models.py:719
#, python-format
msgid "Cannot create a replica of a replica %(id)s."
msgstr ""

#: trove/instance/models.py:723
#, python-format
msgid "Cannot create a replica of %(id)s as that instance could not be found."
msgstr ""

#: trove/instance/models.py:855
#, python-format
msgid "The new volume 'size' must be larger than the current volume size of '%s'."
msgstr ""

#: trove/instance/models.py:863
#, python-format
msgid "Instance %s has no volume."
msgstr ""

#: trove/instance/models.py:898
#, python-format
msgid "Instance %s is not a replica."
msgstr ""

#: trove/instance/models.py:928
#, python-format
msgid ""
"Instance %(instance_id)s is not currently available for an action to be "
"performed (status was %(action_status)s)."
msgstr ""

#: trove/openstack/common/excutils.py:64
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: trove/openstack/common/excutils.py:93
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: trove/openstack/common/gettextutils.py:301
msgid "Message objects do not support addition."
msgstr ""

#: trove/openstack/common/gettextutils.py:311
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: trove/openstack/common/log.py:298
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: trove/openstack/common/log.py:406
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: trove/openstack/common/log.py:467
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: trove/openstack/common/log.py:715
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: trove/openstack/common/periodic_task.py:97
#, python-format
msgid "Skipping %(full_task_name)s, %(ticks_to_skip)s ticks left until next run"
msgstr ""

#: trove/openstack/common/periodic_task.py:105
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr ""

#: trove/openstack/common/periodic_task.py:113
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: trove/openstack/common/policy.py:394
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr ""

#: trove/openstack/common/policy.py:404
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: trove/openstack/common/policy.py:679
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr ""

#: trove/openstack/common/sslutils.py:52
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: trove/openstack/common/sslutils.py:55
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: trove/openstack/common/sslutils.py:58
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: trove/openstack/common/sslutils.py:61
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: trove/openstack/common/sslutils.py:100
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: trove/openstack/common/strutils.py:125
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: trove/openstack/common/strutils.py:230
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: trove/openstack/common/strutils.py:239
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: trove/openstack/common/versionutils.py:90
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: trove/openstack/common/versionutils.py:94
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: trove/openstack/common/versionutils.py:98
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s."
msgstr ""

#: trove/openstack/common/versionutils.py:101
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s. It will not be superseded."
msgstr ""

#: trove/openstack/common/crypto/utils.py:29
msgid "An unknown error occurred in crypto utils."
msgstr ""

#: trove/openstack/common/crypto/utils.py:36
#, python-format
msgid "Block size of %(given)d is too big, max = %(maximum)d"
msgstr ""

#: trove/openstack/common/crypto/utils.py:45
#, python-format
msgid "Length of %(given)d is too long, max = %(maximum)d"
msgstr ""

#: trove/quota/quota.py:311
#, python-format
msgid "Failed to commit reservations %(reservations)s"
msgstr ""

#: trove/quota/quota.py:324
#, python-format
msgid "Failed to roll back reservations %(reservations)s"
msgstr ""

#: trove/taskmanager/models.py:207
msgid "timeout for instances to be marked as deleted."
msgstr ""

#: trove/taskmanager/models.py:251
#, python-format
msgid "Creating instance %s."
msgstr ""

#: trove/taskmanager/models.py:263
#, python-format
msgid "Error creating security group for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:334
#, python-format
msgid "Error creating DNS entry for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:350
#, python-format
msgid "Created instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:353
#, python-format
msgid ""
"Failed to create instance %s. Timeout waiting for instance to become "
"active. No usage create-event was sent."
msgstr ""

#: trove/taskmanager/models.py:358
#, python-format
msgid "Failed to send usage create-event for instance %s."
msgstr ""

#: trove/taskmanager/models.py:368
#, python-format
msgid "Error attaching instance %s as replica."
msgstr ""

#: trove/taskmanager/models.py:389
#, python-format
msgid "Unable to create replication snapshot record for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:406
#, python-format
msgid ""
"Error creating replication snapshot from instance %(source)s for new "
"replica %(replica)s."
msgstr ""

#: trove/taskmanager/models.py:420
#, python-format
msgid ""
"An error occurred while deleting a bad replication snapshot from instance"
" %(source)s."
msgstr ""

#: trove/taskmanager/models.py:441
#, python-format
msgid "Service status: %(status)s"
msgstr ""

#: trove/taskmanager/models.py:444
#, python-format
msgid "Service error description: %(desc)s"
msgstr ""

#: trove/taskmanager/models.py:452
#, python-format
msgid "Trove instance status: %(action)s"
msgstr ""

#: trove/taskmanager/models.py:455
#, python-format
msgid "Trove instance status description: %(text)s"
msgstr ""

#: trove/taskmanager/models.py:477
#, python-format
msgid "Service not active, status: %s"
msgstr ""

#: trove/taskmanager/models.py:483
#, python-format
msgid "Server not active, status: %s"
msgstr ""

#: trove/taskmanager/models.py:518
#, python-format
msgid "Error creating server and volume for instance %s"
msgstr ""

#: trove/taskmanager/models.py:623
#, python-format
msgid "Error occurred during Heat stack creation for instance %s."
msgstr ""

#: trove/taskmanager/models.py:654
#, python-format
msgid "Failed to create server for instance %s"
msgstr ""

#: trove/taskmanager/models.py:672
#, python-format
msgid "Failed to create volume for instance %s"
msgstr ""

#: trove/taskmanager/models.py:804
#, python-format
msgid ""
"Failed to create DNS entry for instance %(instance)s. Server status was "
"%(status)s)."
msgstr ""

#: trove/taskmanager/models.py:815
msgid "Creating dns entry..."
msgstr ""

#: trove/taskmanager/models.py:836
#, python-format
msgid ""
"Failed to create security group rules for instance %(instance_id)s: "
"Invalid port format - FromPort = %(from)s, ToPort = %(to)s"
msgstr ""

#: trove/taskmanager/models.py:894
#, python-format
msgid "Error stopping the datastore before attempting to delete instance id %s."
msgstr ""

#: trove/taskmanager/models.py:905
#, python-format
msgid "Error during delete compute server %s"
msgstr ""

#: trove/taskmanager/models.py:914
#, python-format
msgid "Error during dns entry of instance %(id)s: %(ex)s"
msgstr ""

#: trove/taskmanager/models.py:923
#, python-format
msgid ""
"Server %(server_id)s entered ERROR status when deleting instance "
"%(instance_id)s!"
msgstr ""

#: trove/taskmanager/models.py:934
#, python-format
msgid ""
"Failed to delete instance %(instance_id)s: Timeout deleting compute "
"server %(server_id)s"
msgstr ""

#: trove/taskmanager/models.py:944
#, python-format
msgid "Deleting volume %(v)s for instance: %(i)s."
msgstr ""

#: trove/taskmanager/models.py:948
#, python-format
msgid "Error deleting volume of instance %(id)s."
msgstr ""

#: trove/taskmanager/models.py:963
#, python-format
msgid ""
"Resizing volume for instance %(instance_id)s from %(old_size)s GB to "
"%(new_size)s GB."
msgstr ""

#: trove/taskmanager/models.py:969
#, python-format
msgid "Resized volume for instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:972
#, python-format
msgid ""
"Resizing instance %(instance_id)s from flavor %(old_flavor)s to "
"%(new_flavor)s."
msgstr ""

#: trove/taskmanager/models.py:978
#, python-format
msgid "Resized instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:981
#, python-format
msgid "Initiating migration to host %s."
msgstr ""

#: trove/taskmanager/models.py:986
#, python-format
msgid "Initiating backup for instance %s."
msgstr ""

#: trove/taskmanager/models.py:1000
#, python-format
msgid "Failed to get replication snapshot from %s."
msgstr ""

#: trove/taskmanager/models.py:1014
#, python-format
msgid "Failed to detach replica %s."
msgstr ""

#: trove/taskmanager/models.py:1037
#, python-format
msgid "Cannot reboot instance. DB status is %s."
msgstr ""

#: trove/taskmanager/models.py:1043
#, python-format
msgid "Rebooting instance %s."
msgstr ""

#: trove/taskmanager/models.py:1060
#, python-format
msgid "Rebooted instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:1062
#, python-format
msgid "Failed to reboot instance %(id)s: %(e)s"
msgstr ""

#: trove/taskmanager/models.py:1069
#, python-format
msgid "Initiating datastore restart on instance %s."
msgstr ""

#: trove/taskmanager/models.py:1073
#, python-format
msgid "Failed to initiate datastore restart on instance %s."
msgstr ""

#: trove/taskmanager/models.py:1079
#, python-format
msgid "Initiating datastore configurations update on instance %s."
msgstr ""

#: trove/taskmanager/models.py:1102
#, python-format
msgid "Failed to initiate datastore configurations update on instance %s."
msgstr ""

#: trove/taskmanager/models.py:1106
#, python-format
msgid ""
"Initiating configuration group %(config_id)s removal from instance "
"%(instance_id)s."
msgstr ""

#: trove/taskmanager/models.py:1221
#, python-format
msgid "Deleting backup %s."
msgstr ""

#: trove/taskmanager/models.py:1234
#, python-format
msgid "Error occurred when deleting from swift. Details: %s"
msgstr ""

#: trove/taskmanager/models.py:1242
#, python-format
msgid "Deleted backup %s successfully."
msgstr ""

#: trove/taskmanager/models.py:1262
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Setting service status to failed."
msgstr ""

#: trove/taskmanager/models.py:1271
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1279
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by mounting the volume and then "
"restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1288
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by attaching and mounting the volume "
"and then restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1394
#, python-format
msgid "Failed to get volume %(vol_id)s"
msgstr ""

#: trove/taskmanager/models.py:1408
#, python-format
msgid "Timeout trying to extend the volume %(vol_id)s for instance %(id)s"
msgstr ""

#: trove/taskmanager/models.py:1421
#, python-format
msgid ""
"Error encountered trying to verify extend for the volume %(vol_id)s for "
"instance %(id)s"
msgstr ""

#: trove/taskmanager/models.py:1468
#, python-format
msgid ""
"Failed to resize instance %(id)s volume for server %(server_id)s. The "
"instance must be in state %(state)s not %(inst_state)s."
msgstr ""

#: trove/taskmanager/models.py:1591
msgid "Exception during nova action."
msgstr ""

#: trove/taskmanager/models.py:1593
#, python-format
msgid "Reverting action for instance %s"
msgstr ""

#: trove/taskmanager/models.py:1599
msgid "Restarting datastore."
msgstr ""

#: trove/taskmanager/models.py:1602
msgid "Cannot restart datastore because Nova server status is not ACTIVE"
msgstr ""

#: trove/taskmanager/models.py:1605
#, python-format
msgid "Error resizing instance %s."
msgstr ""

#: trove/taskmanager/models.py:1667
msgid "Error sending reset_configuration call."
msgstr ""

#: trove/tests/db/migrations.py:77
#, python-format
msgid ""
"The following migration scripts are missing a downgrade implementation:\n"
"\t%s"
msgstr ""

#: trove/tests/fakes/nova.py:281
#, python-format
msgid "volume status = %s"
msgstr ""

#: trove/tests/fakes/nova.py:333
#, python-format
msgid "Couldn't find server id %(id)s, collection=%(db)s"
msgstr ""

#: trove/tests/fakes/nova.py:353
#, python-format
msgid "Simulated event ended, deleting server %s."
msgstr ""

#: trove/tests/fakes/nova.py:496
#, python-format
msgid "Couldn't find volume id %(id)s, collection=%(db)s"
msgstr ""

